### ISSUE TITLE
[request] Can we add a second marker for massage was read? 

### ISSUE THREAD

**Issue by JobbeDeluxe** [deltachat/deltachat-android#105]
It is possible to add a second marker with email read confirmation? If that is received it could be displayed as an second mark in the massage.
That should be possible in the app and in normal email conversations, too.

**Comment by r10s** [comment]
Yes, this is planned, see https://github.com/deltachat/deltachat-core/issues/2

**Comment by JobbeDeluxe** [comment]
Sorry, I didn't know. That's wonderful!

**Comment by rizzopablo** [comment]
Please, make it optional, I really like to avoid sending reception/read receipts.
I don't want to know when the other one received or read the message, and I don't want the others to know when I receive/read the messages. I like the fact that you answer whenever you can/want to do it, without pressure. In Argentina we have a new very common expression of disgust: "me clavó el visto!" meaning that you're angry because someone read your message but did not answer inmediately. It's an effect of the anxiety caused by the reception/reading confirmation.

**Comment by r10s** [comment]
Read receipts will be available in 0.9.3

**Comment by r10s** [comment]
Some background information: https://github.com/deltachat/deltachat-android/issues/113
