### ISSUE TITLE
No icon for groups in the chatlist

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1074]
The icon that differentiate groups from private chats, is missing for group entries in the chatlist

- Android version: 7.1
- Delta Chat version: 0.920.0

**Comment by Simon-Laux** [comment]
It was a design choice to remove it.

**Comment by hpk42** [comment]
this change is intentional (i leave it to @r10s or @cyberta to argue for it :)
is it an issue for you/break expectations of users you know off?

**Comment by Simon-Laux** [comment]
There was an idea to make the group images square instead of round to have sth. to differentiate, but that would be a discussion for the forum.

**Comment by r10s** [comment]
yip, the removal was by design

- the icon-usage was inconsequent, eg. it appears in the chatlist but not in the title
- was never nice on desktop, never there on ios, syncing all three platforms seems to be some work - of course, doable, but then we noticed that none of the other bigger messengers use the icon at all
- removing the icon makes the chatlist cleaner, esp. when using emojis as group names
- it is pretty clear when seeing the chat name if it is a group or not, but in general, it brings them closer together

we'll see how this goes :)

**Comment by r10s** [comment]
i think, if needed, we can continue the discussion in the [forum](https://support.delta.chat); also as it is not only android-releated
