### ISSUE TITLE
systemmsg_action_by_{user,me} are hard to translate

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1098]
`strings.xml` currently contains strings like:
```
<string name="systemmsg_group_left">Group left.</string>
...
<string name="systemmsg_action_by_me">%1$s by me.</string>
<string name="systemmsg_action_by_user">%1$s by %2$s.</string>
```

Even in English "Group left by me" instead of "You left the group" or "I left the group" sounds wrong. In other languages it may be even worse.

It is better to split these messages into separate sentences that can be translated properly.

**Comment by r10s** [comment]
yip, this can probably be improved at some point.

iirc, the reasons for the string-building were:
- at some point we created the action strin independently, sent via mail and added the suffix on the receiving device. currently, this is no longer the case, however
- keep the work for the translators a bit smaller (otherwise 3 instead of 1 string would be needed for each action)

btw i am wondering if we need the "by me" wording at all. maybe we can show just he same string at all positions, esp. when these string go into mails, things are easily confusing. not sure how the current state is, however. we fixed many things on this in the past, iirc these strings pop up in various languages not long ago - compared with that, the current state is pretty nice :)

**Comment by angelo-fuchs** [comment]
Closing this for now as no one is actively working on it.
We should change this, but currently it is "ok" even though it is not "good".
The actual putting together of this done in the core and later on the translators on transifex need to work on this as well.
When we pick this up again we should simultaneously improve the messages that are written in the e-mails so that non-dc chat partners are less confused about what the messages mean.
