### ISSUE TITLE
reset advanced-config-settings on config-failures

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1106]
I have changed certificate checks configuration to Strict for my `testrun` account. After connection, logs show `cert_strict` for `entered_account_settings` but `cert_automatic` for `used_account_settings` afterwards.

Release 0.950.0

**Comment by r10s** [comment]
maybe this is a core issue, android does not touch the configured/used settings at all afaik.

does it work for desktop?

**Comment by link2xt** [comment]
It works with `repl`.

I did
```
> set addr ...
> set mail_pw ...
> configure
```

Configuration succeeds. At this point `configured_{imap,smtp}_certificate_checks` are `0`.

Then I do
```
> set imap_certificate_checks 1
> set smtp_certificate_checks 1
> configure
```

Reconfiguration succeeds:

```
$ sqlite3 1.db 'select * from config where keyname like "%_checks"'
12|configured_imap_certificate_checks|1
17|configured_smtp_certificate_checks|1
23|imap_certificate_checks|1
24|smtp_certificate_checks|1
```

**Comment by r10s** [comment]
ahh, it's about changing the settings :) i will check this out!

**Comment by r10s** [comment]
hm, i just tried it out with a testrun account and the current rust/android master, and the entered_account_settings are set as expected (according to the log at settings/advanced/log)

what i did:
- create a new account, cert=automatic
- after login, go to settings/profile/password+account/advanced and set cert-checks to "strict"
- hit ok, configuration is re-done - and cert-checks are as expected.

for both, initial-login and later-reconfigure, the following code is run: https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/RegistrationActivity.java#L442 - no idea what can go wrong there.

**Comment by link2xt** [comment]
Did it again on Android, this time it worked.

Probably connection failed and configuration process didn't succeed. Yet settings show selected settings, not configured one by default, so configured settings were still set to "automatic" and entered settings set to strict, so dialog showed strict. This is misleading, user may think that strict settings were successfully configured.

I think the fields should be prefilled with `configured_` values, not entered ones. This is what Desktop does.

**Comment by r10s** [comment]
> Yet settings show selected settings, not configured one by default

this is by design..

the idea is that the "login parameters" are detected and stored and used internally.
on re-configuring, the same parameters are used.
this ensures that, if some server-settings do change, at least a re-login works for the user - otherwise the user has to change/delete parameters that were never entered by the user and where the user maybe just has no idea that they exist.

so, putting using the configured-parameters as the entered parameters have the potention

> This is misleading, user may think that strict settings were successfully configured.
i think this issue is the 

maybe the 

this idea is that the addr, mail_pw etc. are 
if the user just enters email+password, and clicks on "configure",

**Comment by r10s** [comment]
> Probably connection failed and configuration process didn't succeed. 

so, there should be an error displayed then. however, of course, this is probably hard to say now :)

**Comment by link2xt** [comment]
Makes sense. If we change Automatic certificate checks behaviour to TOFU later, relogin should work if certificate becomes invalid.

But how do I see that strict certificate checks are used? Configured settings are non-strict and UI shows "strict". Maybe save the settings only if configuration succeeds? That would require another prefix or some other API modification.

**Comment by r10s** [comment]
> But how do I see that strict certificate checks are used? Configured settings are non-strict and UI shows "strict". Maybe save the settings only if configuration succeeds?

saving only on success won't work as the core needs it.

but the ui can reset the options on reconfiguration on failure to the state _before_ changes were done. 

there is an older discussion about that at https://github.com/deltachat/deltachat-core/issues/246 - the outcome was to clearify [dc_configure()](https://c.delta.chat/classdc__context__t.html#adfe52669a5bed893df78a620566dd698) - which, in fact, reads _"UI-implementors should keep this in mind - eg. if the UI wants to prefill a configure-edit-dialog with these parameters, the UI should reset them if the user cancels the dialog after a configure-attempts has failed. Otherwise the parameters may not reflect the current configuation."_

**Comment by link2xt** [comment]
What if the client crashes during reconfiguration? Both "last successful entered" and "configured" settings need to be atomically updated at the same time. That is why I said

> That would require another prefix or some other API modification.

above.

**Comment by link2xt** [comment]
@r10s Your solution will work most of the time, if it is not hard to implement maybe go for it now.

To make things more robust, we can implement the following API in the core:

1. Atomically remove all prefixed "new_" settings (possibly remaining from previous crashes) and fill "new_" settings in the database.
2. Client calls new API `dc_atomic_configure()`
3. It reads `new_` configuration and tries to apply it. If it succeeds, it replaces unprefixed configuration with `new_` and updates `configured_` atomically.
4. If it fails, it removes `new_` configuration.

**Comment by r10s** [comment]
just did a thing :) https://github.com/deltachat/deltachat-core-rust/pull/810
