### ISSUE TITLE
setup f-droid own repo?  

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#1126]
cehteh on irc brought this up: you can create f-droid repos that also host the binary packages.  See https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/ for a HOWTO.  I am wondering if that would be a path to more easily support F-droid?  cc @lefherz

**Comment by cehteh** [comment]
k, my idea was that (at least) debug builds, nightly/testing could be provided via a repository served by the DC developers themself. If anyone mind to set this up. That'll solve the issue that pushing things to F-Droid seems slow and not so easy to do. For better user experience the stable version should be served by the F-Droid main repo still.

On another note: Some projects have 'foo' and 'foo (beta)' packages on F-Droid already to let the users choose stability vs. bleeding edge.

**Comment by pabzm** [comment]
I support providing an own repository! Those are easy to use and would help people getting their hands on apk's early (and easier than watching github.com for new pre-releases). It would definitely be useful for nightlies, or beta versions, but maybe also for final, stable versions in order to bring releases faster to the users. We could still bring the stable releases into f-droid, too.

The Guardian Project (builds e.g. conversations) does this, too: https://guardianproject.info/fdroid/repo/

**Comment by cyBerta** [comment]
Bitmask Android uses a similar strategy for F-Droid Beta builds. But instead of having the overhead of setting up and maintaining an own repository, Bitmask Beta is distributed in Izzysoft's repository: https://apt.izzysoft.de/fdroid/
This way Beta releases can be distributed faster than using the official F-droid infrastructure. 

In order to reach more users, I would vote to distribute stable Delta Chat releases via the official repository - as long as we don't get an repository entry in F-Droid client's settings (like guardian project: https://www.linuxjournal.com/files/linuxjournal.com/ufiles/imagecache/large-550px-centered/u1000009/f-droid-02.jpg).

**Comment by missytake** [comment]
izzysoft doesn't provide apks which are already in the main F-Droid repository. In izzysoft's README there is this paragraph:

```
Another reason for an app getting removed from my repo is if it was added to 
the „official F-Droid repository“. Removal then mainly is to avoid confusion at
the users' end, due to signature mismatch on updates (if they installed an app
from the official repo, signed with F-Droid's key, and an update rolls in
earlier via my repo – which is usually the case – there'd be a warning
displayed if they'd try to apply that update). In some cases an app still stays
with my repo; usually it then uses reproducible builds so there'd be no
signature mismatch.
```

But if I understood it correctly, the F-Droid build and our apk build are two different apps, so the warning will most likely not appear. I'll ask him if he wants to include us.

**Comment by missytake** [comment]
Our apk is unfortunately too large to be included in izzysoft's repository - the hard limit is 30MB.

**Comment by DPTJKKVH** [comment]
Looking at the onboarding process I assume that DeltaChat will be creating an own repo. I actually would welcome that. However we need to find a way to inform everyone stuck in the main F-Droid repo that they need to add the F-Droid repo and reinstall DeltaChat.

A last Update (based on the old code basis) to the f-droid repo doing exactly that would be an idea.

**Comment by hpk42** [comment]
in any case, we need a new f-droid release, see #1177  -- before we have found out how much effort it is, let's put this "own f-droid" issue to rest.
