### ISSUE TITLE
Delta Chat Forgotten

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1130]
- Android version: 9
- Device: xiaomy mi a1 
- Delta Chat version: 0.960
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
Sometimes you "forget" to send the message, send others but that remains pending, I have to restart the application several times and eventually I get sent. It often occurs, with the first message, after a period of inactivity.
- Screenshots:
![deltachat-2019-11-25-191036](https://user-images.githubusercontent.com/52469394/69596922-43026280-0fd2-11ea-94c5-c0e8e21d3278.jpg)

- Logs:

**Comment by link2xt** [comment]
This can actually happen because we have separate timeouts for separate SMTP jobs. If the first message failed multiple times, its retransmission can be delayed while other messages are sent out.

We only send all messages out on maybe_network.

**Comment by agutierrez25249** [comment]
The problem continues in this version v0.970.0

**Comment by r10s** [comment]
it is  by design. i a message fails for some reason, the backoff times are increased, up to several minutes.

when then other messages are trying to be sent, they may succeed sooner.

the reason that we do no strict first-in-first-out is that servers may fail to send a specific message - and this would block all sending forever then.  
and this is probably even worse.
