### ISSUE TITLE
message order

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1151]
I'm not sure if there alreay a open issue or is it fixed in a current beta release.

So If is fixed, feel free to close my issue.

- Android version: 7
- Device: Huawei nova
- Delta Chat version: 0.5101.0
- Expected behavior: chronological order of sent and received messages
- Actual behavior: wrong order

See also the attached screenshot.

![IMG_20191208_061604](https://user-images.githubusercontent.com/6864851/70384691-157ac900-1983-11ea-976e-814dce8e036c.png)

**Comment by r10s** [comment]
the message list is sorted by receive-date, not by send-date; all new incoming messages appear at the end of the list.

the main reason for this is that otherwise, messages maybe easily missed completely by a user which might be even worse as a complete message is overseen.

there are some ideas to make this more obvious to the user, however. but it is a tricky thing.

**Comment by webratte** [comment]
OK, I understand.

But in groups (my case) it's better to order by the send time. (I think it's always the better way)

Im my case the answer was received bevore the question. A thread with this inconsistent is not really readable.

My group is relative small.
I belive in a larger group it's terrible.

How do it other popular messengers?

**Comment by r10s** [comment]
> But in groups (my case) it's better to order by the send time. (I think it's always the better way)

this raises the problem that you will easily oversee messages completely. imagine, someone is offline for a day and on that day 100 messages from other users come in. then the messages from the mostly-offline-user appear - they will be completely out of sight.

not sure what is better.

however, i think we should shift the discussion to the forum (if not yet there). it is not an android issue.

**Comment by webratte** [comment]
Sorry, I don't agree:

-Alice write question
-Bob answer to this question
-I see the order: Bobs answer - Aliices question.

So I can't understand what they plane.
Very often a group chat is made of questions and answeres.
And a Order not by sending time is not really helpfull.

**Comment by webratte** [comment]
Here is a forum post for this discussion:

https://support.delta.chat/t/order-of-messages/698

**Comment by r10s** [comment]
thanks, i am not for voting on this issue, but anyway :)

**Comment by webratte** [comment]
> thanks, i am not for voting on this issue, 
> but anyway :)

Sorry for the poll 😉

My hope, a poll will animate people to enter the discussion.

Maybe I'm wrong.
Let's see what happens.

**Comment by r10s** [comment]
nothing to be sorry for :) everything's fine :)

**Comment by adbenitez** [comment]
I agree with @r10s, it is better to sort in receiving order, a message from an user with a wrong date, may get forever lost too up in the chat, example: after reseting a phone

**Comment by webratte** [comment]
On the other hand, if you sort by incoming time the chronology of a discussion may come chaotic.

If you answer two questions.
One with yes and one with no.

And now the messages are in wrong order your friends will see yes for a question you answered with no.

I got a similar case. That's why I opened this issue.

How many devices which are connected to the internet do you know which not sync the system clock with the server?

**Comment by adbenitez** [comment]
there are also issues with timezones etc. it is better to have the message in the wrong "sending order", for example, if I lost my connection while traveling and a message couldn't be sent, then I get signal 1 hour later, the group will never see the awesome picture I was trying to send :P so it is better to ask your friends to avoid sending "yes" and "no" and give some context ;) example copy+paste the message you are replaying to, otherwise it will be always confusing, ex. if some other user ask another question some seconds before you sent your "yes" how would know your two friends to what question are you replaying??? also when we get the "reply" feature this will no longer be a real issue. Also it looks weird and buggy to the user to get new messages and don't see them at the end.

**Comment by webratte** [comment]
Sorry,
but the idea behind a messenger is to have a chronological thread of short messages.

Try to think like a non tech user.

If I have to use contextual replay for every message because I never know which question I will answer....

In this case I search for a other, correct working, messenger.

BTW. Wrong order is made by DC.
Wrong device time is made by the user.

Should DC issues be fixed or user issues?

There are much more user issues.
It's a hard work to fix them all 😉

**Comment by adbenitez** [comment]
My point is that I had seen a lot of non-tech users facing the issue of wrong date, and the messages just don't show in their Delta Chat because they are sorted at the top, they don't realize this until I send them an SMS or so, also I have had this issue my self more than once, and got some messages "lost" until I managed to get the time syncronized by the network.

I am pretty sure I chat a lot more than you (including groups of 50+ people) also do a lot of non-tech users over here, no one had complained about a "yes" and a "no" in the wrong order, maybe you are too unlucky?? ;)

I understand your point, but are you reading mine? it is really worse to lost a message. If you are in a group, receive 20 msgs then receive 1 msg with date older than that 20 msgs you will have to scroll up and try to find the message, non tech users will hate that for sure ;)

Regards,
adb

**Comment by hpk42** [comment]
So the question of send/receive ordering is a long going discussion ...
and i agree we need to move beyond send/receive order and rather think
about a) quoted replies  b) marking a message as having been delayed
in transport. 

does somebody know how Whatsapp/Telegram/Signal show a message i sent while 
being offline during which the group was chatting 10-15 messages?

**Comment by violoncelloCH** [comment]
Whatsapp e.g. just sets the time stampt to the time the message was actualls sent to the server... So if there is no network when sending, the message just gets the thime when it was actually sent out to the server (at least for the receiving side)

**Comment by webratte** [comment]
What about a user preference?
So you could gif the user the choice.

I know, we should not add to much options to keep the settings area as cleen as possible.

**Comment by r10s** [comment]
> Whatsapp e.g. just sets the time stampt to the time the message was actualls sent to the server... So if there is no network when sending, the message just gets the thime when it was actually sent out to the server (at least for the receiving side)

do you know where it appears in the list then? if there are 100 messages the user has received after this messages, how is the user pointed to that message?

**Comment by adbenitez** [comment]
@r10s if I understand well what he says, the message get the timestamp of the time when the message was sent to the server(successfully) not when the user pressed the sent button, so the message will be shown at the end of those 100.

**Comment by violoncelloCH** [comment]
Exactly @adbenitez
So if we assume correctly configured SMTP servers with network time etc, could possibly the SMTP sent timestamp be used as a (more) reliable sent time?

**Comment by webratte** [comment]
This sounds like a good idea 👍

**Comment by r10s** [comment]
and if the correct sending time is from yesterday? this will again show the "new" message far up in the list. i do not think this will solve this problem.

**Comment by webratte** [comment]
> and if the correct sending time is from yesterday? this will again show the "new" message far up in the list. 

If I understand it correctly this is exactly how other messenger handle this.

And if the sendig time it's yesterday, the message is sent yesterday.
IMHO it also should get the time stamp "yesterday" and also shown under the "time marker" yesterday because it's not a new message. It's a old message not a new message.

When exactly will happen a yesterday sent message will reach the receiver phone e.g. 20 messages (sent today)  in the list if you use the time where the message reach the sender's server?

**Comment by webratte** [comment]
If there are a few new messages it's possibe the last sent message will be out of sight.
Because it could be this message reach the recipient a few minutes after the last sent message.

This conversation is more chaotically then your described case.

In this chat is no visible order, no chronologic.

And still a message is missing (out of sight).

**Comment by webratte** [comment]
> even more tricky as currently we do not really depend on it for incoming messages.

That's why you fight for your solution.
Isn't it? 😜

**Comment by adbenitez** [comment]
@webratte I don't think it is common you get a reply before an answer, if A ask something, the message have to reach B, before B can start writting a reply to that message, are you telling me the message reach B but for some reason don't reach you, and even B can think, type his reply and send it it arrives to your inbox, and then A is answer finally arrives??? when in theory it was sent almost at the same time to both of you? I think the issue you have was other thing, I have never faced this issue myself, it is almost impossible I could get an answer from B before the question from A. You could get some unrelated messages sorted in the wrong order because they were sent just some seconds of difference, but have such a "chaotic" scenario as you try to picture it, I don't think it is even close to the real issue of receiving a notification for a new "ghost" message you can't see anywhere.

Sorry to the devs for the long reply, currently you have no time for this discussions on a **closed** issue, so I apologize, will not participate more here, I recommend to continue in the forum.

**Comment by webratte** [comment]
Take a look on my screenshot in the first post.

This happens in a group.

The picture was the replay of the textmessage.

Text message was sent by A
Picture was sent sent by B as a reply

The screen shot is the chat view of C

Because the wrong order the context was not recognizable for me (C).

Things like this happens more then one time. Probably sometimes I just don't realize it.

**Comment by webratte** [comment]
Ahh, and don't forget about the closed issue...

...YOU started discussion here after I opened a forum thread 😜
