### ISSUE TITLE
provide f-droid 1.0.x apk

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#1177]
We only have APKs and the Gplay release of the 1.0.x series currently. 
F-droid is missing and typically the build/release chain can take quite a while to make it to end-users.  It might be that it is not that hard. Some of us will try to see if we can get someone from or very familiar with F-droid at 36c3 to help us.  Any help and trying welcome.

**Comment by nathanael-h** [comment]
Hello, I saw the version 1.0.2 had been added to the file https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.b44t.messenger.yml#L592 ; so I did not understand where you had a problem in releasing update via f-droid. (In fact I wanted to help, but did not find how :laughing:  )

**Comment by r10s** [comment]
hi @nathanael-h first of all, great that you want to help on this issue!

to the updated build script: yes, the new version is detected, and probably we're in f-droids build-chain, however, when f-droid tries to call `ndk-build` this will fail with the error `ERROR:jni/Android.mk:deltachat-core: LOCAL_SRC_FILES points to a missing file` (you can try this by cloning this repo and call the command)

i assume, the whole apk won't be build then - or if f-droid does that, it won't work.

so, what is needed?

- Delta Chat uses the Rust programming language now for it's core, instead of the android `ndk-build`, we've created a script [`./ndk-make.sh`](https://github.com/deltachat/deltachat-android/blob/master/ndk-make.sh) that needs to be executed instead. the script calls the rust compiler for all needed platforms and calls then `ndk-build`  
so that would be the first step, do a pr on https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.b44t.messenger.yml to use this script.

- maybe this is already everything, however, in a way, the rust build environment is needed. not sure if and how f-droid supports that yet.

i think we should file a corresponding issue on gitlab/fdroiddata

**Comment by r10s** [comment]
i filed an issue on gitlab: https://gitlab.com/fdroid/fdroiddata/issues/1889 - so it is probably more useful to continue the discussion directly there (cc @cyBerta @hpk42 @Bubu @angelo-fuchs @Ampli-fier @toddy15 )

**Comment by r10s** [comment]
meanwhile, there is a pending pull request: https://gitlab.com/fdroid/fdroiddata/merge_requests/6132 - but there are still some issues with that.

**Comment by r10s** [comment]
the pr is accepted and merged meanwhile and the build seems to succeed locally, however, for whatever reason https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_574 reports an error. 

@missytake can you have a closer look, please :)

**Comment by angelo-fuchs** [comment]
@r10s Your referenced build says "Build Succeeded." Current Version on f-droid is 1.1.2.
So mission accomplished.
