### ISSUE TITLE
Reply to only one group member appears in group

### ISSUE THREAD

**Issue by nst0022** [deltachat/deltachat-android#1178]
- Android version: 10
- Device: Google Pixel 3a (Delta Chat), iPad 9.3 (non-"Delta Chat")
- Delta Chat version: 1.0.0
- Expected behavior: Reply to one member only should go to a one-to-one thread, not the group
- Actual behavior: Reply to one member goes to the group
- Steps to reproduce the problem:

I (named C) have a group named Group-1 with two email-only, non-"Delta Chat" members named A and B.

If I send a message to the group, and A replies to me only, then this reply erroneously goes to Group-1.

The reply should go to chat A-C.

Related problem: If I long-press this answer and select (i) from the menu, I do not see any recipients, so I cannot tell, whether this was sent to me only, or to the group.

**Comment by r10s** [comment]
in fact, these group replies to only some group members are a problem.  
there are also other issues possible eg. a group with 6 members where a normal mail client replies to only 3 of them.

often, these partial replies are by accident - if you want to send a mail to one person you can also send a normal mail to this person.

delta chat cannot really decide this and putting partial group replies to other chats may not make things clearer.

we will target this issue in the same we show encypting and signing inssues: 

- we will show the mail in the context of the group - the mail-user _has_ hit reply on a group message, so this makes some sense

- but instead of the message shown directly, there will be a clear hint about what was going wrong - including sth. as "click here to see the original info"

this way, the receiver can decide if the sender has done sth. wrong and inform her/him (eg. if the mail content obviously addresses the whole group)

**Comment by nst0022** [comment]
I would not think this complicated.

As a normal email user, you have just two options when replying:

1. reply to all
2. reply (to sender only)

(A Delta Chat user does not have these options, either s/he replies in the group, or in a one-to-one chat)

So, just "reply to sender" is the exemption.

In that case, you know, that it is the reply to a group message, 
but the CC field is empty, 
so, just ignore the group and treat it as a normal, incoming one-to-one message.

**Comment by r10s** [comment]
> so, just ignore the group

but this may be just wrong. many email-users do not really know the difference between reply and reply-all and/or hit things accidentially.

also, it _is_ a group reply, so it seems to be wrong to show it outside the group.

**Comment by r10s** [comment]
also, iirc, we had the behavior group-replies to to one-to-one-chat at some point - and it turns out it confuses users even more. assume a reply with just the text "yes".

so, i think, showing partial-group-replies in the group with a warning before seems to be a good compromise.

**Comment by nst0022** [comment]
Understood :-)

**Comment by adbenitez** [comment]
I think XMPP has this "private reply in group" where in a XMPP room you can send a secret message to only one(or more?) members of the group, I think this is similar and could be even a wanted feature in the future, so this could be show in the future as a "direct/private message in group" but I think for now the warning is already a good solution :+1:

**Comment by r10s** [comment]
closing this here, there is no actionable item for the android-ui. of course, discussion can be continued at https://support.delta.chat

**Comment by Norbert80** [comment]
> private

I just hat the same idea inspired from XMPP (and the app Conversations).
