### ISSUE TITLE
switch off encryption has no effect

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1186]
See title

- Android version: 7.0
- Device:  Huawei nova
- Delta Chat version: 1.0.2

**Comment by r10s** [comment]
@webratte - thanks for your post.

can you please provide some more details?
what you are doing, what you expect, how devices are set up? delta-to-delta or delta-to-mail  etc.

please note, that replies in a chat that is already enrypted will stay encrypted even if "prefer encrypt" is set to off. this is because of the autocrypt-policy that replies must always be encrypted - and writing to an existing chat is always a reply in this sense.  
we were already thinking this over here and there, however, this is another discussion :)

**Comment by webratte** [comment]
Thank you for explain.

In this case the issue can be closed.

I just would like to switch off encryption for testing https://github.com/deltachat/deltachat-android/issues/1179

See my last post.
