### ISSUE TITLE
Refresh contact list

### ISSUE THREAD

**Issue by thenktor** [deltachat/deltachat-android#119]
Hi,

it seems there is no option to refresh the contact list. I've edited some contacts, but changes do not appear in Delta Chat.

**Comment by r10s** [comment]
Contact-app -> Delta Chat synchronisation is done as  follows:

- names are synced if no chat is started (this is because the user can set another name in Delta Chat and we do not want to make things more complicated)
- profile pictures are always synced
- there is no need to sync the e-mail-address as it is used as the primary ID
- other fields are not used and there is no need to sync them

The other way round, Delta Chat does not write anything to the Contact-app.

**Comment by thenktor** [comment]
> there is no need to sync the e-mail-address as it is used as the primary ID

I've removed some outdated e-mail addresses from my contact list. Does this mean I have to remove them from Delta Chat manually, too?

**Comment by r10s** [comment]
Yes, if you really want to. Currently, Delta Chat has no address book in this way, it only collects the email addresses from different sources.

**Comment by thenktor** [comment]
OK.  This probably is because chats can also be started with arbitrary e-mail adresses.
May it be a good idea to have a contact list, that is in sync with the phone contact list and another one that collects other e-mail addresses?
I think GMail or Thunderbird do it the same way: there you can chose from addressbook contacts and aggregated contacts.

**Comment by r10s** [comment]
Contact requests should be only added if they are known in any way, eg. if the contact was CC'd by a known user before.

**Comment by thenktor** [comment]
Yep, just noticed that there aren't all contact request addresses in there. But there was a author@noreply.github.com added, which is a CC address from github notification mails.

**Comment by r10s** [comment]
> Contact requests should be only added if they are known in any way, eg. if the contact was CC'd by a known user before.

The last version improves this behaviour; not all mailing list recipients automatically become "known" users.

Regarding the introducing question of this issue, I think we can close it here.
