### ISSUE TITLE
laggy imap results in timestamp woes: broken conversation order

### ISSUE THREAD

**Issue by eveofdestruction** [deltachat/deltachat-android#1229]
- Android version: 4.4.4 (media center, cannot upgrade)
- Device: mystery chinese box Amlogic S912
- Delta Chat version: fdroid 0.510.1
- Expected behavior: meta data should preserve message ordering
- Actual behavior: minutes later messages arrive in a batch out of conversation flow order

I will not impeach the free smtp/imap provider in public view.

It would seem timestamp alone is not sufficient to prevent disorder.

**Comment by gerryfrancis** [comment]
Version 0.510.1 was released more than half a year ago. Please use the latest version 1.0.3 and report again, thanks.

**Comment by r10s** [comment]
yip, imap as such is probably improved since then, at least there will be other issues, the whole core was replaced since 0.510 ([core-c](https://github.com/deltachat/deltachat-core/) to [core-rust](https://github.com/deltachat/deltachat-core-rust/))

wrt sorting: there are already several some discussions ongoing, eg. at https://support.delta.chat/t/order-of-messages/698
