### ISSUE TITLE
Wrong timestamp for messages

### ISSUE THREAD

**Issue by rootuser1** [deltachat/deltachat-android#124]
Sometimes messages show up delayed with a timestamp which is different to the original sent/received time, e.g.

K-9 mail:
message A: 12:00
message B: 12:04
message C: 12:08

Delta Chat:
message A: 12.00
message C: 12:08
message B: 12:10

Anyone having similar issues?

**Comment by r10s** [comment]
If the sending time of a new message is older than the newest message time, we use the receive time instead. We also use the receive time when the sending time is in the future. Both cases are exceptions.

This is to show fresh incoming messages at the end of the list. Otherwise they will pop up somewhere in the chat where they may be not seen at all. In messengers, new messages should be at the end of the chat.
