### ISSUE TITLE
Vertically spaced characters are displayed outside text zone

### ISSUE THREAD

**Issue by EchedeyLR** [deltachat/deltachat-android#1272]
- Android version: 7.1.2
- Device: BQ Aquaris U Plus
- Delta Chat version: 1.2.1
- Expected behavior: Display characters inside the text zone in the message bubble
- Actual behavior: The characters separated vertically are displayed outside text zone and like 1 pixel outside the message bubble in some cases.
- Steps to reproduce the problem: Use vertically displayed/separated characters in some messages
- Screenshots: 
![2020-03-27-07-44-1](https://user-images.githubusercontent.com/56733813/77733552-f8840780-6ffe-11ea-9dbb-24d5e0788f84.jpg)

![2020-03-27-18-36-1](https://user-images.githubusercontent.com/56733813/77788934-074bd800-705a-11ea-8e05-308340ee249d.jpg)

**Comment by angelo-fuchs** [comment]
For testing purposes, here is some text with such chars. When sent to a DC Android, the elements above the "y" are not properly displayed.

É͆̓̃̿͆̄ͣ̑͒̔ͧ̍nter ̀̀ͩy͂͗̂̑̐͗̌̾ͩͥour̚ ̂teͥͨͤ͋̈̑̍ͬͪ̊x̓ͥt̊̑̅̔ͥ̍̇͒̐̿̒ ͯ̏͑̾͑ͬĥ̄͊ͩͥ̃er̃̾̊̐e

**Comment by angelo-fuchs** [comment]
There is a workaround:
When you want to send an overlarge text you write a . then some newlines, then your text and then some more newlines and a dot.

We do cut newlines at the beginning and end of texts, so the dots are to prevent that from happening.


For now I'm closing the issue as it is not something anyone is working on now or in the foreseeable future (as it does not come up in regular writing and we have more urgent things to work on). I will put it into project Resurrection so that we take care of it when there is time.

So, whenever we solve this, the place to detect and handle such characters is in 

> org.thoughtcrime.securesms.components.emoji.EmojiTextView#setText

**Comment by EchedeyLR** [comment]
Well, if that type of characters exists its because someone in the world need them. No idea if its attached to some natural languages (I am sure some of them are attached for real) which could make the "not common" to "common in that case" but anyways I am glad you made a workaround. 

About project resurrection, I never replied but when an issue have just a workaround or is not going to be fixed, instead of closing it + add to the list as if it was solved, I would maintain it opened so more people could check in the opened issues (as many people only check there) to know about it or participate.

**Comment by EchedeyLR** [comment]
Could you reference that workaround in the documentation and put a reference to this issue to people checking it know about it?

**Comment by angelo-fuchs** [comment]
@EchedeyLR I checked, no actual language uses more then four diacritic signs, so all situations where that is needed would be the jokes.
Unicode allows for arbitrary many diacritic signs around any character.

wrt "accessibility and screen readers": Scaling the font should work fine and, as there are no pronunciations for ĥ̄͊ͩͥ̃, screen readers wouldn't work for such characters anyway. Regular situations should not be affected by it.

Putting the workaround in the docs: https://github.com/deltachat/deltachat-pages/blob/master/en/help.md Here? If you feel like it should be mentioned, please do open an issue on the deltachat-pages issue tracker. If this becomes a frequently requested feature it will get its entry there on its own.

Project Resurrection and keeping it open: There were long discussions about the pros and cons and we decided to have the issue trackers only for things that are worked on, so that we don't have thousands of open issues that just linger around. I know that this feels odd at times (it does for me too when one of my issues gets closed because of it).

**Comment by EchedeyLR** [comment]
> wrt "accessibility and screen readers": Scaling the font should work fine and, as there are no pronunciations for it, screen readers wouldn't work for such characters anyway. Regular situations should not be affected by it.

I have classmates using screen readers with built-in OCR for general. That caused many issues in the past with specific handwriting as could happen here now. That is the issue I reference.

> so that we don't have thousands of open issues that just linger around

In the end, it's that, hide many not existing and not solved issues that should be in a future. Project resurrection doesn't provide, itself, visibility for general users as I had to point some of them there time ago. It is for "developers" purposes more than any contributor or any user.

> Putting the workaround in the docs: https://github.com/deltachat/deltachat-pages/blob/master/en/help.md Here? If you feel like it should be mentioned, please do open an issue on the deltachat-pages issue tracker. If this becomes a frequently requested feature it will get its entry there on its own.

Is it not easier to move this issue or part of it to there if you are such main contributor?. I also don't think that asking for the site for me would be better. I don't know of the project structure that seems to change every time and I have to ask some users sometimes or waste time checking.

In general, I would think the FAQ, which is embeded with the software, a better site. If help pages are already in the device, it's great.
