### ISSUE TITLE
Format files using 2 spaces for indentation

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1278]
I don't mind if it's 2 spaces, 4 spaces or tabs but can we please have it uniquely for the whole project?

**Comment by r10s** [comment]
yip, this would be great!

i think, we can target this once the pr-count is down to zero, otherwise, this would be too much effort.

i personally would tend to 4 spaces, this is also what we use in other projects as core, ios, python. desktop otoh seems to use 2 spaces.

**Comment by r10s** [comment]
> i personally would tend to 4 spaces, this is also what we use in other projects as core, ios, python. desktop otoh seems to use 2 spaces.

thinking it over - as we're pulling in source code from signal from time to time, we should also use the same spacing as used there - otherwise, we're just making our life harder :)

however, tbh, i am also not sure if enforcing a unique code/tab style is worth the effort. at least not for the code, we're pulling in.

**Comment by Hocuri** [comment]
Signal uses 2 spaces AFAIK.

**Comment by r10s** [comment]
yip, i and i think also the majority of our files use 2 spaces, so maybe use this as a target. there are not so many files to change then.

**Comment by r10s** [comment]
closing this, it does not work this way :)

i think, we agree that we want to use 2 spaces for formatting for new files - existing files taken from some upstream stay as they are - and the few ones formatting differently can be reformatted when working on them the next time.
