### ISSUE TITLE
notification icons appears and disappears

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1296]
when there are unread messages in different chats, there are several appearing and disappearing notification icons in the system-bar.

for fixing that, we should probably move towards using notification-channels as they are supposed to.

this issue is a bit older, thought, it was filed already :)

**Comment by adbenitez** [comment]
don't know if it is related but when you open a chat, the other old notifications are re-issued, every time you enter a chat, it is a bit annoying and covers chat name and menu, and if you dismiss the notification messages are marked as read, so you have to wait the notification to go away

**Comment by r10s** [comment]
> don't know if it is related but when you open a chat, the other old notifications are re-issued

yip, this is what i meant, but i failed to describe it accurately :)

**Comment by solidboredom** [comment]
actually in my case it does not even appear first, but the #1295 issue is closed as a duplllicate so i assume this is the original issue. in my opinion this is the  single most important problem or feature request (permanent notification) hindering deltachat from being used at all. please! please! please!

**Comment by r10s** [comment]
we should differentiate between 1. "messages are not fetched in background" and 2. "i'd like to have the notification-display different". 

#1295 was closed because it is already initially a mix of that and also duplicates things already discussed and/or contains feature requests.

@solidboredom if your issues is about 1.  "messages are not fetched in background" - there were several issues like that in the past, some of them could be solved, some of them not because they were not reprodible, see  https://github.com/deltachat/deltachat-android/issues?q=is%3Aissue++label%3Anotify

so, if you have checked, "background" is allowed on your phone (see also https://dontkillmyapp.com), feel free to open a concrete issue, with as many information as possible, also have a look at the other ones  - please keep in mind that we cannot do much about issues that just read "messages do not come in on my device" - things are becoming hard here because on many devices things work as expected  :)

**Comment by solidboredom** [comment]
to @r10s :
i agree it is good to keep apart the issues. so what open issue i could move to with my comment/proposal to implement permanent notification like telegram(f-droid)/conversations/riot/(essentially everyone else). 
what you describe is sadly all known to me and tried by me times and times on my own phone and that of my friends i have tried to convince to use deltachat. i actually have fixed the problem on my Sony Xpreria, but that does not help much, since i need other people to be notified of my messages too... :-( As you can see in my comment under #1295. i am personally absolutely sure this is the single most important problem/feature of deltachat (now that the provider database is in place anyway) so just closing the issue and waiving off to read dontkillmyapp and granting backround privileges will make sure nobody, but the very most enthusiastic enthusiasts like me, will perhaps be able to use it. (and i have a proof of 5 out of seven friends, read more under #1295). that would be very sad

**Comment by r10s** [comment]
for sure, we are regarding these issues as important.

btw there is also https://support.delta.chat/t/show-a-permanent-notification/943

**Comment by solidboredom** [comment]
@r10s oh ok. i will head to  https://support.delta.chat/t/show-a-permanent-notification/943
 for further discussions on the topic
thanks
