### ISSUE TITLE
To many emails in the email apk

### ISSUE THREAD

**Issue by andy43226** [deltachat/deltachat-android#1307]
I'm using DeltaChat and it's a very nice apk, but is very anoying when my email apk get the emails generated from DeltaChat. I am using a same email address in two different apk (DeltaChat and otheremail client) and I would like my email apk does not get the emails generated by DeltaChat

- Android version: 7.0
- Device: LG Stylo 2 Plus
- Delta Chat version: 1.3.0
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by r10s** [comment]
if your are not using multiple devices for Delta Chat, for outgoing mails, please make sure, "Settings / Advanced / Send copy to self" is disables. this way, outgoing mails are not sent to yourself and not to other email apk therefore.

otherwise and for incoming mails, Delta Chat cannot do much on that as we do not have the other app under control.

however, you have some options:

- you can try configure the other app so that it ignores Delta Chat messages, depends a bit on which other program you are using. 
- you can use a dedicated account
- you can let Delta Chat handle the address exclusively 

for detailed discussions and for  more help on that, however, please go to the [support forum](https://support.delta.chat) - you can log in there with your github account.

as there is no direct actionable item, i am closing this.

**Comment by AndreazLattmann** [comment]
... you can log in there with your... awesome Delta Chat!
