### ISSUE TITLE
Subject line missing for contact requests

### ISSUE THREAD

**Issue by hardy1957** [deltachat/deltachat-android#1321]
English translation:
The subject line is missing for contact requests. The view should be renamed into "Mail Inbox" so the use is more intuitive.
Otherwise a nice mail program.

Original:
Die Betreff Zeile fehlt bei den Kontakt Anfragen. Die Seite sollte in mail Eingang umbenannt werden. Dann ist die Bedienung intuitiver. 
Sonst ein gutes Mailprogramm.

**Comment by angelo-fuchs** [comment]
I can reproduce this. Subject Line is not displayed in contact requests.

**Comment by r10s** [comment]
just tried that, actually, the subject line is shown for contact requests as well as for other mails coming from non-delta-clients:

![Screen Shot 2020-04-28 at 11 28 31](https://user-images.githubusercontent.com/9800740/80471773-2b922180-8944-11ea-9d68-a475b0019c53.png)

maybe this issue is about subjects with "Re:" etc. that are actually hidden by some heuristics? however, this is not related to contact requests.

**Comment by gerryfrancis** [comment]
According to the screenshot, name of sender, subject, and body are put in one line only. Chances are that if the contact name was very long, the other information might be lost/truncated.

**Comment by r10s** [comment]
> Chances are that if the contact name was very long, the other information might be lost/truncated.

that may happen, however, this is probably not the initially reported issue.

i am closing this for now as there is no actionable item, we can reopen, if we get more information.
