### ISSUE TITLE
"group" message did not sent to all participants

### ISSUE THREAD

**Issue by vitalyster** [deltachat/deltachat-android#135]
I have create "group" for some people in my contacts. But not all of them have each other in their contacts. They receive messages from me, but not from others they have no in contacts, and there is no any warnings to guess problem, people just think "app not working" :)

**Comment by kollokollo** [comment]
I observe the same issue. Also People could get confused if the use two different email adresses and delta chat can only listen on one of them.

**Comment by r10s** [comment]
Oh, is this true? Thank you for the hint, we will check this.

**Comment by kollokollo** [comment]
Could it be, that it matters, if the email address in the contact has some capital letters in it?

Like : Hans.Marinstedt@web.de instead of: hans.marinstedt@web.de

I could not really test this, bit there is a suspicion, that the addresses are sometimes treted as two different contacts, and sometimes not.

**Comment by kollokollo** [comment]
Also I observed this issue in following group: 
3 Members using delta chat and other groups containing only them do work fine.
a fouth member was added but does not use delta chat, and has never replied or send anything to the group (and may not me in the contacts list of all other three members). 

Then, one of the 3 Members does not see any posting in the group, except for his own, but he can post to the group, ant these postings can be seen by the others.

Also I could observe, that since the fourth member was added, the coversation was not encrypted anymore. Strange...

**Comment by lobit0** [comment]
Hi all.

> Could it be, that it matters, if the email address in the contact has some capital letters in it?
> Like : Hans.Marinstedt@web.de instead of: hans.marinstedt@web.de

I know Gmail will treat hans.marinstedt@gmail.com and hansmarinstedt@gmail.com as the same address. Maybe Delta Chat doesn't and that's what causing trouble?

**Comment by r10s** [comment]
this should be fixed with https://github.com/deltachat/deltachat-core/pull/118 , the change will be released with 0.16.0 then
