### ISSUE TITLE
Imap port ignored

### ISSUE THREAD

**Issue by x011** [deltachat/deltachat-android#1378]
Delta for android connects to imap port `143` even if port `993` is specified on advanced.

![Screenshot_Delta_Chat_20200522-135314_1_1](https://user-images.githubusercontent.com/4313821/82669790-f4a5e780-9c33-11ea-9f6b-81263e71b39d.png)

**Comment by r10s** [comment]
thanks for your input.

in fact, the original given port is not ignored - however, when failing, other ports are probed.

this, however, has to be turned out as not the best idea as this makes finding errors harder, there is already an issue for that at https://github.com/deltachat/deltachat-core-rust/issues/880 - i am closing this one therefore.

**Comment by x011** [comment]
However, deltachat doesn't work with valid email credentials and shows wrong information when displaying errors, like the port which supposedly should connect to. Too many errors for something simple,  I'm skipping this app.

**Comment by r10s** [comment]
sorry to hear that, we try to improve all the time, however :)

**Comment by x011** [comment]
It's working now, thank you, however :-)

**Comment by r10s** [comment]
great! and again thanks to push us to finally fix the initial issue!
