### ISSUE TITLE
Second checkmark for "read receipt" is not shown automatically

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#140]
Second checkmark for "read receipt" is not shown automatically in an active chat.
Switch to main display and back to related chat shows the second checkmark.

**Comment by csb0730** [comment]
No one notifies this issue?

**Comment by r10s** [comment]
I have tested it here - and i cannot reproduce the issue.

**Comment by csb0730** [comment]
I noticed this while testing with my friend a month ago. At that time we both used dc v0.9.3. I supposed an actualization problem between core and user interface.
Meanwhile I've no possibility to double check this again. I've no other peer using dc and (with last changes in dc) no other MUA will sent/ask about a read receipt (second checkmark). Maybe this issue is solved now anyway by disabling read receipt from other MUA than dc. 
With r10s's chat this issue I didn't see! With dc only communication I suspect that this is not an issue.
So what to do?
Maybe this issue can be closed now and only should be opened when detected again.

**Comment by kollokollo** [comment]
I have noticed this issue. For a while the second check worked with a chat, but then it stopped working: No checkmark is show al though the messages were received. I dont know why, and I do see it only on one chat. Others do work correctly. Maybe it has something to do with the mail providers.

**Comment by kollokollo** [comment]
Aehm, different to the original posters situation, the second check is not shown at all, even when swtching back and forth in the ui. I think the receit (Empfangsbestaetigug) was really not received, maybe not send by the other deta chat client. Or removed by the mail provider.

**Comment by r10s** [comment]
@kollokollo, @csb0730: So it works first and stopped working after a while? And if the chat is entered again, the second check mark is shown immediately?

Another note: Due to issues with the read receipts from normal MUAs, see https://github.com/deltachat/deltachat-android/issues/121 , Delta Chat 0.9.4 and future versions use a different header for requesting them.

As a result, read receipts from 0.9.3 or older or from normal MUAs are not shown in Delta Chat 0.9.4 (and the other way round)

**Comment by kollokollo** [comment]
Yes, 
I can confirm, that the problem startet after I have updated to the August Version of delta chat, while the other client has not yet updated. I need to check what happens, once the other client is updated as well.

**Comment by kollokollo** [comment]
However, I have not noticed any problem with the July version, nothing related to Issue #121. It used to work even with normal mail clients, at least for me an my chat partners.

**Comment by r10s** [comment]
Yes, it would be great if you can re-check it with the most recent versions of Delta Chat :)

**Comment by kollokollo** [comment]
Confirmed: It seems to work, in case both partners use the latest (f-droid) version.

**Comment by Ampli-fier** [comment]
I'm using v0.9.6 and noticed this when testing group messages. But this issue seems to be generic.

When a receipt is coming in too fast (on the receiving device I was already in the Chat) then it is missed.
It looks like messages between _T4 IDLE interrupted_ and _T4 IDLE start_ are not recognized (~ 2s).

`08:06:08.352 DeltaChat: T2: Signal job thread to wake up...`
`08:06:08.516 DeltaChat: T2: Job #1 done and deleted from database`
`08:06:08.528 DeltaChat: T2: Executing job #2, action 700...`
`08:06:09.316 DeltaChat: T4: IDLE interrupted.`
`08:06:09.316 DeltaChat: T2: Appending message to IMAP-server...`
`08:06:09.441 DeltaChat: T2: Message appended to "Chats".`
`08:06:09.594 DeltaChat: T2: Job #2 done and deleted from database`
`08:06:09.599 DeltaChat: T2: Job thread waiting for signal...`
`08:06:09.599 DeltaChat: T2: Job thread checks for pending jobs...`
`08:06:09.608 DeltaChat: T2: Job thread waiting for signal...`
`08:06:1x:xxx <== received read receipt which is not shown`
`08:06:11.511 DeltaChat: T4: IDLE start...`
