### ISSUE TITLE
Emoticons do not work on Android 4.0.3

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#142]
![b](https://user-images.githubusercontent.com/15250834/28783913-1de3a498-7612-11e7-9930-f2fc2e2aa90c.jpg)

Emoticons are not displayed on my phone (Android 4.0.3). 
Not in the chats, nor in the emoticons menu (there is only one icon displayed, the black heart). All other menu fields are empty, or better: blank. Maybe the icons are missing.

On other/newer phones it works.

**Comment by r10s** [comment]
Yes this may happen, esp. on older devices the system's unicode support is not that good (in fact, they're only glyphes as other characters; the same issue may happen if someone sends you some text using different alphabets as russian, arabic or greek)

However, as this issue is already fixed by more recent android versions, I do not think that it makes much sense to invest time and money into this issue (eg. by rendering all emoticons ourself) - esp. as this may open further other issues (eg. incompatible emoticons when using the clipboard on the same device, no aotumatic support of new emoticons, unfamiliar emoticons ...)

**Comment by kollokollo** [comment]
Hm, yes, I see. Is there a possibility to install the missing glyphs e.g. by using a third-party app?

**Comment by r10s** [comment]
As this issue is not related directly to Delta Chat, I think we can close it.

**Comment by kollokollo** [comment]
Thanks for the link, but isnt this for iOS only?

**Comment by r10s** [comment]
The linked forum posts are a about how to replace the Emoji-Font on Android devices. The font is replaced by the iOS-Emoji font IIRC.

**Comment by kollokollo** [comment]
OK thanks; wer lesen kann...

**Comment by kollokollo** [comment]
The method described above in the link didnt work out for me. I think this works only for Android 4.1 and later, I have Android 4.0.3. (Which does not support color fonts)

But:  I found a solution (with monochrome emotjis):

1. Download NotoEmoji-Regular.ttf from this project: https://github.com/googlei18n/noto-emoji
2. Using adb on your rooted phone: make /system writable (mount -o remount,rw /system)
3. put NotoEmoji-Regular.ttf in /system/fonts/
4. Add following lines to /system/etc/fallback_fonts.xml

`
    <family>
        <fileset>
            <file>NotoEmoji-Regular.ttf</file>
        </fileset>
    </family>


`
5. reboot the phone

**Comment by r10s** [comment]
Okay - this seems to be a solution. If you like, you can create a blog entry for it a https://delta.chat/en/blog ...

**Comment by kollokollo** [comment]
Well, one could create an installer app for rooted phones, which does it, but this seems to be overkill. Whoever still uses such old phones (like me) should be able to fiddle with adb. Maybe there are only few of us. I think I was the only one missing emotjis in DC.
