### ISSUE TITLE
App freezes during account setup

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1426]
on 1.10
steps to reproduce:
1. fresh install
2. tap on 'Log in to your server'
3. enter email
4. focus on password field -> ANR

**Comment by r10s** [comment]
this is probably because dc_get_oauth2_url() may block on "no network" or so now. https://github.com/deltachat/deltachat-core-rust/pull/1626

**Comment by r10s** [comment]
@cyBerta @link2xt i did not manage to reproduce the anr, tried on 5 devices and the same amount of different emulators. @cyBerta it happens to you only when there is no network? otherwise, this might be different from what @link2xt reported.

however, i am totally sure it may happen as dc_get_oauth2_url()`dc_get_oauth2_url()` does network now.  
to write a proper thread-handling on android, i am forcing a test-sleep() in rust-core now :)
