### ISSUE TITLE
Contact request disappears from chat list after "Contact requests" view opened

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1432]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10.

- Delta Chat Version:
1.10.0.

- Expected behavior:
A contact request remains in the chat list after the user has opened the "Contact requests" view (and has gone back).

- Actual behavior:
A contact request is removed from the chat list unless that contact launches another request. However, when accessed, the "Contact requests" view still serves (all) incoming contact requests.

- Steps to reproduce the problem:
-- Let anyone (who has not been confirmed as a contact) send a message to you.
-- While viewing the chat list that shows the contact request, switch to the "Contact requests" view and go back.

- Logs:
N/A.

- Remarks:
This is a different behavior than in Delta Chat Desktop (current version 1.3.4) where the contact request entry does not disappear from the chat list (in left window area) after the "Contact requests" view has been opened.

**Comment by r10s** [comment]
this is by design currently.

contact requests disappear from the chatlist once there is some action with them by the user.

the action is either a tap on the item in the chatlist or opening the whole list of contat-requests.

if course, this can be improved and can be discussed in the forum at https://support.delta.chat
