### ISSUE TITLE
Delete Chat - Why are Messages not deleted on Server?

### ISSUE THREAD

**Issue by gitkald** [deltachat/deltachat-android#144]
If I delete a Chat, DC told me, that the messages not be deleted on Server. Why?

At the moment, I must delete every single Message from a chat, to clean up my inbox on server. Thats a lot of work, to clean up the server, if I had a long chat.

When I close DC and delete all chats, for example in Thunderbird, start a new chat, with the same mail adress, all messages from the old chat, shown in DC. On Server, where I deleted them with Thunderbird, they will never been shown again.

**Comment by kollokollo** [comment]
It would be better to have an option to delete the files on the server or leave them there (for later reuse, if one again joins the chat). Maybe it would be even better, if one had a function to export the while chat into a file. In that case, all files could be deleted from the server always.

**Comment by r10s** [comment]
> If I delete a Chat, DC told me, that the messages not be deleted on Server. Why?

This is because also "normal E-Mails" may be shown in the chat and deleting them would be at least unexpected.

**Comment by zoff99** [comment]
so add an option then?

**Comment by r10s** [comment]
Well this issue is about _why_, I think this is answered.

An option to delete all messages on a chat on a server may result in the same problems - users might not expect non-chat-messages being deleted when deleting a chat. I we delete only true chat messages, other users may wonder why some messages are deleted and others are not. Other issues are about not to display non-chat messages at all, if we do this, the deletion problem here is solved.

So, for now, I would not add an option until there are more general questions pending.

However, as a simple workaround, I could imaging a "Select all messages" in a chat which can then be deleted explicitly before the chat is deleted itself. This would solve the problem in a way, the user has selected the messages to delete himself and _sees_ what will be deleted. Maybe this is a fine solution for all cases. If so, maybe we should open a feature request for this.

**Comment by r10s** [comment]
> If so, maybe we should open a feature request for this.

It already exist:
https://github.com/deltachat/deltachat-android/issues/76
