### ISSUE TITLE
Ask the user about the "Show all emails" setting on start

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1516]
@hpk42 's idea:

During onboarding and after we scanned the history, we might ask the user something along the lines of
"oh, it appears you are using this e-mail account also with another email program. Do you want to a) see all your e-mails in Delta Chat or b) only see chat conversations from other Delta Chat users?"

My own note: Many email providers place 1 or 2 emails in the inbox after an account was newly created. So, we can only assume that the user is already using their account if there are, like, 5 or more emails already.

Opening an issue here because I think that the core can't do much about this (or should it still go into the core tracker?)

**Comment by gerryfrancis** [comment]
Interesting approach. My two cents:

We must be careful when Delta Chat was installed once as the only mail client and configured to not move mails to the DeltaChat folder. If that was the case and the user reinstalls Delta Chat, the "assumption" that other clients have been used, too, may be wrong.

**Comment by Hocuri** [comment]
To speed up onboarding (the user already has to do quite a lot of things) we should somehow postpone this question, I think. Like:

On install, set ShowEmails to "All" and already show all of the user's past emails (or maybe only the ones from the past year).
Wait until the user opens DC for the second time or is using it for 10 minutes. Then ask:

```
It appears you are using this e-mail account also with another email program.
(•) Show all e-mails in Delta Chat (default)
( ) Only see chat conversations from other Delta Chat users
                                                                  Ok
```

in a floating dialog where (•) is currently selected. Then, if this is technically possible, change the chats list in the background dynamically when the user changes the setting.

**Comment by angelo-fuchs** [comment]
Our current default is to not show any past messages (Deltachat or otherwise) and default to DC-Messages only.
It seems only some geeks (like me) want to have their regular mail in Delta Chat, the majority of users expecting DC to behave as a standalone system and not interfere with E-Mail.
Until we have a strong reason to believe that users in general want to use DC as their regular mailer we should not change that default.

I suggest we do not ask the user during setup but only if we see that there are new mails coming in that non-DC mails. Even then, the default should be not to show Non-DC Mails.

(If we show past mails and if so, how many is a different question and should be discussed in a separate issue)

**Comment by gerryfrancis** [comment]
I think it depends on where to lay the focus, however, asking the user on how Delta Chat is going to be used would be fine for me. One thing that might be quite useful to set "All" as default is that contact requests from common mail users (who obviously are the vast majority) are shown to the Delta Chat user, and replying to them is easier because their mail addresses do not have to be typed manually. (This is most helpful when using the Desktop release, because no contact list that could be accessed is available there, yet.)

**Comment by angelo-fuchs** [comment]
@gerryfrancis Importing the contact list from the Non-DC-Mails can be a very good idea (but that's a feature request and should go to the forum).
The focus of DC is the Chat Experience. Being a Mailer is a nice second goal but not the primary focus.

As we currently have no outstanding issues that users expected their classical emails to be shown, I would not change the onboarding process if it can be avoided. (medium preference, would not object to a PR)

**Comment by gerryfrancis** [comment]
@angelo-fuchs Thank you for sharing your thoughts. I did not favour an option to automatically import mail contacts, and I am with you regarding your estimate of effort to realize such a goal. Having the contact request view in Delta Chat is fine for me, as it is a messenger and not a classic mail solution. Because "All" is sufficient to receive contact requests, that could be set as default, but my use case is one out of over 1,000, I guess.

**Comment by hpk42** [comment]
@gerryfrancis FYI there is a tentative plan to read all of an e-mail accounts
messages and extract all To/CC addresses if the From was from our own account. 
This can probably be done very quickly after login succeeds. We would add those 
"known" e-mail addresses as accepted contacts. 

Together with a setup question which switches on "ALL" for
email-interaction liked discussed here on the issue this would provide a
smooth onboarding experience where one isn't lost.  Messages from those
"known" contacts would directly show up.

If you like you could open a forum issue about this plan, and ask/poll
people about open questions / defaults etc. This could then be the
basis for the eventual implementation. 

@gerryfrancis thanks btw for all your great communication/testing/triaging work!

**Comment by gerryfrancis** [comment]
@hpk42 Thank you for revealing future plans regarding this matter, I am very much looking forward to seeing this improvement in Delta Chat. And thanks a lot for your kind words and for the hard work of you all. I am very pleased and honored to be conducive to the Delta Chat project. :)

**Comment by varuzam** [comment]
It would be nice to have the feature. I want to use DC as replacement for regular email client.

**Comment by r10s** [comment]
closing this. for now, we want to do the "peeking" ui-less for now, see https://github.com/deltachat/deltachat-core-rust/pull/1925#issuecomment-696115758 for further details.
