### ISSUE TITLE
Nicer welcome activity ("About" or "Help", avoid "server")

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1530]
- I think that there should be a link "About" to delta.chat or a button "Help" to the in-app help page.
- "Log in to your server" might make users think "I do not have any server". What about "Log in to your mail account" or simply "Get started"?

**Comment by webratte** [comment]
For me as a user sounds "Log in to your mail account" like a good solution.

"Get started" is not the best solution I believe. User may not know he/she can use a existing mail account.

**Comment by Hocuri** [comment]
> "Get started" is not the best solution I believe. User may not know he/she can use a existing mail account.

At least on the next screen it says "Existing password" but yes, that's less clear.

"Log in to your mail account" is quite long, but I think that I am slightly in favor of this.

**Comment by gerryfrancis** [comment]
Why not writing "Log in to your mail account and get started"?

**Comment by r10s** [comment]
> or simply "Get started"

we had that already.

after loooooong discussions this resulted in the current wording. the "your server" was considered as an  important bit, ppl were really scared at some point but different login screens.  
afaik, this part has impoved since then, i do not know about recent complains.

as there are several rewording issues/pr the last time:

i am not saying, that we cannot reword etc, maybe "mail account" is better than "server" - maybe not. however, i would not do that without good reasons, depending on some amount of actual user issues.

however, rewording comes at costs - things have to be re-explained, help, faq, translations, there are several platforms etc.

i recently discussed that with @hpk42, in general we had the rough idea that 
- rewording should only be considered when features are actually _changed or added_ - in all other cases, it appears better (and easier!) in many cases to leave things as they are.
- in addition to that, we can collect some ideas of rewordings somewhere, and to that at some later point, then, on all platforms, including help, faq etc.

so, i suggest, to close this issue in this form.
