### ISSUE TITLE
always create a chat group for mailto: links

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1534]
currently 1-1 chats are created if a sendto:  link was clicked. The subject is the first line of the message draft. 
Using group chats would allow us to set the chat name correctly to the subject as well as allow to have multiple receipients. 
One real live example from Black Lives Matter struggles in Berlin can illustrate one use case: https://github.com/06062020BLM/mail

Clicking on "Vorlage senden!" should create a group with all receipients, the correct subject and the correct body.

**Comment by gerryfrancis** [comment]
I think this use case is served better by using a classic mail client, TBH. To found such a new chat group in Delta Chat, the members of it must be added as contacts first, one by one, afterwards they can be joined to the group. In a classic mailer like Thunderbird, you do not have to do any preparation like this, you just write and send your message to the recipients you want to address.

**Comment by cyBerta** [comment]
The adding of a contact is already done now if we're using sendto links (if the contact is unknown). We just have to iterate through all email-addresses instead of using the first one. There's no user inteaction needed, only the dialog might have a different text.

**Comment by r10s** [comment]
maybe create groups when more than once recipient is in the mailto-link or when a subject is set. 

a plain mailto: with only a single recipient should still be a 1:1 chat. wondering if if makes sense to handle all that in the core, btw. sth. as `chat_id = dc_handle_mailto(string)` or so.

**Comment by cyBerta** [comment]
> maybe create groups when more than once recipient is in the mailto-link or when a subject is set.
> a plain mailto: with only a single recipient should still be a 1:1 chat.
> 
> wondering if if makes sense to handle all that in the core, btw. sth. as `chat_id = dc_handle_mailto(string)` or so.

I agree on both of your proposals @r10s

**Comment by hpk42** [comment]
On Fri, Sep 11, 2020 at 13:09 -0700, bjoern wrote:
> maybe create groups when more than once recipient is in the mailto-link or when a subject is set. 
> 
> a plain mailto: with only a single recipient should still be a 1:1 chat. wondering if if makes sense to handle all that in the core, btw. sth. as `chat_id = dc_handle_mailto(string)` or so.

sounds good ... but guess "dc_create_chat_by_mailto()" is more consistent naming then.

**Comment by r10s** [comment]
i just had a look - in fact, we have already some code for handling `mailto:` in core.

`dc_check_qr("mailto:foo@bar.de")` will return DC_QR_ADDR. maybe we should start from there - this would also have the advantage that all this can go to a QR code.

so i suggest to:

- make `dc_check_qr()` to also check for more complicated `mailto:`-links and return them as as DC_QR_CREATE_CHAT

- after asking, the result links can be given to `dc_create_chat_from_qr()` that does all the details gracefully and returns a new `chat_id`

- i would use the "qr" wording here, leaving out the mailto-wording, even if the source is not always a physical qr-code; it fits well to `dc_set_config_from_qr()` - however, of course, the function can be used for share etc. as well (we are already doing that, eg. desktop allows copy+paste).  moreover, there might be other urls than mailto that can create chats in the future.

however, not sure how important all this is, compared with other features in the queue. at least today, my impression is that sophisticated mailto-links are not very widely used - also because, iirc, they are handled pretty badly in the past by muas.

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
