### ISSUE TITLE
Multiple devices on same email address

### ISSUE THREAD

**Issue by farvept** [deltachat/deltachat-android#159]
With encryption keys moved to second device or with encryption turned completely off on both devices, messages between the first device and second device are independent of each other on v0.9.4. A message on the first device with the same email address as the second device can not be seen on the second device and vice versa.

**Comment by gitkald** [comment]
DC syncs the imap folder every 30 minutes. (My last information). So wait a little bit.

**Comment by farvept** [comment]
The messages appear right away on my IMAP email client on both devices but does not register on the opposite device that sent the message, even after waiting overnight.

**Comment by csb0730** [comment]
See issue #148. This seems to be related to that.
I would prefer to show messages to own address for consistency. Other MUA does this.

**Comment by r10s** [comment]
is this still an issue?
eg. meanwhile messages to yourself are shown in the chat.

**Comment by csb0730** [comment]
1. It would be nice to see even the re-incoming mail back in the same chat from where it has been sent as normal email clients are doing it.
2. But on the other hand .... this issue is really softened now.

I would prefer 1. but it's only my opinion.

**Comment by testbird** [comment]
> eg. meanwhile messages to yourself are shown in the chat.

I think this issue is not about messages to oneself, but about messages sent TO a chat partner/group, however from a second device, not showing up in the corresponding chat on the first device.

The syncing part of this has been considered in https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy, by uploading "sent messages" to the chat folder (and temporarily moving to INBOX, if only that one folder can be watched by other clients).

**Comment by r10s** [comment]
i think this issue is totally covered by https://github.com/deltachat/deltachat-core/issues/52 now.
if there are additional aspects missing in https://github.com/deltachat/deltachat-core/issues/52 , we should add them there.
