### ISSUE TITLE
voice message reproduction have another sounds

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1607]
expected Behavior
when you are reproducing a voice message and in the chat arrives a message the Delta Chat beep (or maybe notification beep) doesn't reproduces

actual behavior
when you are reproducing a voice message and in the chat arrives a message the Delta Chat beep reproduces and you maybe not hear the message

**Comment by r10s** [comment]
i am not sure if i understand correctly.

the notification should is not played when you listen to a voice message?

**Comment by RubenDavidPerezJimenez** [comment]
the inverse

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez I think that this is intended. When listening to a voice message, playback should not be disturbed by/mixed with another sound, otherwise the message cannot be heard well.

**Comment by r10s** [comment]
in general, we give the notification-sound to the system - and the system plays it or not, depending on several modes and whatnot.  
we maybe can influence things here and there :)

we can continue discussing this in the forum, would also be interesting what other apps and other os are doing.

closing the issue here as there is no current actionable item.
