### ISSUE TITLE
"forward" should not go to overflow menu

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1656]
on a bit smaller screens, in group-chats, long-tapping a message may move forward to the overflow-menu, esp.

however, esp. as we use that also for "starring", i'd regard that as a major function that should be available with just one tap. "copy to clipboard", "info" and even "delete" are better candidates for the overflow-menu.

**Comment by r10s** [comment]
by the AdaptiveActionsToolbar pulled in from the signal source, this kind of stuff is hard to fix. 

i played around - things are much easier without AdaptiveActionsToolbar - esp. as i plan to have only four or five "always" icons:

- INFO, [SAVE], REPLY, FORWARD, DELETE (and COPY and REPLY_PRIVATELY in the overflow then)

afaik, even with "always", things go to the overflow menu if there is too few space.

@Hocuri do you know of any special reason why the AdaptiveActionsToolbar is needed? we are using eg. the action bar in the chatlist in the "system way" since a long time without issues - and also in the chatview before.

**Comment by Hocuri** [comment]
We need the AdaptiveActionsToolbar in order to show as many items as possible as actions (i.e. not in the overflow menu) but but them into the overflow menu if there is no more place.

> afaik, even with "always", things go to the overflow menu if there is too few space.

No, they are shoved out of the screen.

In the chatlist, we use `showAsAction="ifRoom"` which allows at most 3 icons to be shown as actions.

Anyway, I'll make a PR.

**Comment by r10s** [comment]
> We need the AdaptiveActionsToolbar in order to show as many items as possible as actions

i know - but why should we want to do that? it gets pretty confusing to learn all the icons and to differ between them. some sorting between "always", "never" etc. makes sense. i would put eg. "copy to clipboard" and "reply privately"  to the overflow-menu.

> In the chatlist, we use showAsAction="ifRoom" which allows at most 3 icons to be shown as actions.

in the old chatview, we've shown 4-5 actions without problems, just by adding "always" to the items.

and i tried that, it also works with the current ones.

i do not like the idea to have some special class just for a single action bar (as i in the pr), this might get pretty much very-specialized  code if we continue doing that for other view - also  this kind of stuff has the potential to fail on newer/older/different android versions.

**Comment by Hocuri** [comment]
> i know - but why should we want to do that?

Well, Signal and WhatsApp do it, so users are used to it. And it's a whole extra-tap that is saved. Telegram solves this by directly showing a menu with icons+text if the user short-taps on a message, which is good UX but I imagine it's pretty much effort to implement this.

> i would put eg. "copy to clipboard" and "reply privately" to the overflow-menu.

I find the "copy" icon pretty intuitive and "reply privately" always goes to the overflow menu already today.

> in the old chatview, we've shown 4-5 actions without problems, just by adding "always" to the items.

and on small screens, some items were not shown

> this might get pretty much very-specialized code if we continue doing that for other view

For what other view? I think that the chatlist is pretty unique in that we want to show more than 3 items as actions.

Anyway, it should not be too difficult to generalize the AdaptiveActionsToolbar again (estimated effort 30min) so that we can reuse it should we need it for another view.

**Comment by r10s** [comment]
> and on small screens, some items were not shown

they are also not shown with using AdaptiveActionsToolbar -  also AdaptiveActionsToolbar marks items as "never". 

however, my real point is: what is the advantage of  AdaptiveActionsToolbar compared to just setting showAsAction="always"? (and do these advantages weight out disadvantages)

**Comment by Hocuri** [comment]
> they are also not shown with using AdaptiveActionsToolbar - also AdaptiveActionsToolbar marks items as "never".

this means "never show as action, instead show in the menu". 

> however, my real point is: what is the advantage of AdaptiveActionsToolbar compared to just setting showAsAction="always"? (and do these advantages weight out disadvantages)

If we set showAsAction="always", on small screens some icons are not shown at all, also not in the overflow menu. This is really bad as there is no way to use these items then. With AdaptiveActionsToolbar, they are shown in the overflow menu on small screens.

**Comment by r10s** [comment]
> If we set showAsAction="always", on small screens some icons are not shown at all, also not in the overflow menu.

i see, that's a point.
