### ISSUE TITLE
Don't show messages very thin if small or tall images are sent

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1687]
If I send a small (few px) or tall (e.g. screenshot) image with text, then the text area is so slim that rarely two words fit beside each other. Other messengers solve this by cutting tall images at the top and bottom and showing small images bigger.

**Comment by r10s** [comment]
yip, i totally agree, this also annoys me since some time. for calculated cell-width should take higher priority on text, the image should be second priority only. i'd consider that as a bug even.

> Other messengers solve this by cutting tall images at the top and bottom

yip, this is also what i would suggest. tapping on the image will show it in full-size anyway.

>  and sending small images bigger.

not sure what you mean here. sending images should not be changed to solve this issue imho.

**Comment by Hocuri** [comment]
> > and sending small images bigger.
> 
> not sure what you mean here. sending images should not be changed to solve this issue imho.

I meant "showing" :joy: if we have a 50x50 px image, we are showing it 50x50 px -> very thin, others enlarge it

**Comment by r10s** [comment]
i seen :) yip, that makes sense +1
