### ISSUE TITLE
Archived chats return to the chat list

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1695]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.13.5 and 1.13.5 DEV
- Expected behavior: When I archive a chat must remain archived and it doesn't have to go back to the active chat list by itself.
- Actual behavior: When I have an archived chat, it unexpectedly returns to the active chat list, even if the chat has not received any read notifications or new messages.
- Steps to reproduce the problem: I have not found a way to reproduce the problem, I only know that when I open Delta Chat I find the chats in the list of active chats
- Screenshots:
- Logs:

**Comment by r10s** [comment]
> Expected behavior: When I archive a chat must remain archived and it doesn't have to go back to the active chat list by itself.

well, if a "normal" message is received, the chat will be unarchived, this is by design. but i assume this is not what you meant, i just want to clarify that bit.

but of course, it should not happen if only a read-receipt is received or under under circumstances without a normal message added.

corresponding rust issue: https://github.com/deltachat/deltachat-core-rust/issues/2054
