### ISSUE TITLE
Show voice messages as draft

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1708]
It is possible to cancel voice message, but otherwise it is sent immediately. There is no way to listen to yourself before sending.

**Comment by Hocuri** [comment]
Interestingly, neither WhatsApp nor Telegram allow this. I guess that the reason is that you don't want to push users to hear through their voice messages and make them perfect; they are rather thought as something similar to a real call.

That being said, there are obviously workarounds:
- record in "Saved messages" first
- turn of internet, record voice message, send it, listen, if you don't like it delete it, if you like it turn on internet

**Comment by link2xt** [comment]
Wire allows this.

Signal doesn't too, the only difference is that it has a "swipe up to lock recording".

> turn of internet, record voice message, send it, listen, if you don't like it delete it, if you like it turn on internet

I think I heard about this workaround from @adbenitez :)

Maybe this should have been a feature request instead.

**Comment by r10s** [comment]
> I guess that the reason is that you don't want to push users to hear through their voice messages and make them perfect; they are rather thought as something similar to a real call.

yip, i also think, this is a reason. it is a bit the walky-talky-style. hold-while-speak, done.

also, if you look how many ppl use whatsapp voicemessages, they do them very quickly, sometimes series of them etc. for this usecase, an additional staging would be annoying, making switch from whatsapp harder.

however, we can maybe combine what signal is doing together with staging somehow - if you do "swipe up to lock recording"  you need one additional tap anyway.

> Maybe this should have been a feature request instead.

yip, i also say so. this can better be discussed in the forum, at least it is nothing that needs to be targeted urgently the next time :)
