### ISSUE TITLE
linkify reserved/delimiting characters in urls?

### ISSUE THREAD

**Issue by cwerner1** [deltachat/deltachat-android#1734]
- Operating System (Linux/Mac/Windows/iOS/Android): Android - 10.1.0.243
- Delta Chat Version: 1.14.1
- Expected behavior: linking the complete URL
- Actual behavior: not linking the complete url
- Steps to reproduce the problem: 
Send the URL:
`https://www.toyota.at/new-cars/proace-verso/build?path=summary/b0fec657-68ed-4858-b470-ee998aa53d8a/de04ea4c-3bc4-4ffc-b1cf-577e3833a2a9&c=36b77af8-b387-4e32-afde-8564b149acd0&u=a5385a5d-a30a-4dfe-8f96-04d44d4b1a16&e[0]=15684&e[1]=14317&e[2]=14273&e[3]=14237&e[4]=14267&e[5]=1349&e[6]=14319&e[7]=11608&e[8]=14283&e[9]=14320&e[10]=14287&e[11]=829&e[12]=2203&financeOption=cash`

- Screenshots:
![grafik](https://user-images.githubusercontent.com/1199614/99191885-0b0aa700-2770-11eb-8fd5-8f237378af04.png)

Edit: added the Android version

**Comment by Hocuri** [comment]
I can confirm this. Funnily, Telegram has the same problem, WhatsApp does not. I just had a look in the code, there seems not to be an easy solution as this is handled by some Android library (which we can't change), seems like there is a bug in there.

Let's ping @adbenitez (our linkify expert) anyway, maybe he has a solution?

**Comment by adbenitez** [comment]
since when I am a linkify expert ;)
I guess the issue is that the buildin url regex is not accepting `[]` in the "query component" we could use a custom regex like:
`^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]`
we were using a custom regex in the pass but then that caused even more issues in other situations

**Comment by adbenitez** [comment]
actually that regex example I grabbed from http://urlregex.com/ doesn't allow `[]`
:)

**Comment by r10s** [comment]
`[` and `]` are discouraged characters in urls, they should be escaped by `%5B` and `%5D`, see https://tools.ietf.org/html/rfc3986#section-2. so, the given url is bad, iirc they come from some older shop-system, i can remember i had a similar issue 20y ago :)

also, as @Hocuri pointed out, we're just using the android-provided linkify, that seems to be correct in this sense. linkifying invalid characters may raise different issues (markdown!).

i'd say, if at some point we handle things in the core, we can think over that, but this issue is not worth to be handled here, esp. as it is discussable if this is an issue on our side.

so, i suggest to close this issue and maybe put it to Resurrection.

**Comment by cwerner1** [comment]
@Hocuri @adbenitz @r10s Thank you for investigating.

I had a closer look at the RFC3986 - especially the appendix-B https://tools.ietf.org/html/rfc3986#appendix-B  

There is an example regex for url parsing. 
for the query block parsing every character is assinged to the group "query" except the "#" character.

So thank you for the hint with linkify: I created an Issue in the android bug tracker.

**Comment by r10s** [comment]
@cwerner1 thanks for coming back - for reference, can you add a link to the created android bug tracker issue here?

**Comment by cwerner1** [comment]
Android Issue Tracker: https://issuetracker.google.com/issues/173312198

**Comment by r10s** [comment]
thanks!
