### ISSUE TITLE
The messages from one contact isn't display in app

### ISSUE THREAD

**Issue by netzoom** [deltachat/deltachat-android#174]
I use the app for a few months, everything is fine. But now I was faced with a problem that cannot solve. I sent a message to a friend who also uses the Delta Chat. It appears in the Inbox, but not immediately or half an hour or several hours is not displayed in chat. We tried to restart the app, the device. Resending also doesn't help and it's not displayed. Backwards messages to me reach perfectly and immediately. Before this incident we had a long chat. How can I further diagnose the problem? In the log there are no errors. What additional information is necessary to specify?

**Comment by testbird** [comment]
This is just a guess, that came to my mind because I saw a couple of issues with "strange" message appearances.

It could be that message filtering by other email clients, or on the server, is interfering.
I don't remember having read a basic advice about how the email chat works. Something like `eMail chat subscribes to the folder "INBOX" and "Chat"`or similar.
If emails get filtered into other folders, also "Spam", that could be one reason for them not appearing in the email chat.

**Comment by netzoom** [comment]
Thanks for the idea to check the filters. None of it affected the messages with "Chat" in the subject line. It remains in the Inbox folder. But we found a strange thing. One of the emails which I have sent previously via Thunderbird, it was marked as unread. It was in a subfolder. As soon as I opened it, Delta Chat showed a notification about ill-fated message which was not displayed. The problem is solved. It turns out that different messages in different folders and their status of reading affects the operation of the application. I hope this information will help the developer.
