### ISSUE TITLE
Device run's in DarkMode - Background and font color is black

### ISSUE THREAD

**Issue by Meldario** [deltachat/deltachat-android#1748]
- Operating System (Android): 10 (V12.0.3.0.QFDEUXM, QKQ1.190825.002 test-keys)
- Delta Chat Version: Delta Chat 1.14.5-fat
- Expected behavior: Messages should be shown normally
- Actual behavior: Background ist black, also font color is black (Smylies are shown) after a fresh install
- Steps to reproduce the problem: Device runs in DarkMode. In DeltaChat Settings (Appearance) the Theme is "Light" = Font Color and Background is black, can't read Messages. Have to change Theme to "Dark"
- Screenshots:
![DarkMode](https://user-images.githubusercontent.com/75611145/101335092-03bf5080-3879-11eb-84de-989c7c6700af.jpg)

**Comment by r10s** [comment]
thanks for reporting.

1. if that is mainly the bubble color, a quick fix might be to not use the "system-background" for bubbles but just white. then, the delta chat dark-mode can be selected independingly of the system dark mode.

2. alternatively, we could to tag our themes for light/dark in a way, the system understands it, so that the system can select the correct one see https://developer.android.com/guide/topics/ui/look-and-feel/darktheme?authuser=1. however, unfortunately, most androids out there do not support system-dark-mode at all, so that we would still need an internal switch, that would probably need three states then (default/light/dark). if the user has manually selected light/dark, we have to override the system setting, that might be tricky.

3. we could hide the in-app-option in android9, however, not sure if really all android9 systems have that switch. as this is not easy to find out, i would avoid that option for now.

so, all in all, it seems 1. seems to be the easiest thing to do. also, it is a precondition for 2., so the work would not be lost

**Comment by Meldario** [comment]
Hello,
thanks for your answer.

It's not a Problem for me, I simply selected "Dark" in Themes (but it took a few Moments to understand, what's the Problem)
It may be a Problem for Users, that want to use DeltaChat "Out of the Box". Maybe they don't understand, why they can't read anything :-)

Greetings,
Alex

**Comment by r10s** [comment]
> Maybe they don't understand, why they can't read anything :-)

yip, that needs to be fixed, no doubt :)

**Comment by r10s** [comment]
this needs a retry, i tested darkmode on some common devices, looks good so far.

however, in the screenshot atop, also the background image looks weird - maybe the system tries to shift some colors around or so...

**Comment by Meldario** [comment]
Hhmmm, my Device is a Xiaomi Mi Note 10 Pro. Maybe this helps...
Got DeltaChat via F-Droid (not Playstore).

**Comment by r10s** [comment]
afaik, there is no Xiaomi device in reach of some dev (@Hocuri ?)

but i have just created a fresh testing-apk with the fix - maybe you can test the fix on your device?

as a general precaution, if needed, i would recommend a backup first.

then, you can install the apk from http://testrun.org/deltachat-fat-debug-1.15.0-beta.apk beside your existing installation, it should not overwrite the fdroid-install (as we do not have the signing key from fdroid). after installation, there should be two delta-chat-logos on the system, the one with the "Dev" on it is the testing one. i suggest to use a different account to login, however, to check dark-mode, maybe a login is not even possible.

**Comment by Hocuri** [comment]
No, I don't have a Xiaomi device. Actually a shame, when a device makes problems, it's usually Xiaomi (maybe that's their plan - make lots of problems so that every dev has to buy a Xiaomi phone and they make lots of money :joy:)

**Comment by r10s** [comment]
> Actually a shame, when a device makes problems, it's usually Xiaomi

i think we should get one.

**Comment by Meldario** [comment]
Starting DeltaChat-Dev Out-of-the-Box -> Theme is "System default" and everything looks great! :-)
When I change the Theme to "Light" -> Black background and black font so can't read anything
Theme "Dark" -> Everything OK, like "System default"
So, it may be a good Workaround for the next official release to start with "Sytem default"
Great Job @ Dev-Team!!!

**Comment by r10s** [comment]
> Starting DeltaChat-Dev Out-of-the-Box -> Theme is "System default" and everything looks great! :-)

great! thanks for reporting!

> When I change the Theme to "Light" -> Black background and black font so can't read anything

as @Hocuri pointed out, at https://github.com/deltachat/deltachat-android/pull/1758, that might also be an issue with the concrete system, mixing some colors for ForceDark mode, might be that some systems force that independently of app preferences. 

however, as this is no longer the default, and as this seems not to be a general issue, i think we can close this ticket. also, as there is no actionable item left.
