### ISSUE TITLE
setConfigFromQr error is not displayed

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1762]
Scanning invalid `DCACCOUNT` code, such as `DCACCOUNT:http://example.org/`, results in error dialog "Configuration failed. Error: Please enter an email address".

When running `setqr DCACCOUNT:http://example.org/`, there is an error `Cannot set config from QR code: Cannot create account, request to http://example.org/ failed`. It should be displayed in Android UI, but it isn't.

Attached QR code for testing:
![1](https://user-images.githubusercontent.com/18373967/103284464-56a9a500-49ec-11eb-9e71-68edb0bf98be.png)

Relevant line is https://github.com/deltachat/deltachat-android/blob/971c7e1d68129b235221d9d8c86c5cd724a1726a/src/org/thoughtcrime/securesms/WelcomeActivity.java#L166

One bug is that `dcContext.configure()` is called regardless of whether `setQrConfigFromQr` succeeds or not. The other one is that error is not displayed.

**Comment by adbenitez** [comment]
@link2xt the issue is that `dcContext.setConfigFromQr(qrCode)` is returning that it failed, but at that time the error event have not been processed yet by `ApplicationDcContext.handleEvent()` (where the `lastErrorString` is saved) so `dcContext.getCapturedError()` returns empty string, adding an additional call to `dcContext.getCapturedError()` just afterwards I got the error string, it is just a race condition, 

if  `dcContext.setConfigFromQr(qrCode)` returns `false` there was an error, maybe it makes sense to wait for `dcContext.getCapturedError()` (`lastErrorString`) to have a value or so

**Comment by link2xt** [comment]
Or maybe get rid of error capturing once https://github.com/deltachat/deltachat-core-rust/pull/2319 is merged and get back to simply displaying toasts on error events. As I understand this error capturing was created because of annoying network errors which should not be emitted anymore.

**Comment by r10s** [comment]
>  As I understand this error capturing was created because of annoying network errors which should not be emitted anymore.

no, the capturing was created to show _concrete_ alert-dialogs after some actions, as configure, import, scan account etc.  toasts are not-so-great for that and, due to unclear dialog/acticvity-context you cannot easily get "real" dialogs on events.

these toasts were meant for "unrelated", "async" and _short_ errors as just "No network." showing once the network is lost. this broke at some point, resulting in several toast issues, indeed :) meanwhile, these "No network"  errors are replaced by the connectivity view, so maybe we can fade out the usage of toast for errors at all.

on ios, we do not show error toasts, and they are not missing imho. 

anyway, this issue is fixded by #2106, as @adbenitez pointed out (thanks for that!).

**Comment by r10s** [comment]
meanwhile the error from core is displayed, that shows the error from the server - in case of the example above, including some html-tags - but this is probably a server issue, not sure if that is real on real account servers.
