### ISSUE TITLE
Smaller font in toolbar (on top) after starting app in landscape view

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1798]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-02-05).

- Delta Chat Version:
1.15.0-beta.

- Expected behavior:
When the app is started in landscape view, height and font size used in the toolbar are the same as in portrait view.

- Actual behavior:
When the app is started in landscape view, height and font size used in the toolbar are smaller than usual.

- Steps to reproduce the problem:
-- Rotate the launcher view from portrait to landscape.
-- Start Delta Chat (from the launcher).

- Screenshots:
-- Expected:
![grafik](https://user-images.githubusercontent.com/51095533/107424001-6523ca00-6b1d-11eb-8152-2519b615b819.png)
-- Actual:
![grafik](https://user-images.githubusercontent.com/51095533/107422527-7075f600-6b1b-11eb-996f-655b9fd42021.png)

- Logs:
N/A.

**Comment by r10s** [comment]
interesting!

**Comment by Hocuri** [comment]
This is the expected behavior, other apps also show it (e.g. Flym and SuperFreezZ). The idea is that the bar should take away less space when the screen height is low (btw it also happens when you use the "split screen" feature).

What _is_ a small bug, is that the size of the title bar should dynamically change when the screen rotates. The problem here is: as we set 
`android:configChanges="...orientation..."`
in AndroidManifest.xml:107 (and also for many other activities), the activity is not recreated when the screen rotates and the size of the title bar stays the same.

In [the documentation](https://developer.android.com/guide/topics/resources/runtime-changes), Google writes that we should either:
- remove `orientation` from `configChanges`; this will lead to a short lag when rotating the screen and may introduce new UX issues, like that the list scrolls to the top as soon as the screen is rotated (I had this when developing SuperFreezZ)
- Handle the config change ourselves, somehow invalidating the title bar `onConfigChanged`, no idea how to do this

Personally I think that it's fine to leave things as they are.

**Comment by r10s** [comment]
thanks for insight. so, yes, with the split-screen that makes sense, i forgot about that. not sure if it is worth to target that, at least, i'd say it has pretty low priority ;)

**Comment by gerryfrancis** [comment]
@r10s and @Hocuri , thanks for your detailed explanations. :)

> What is a small bug, is that the size of the title bar should dynamically change when the screen rotates.

@Hocuri Do you mean that font and height do not change to the smaller when the bar is rotated from portrait to landscape?

**Comment by Hocuri** [comment]
> @Hocuri Do you mean that font and height do not change to the smaller when the bar is rotated from portrait to landscape?

Yes.

**Comment by gerryfrancis** [comment]
I have just experienced the bug in portrait view, without any rotating before at all:

![grafik](https://user-images.githubusercontent.com/51095533/107934012-cb767580-6f7f-11eb-87e7-c8939b41cd45.png)

I started the app after I "killed" it in the Android app settings.

**Comment by adbenitez** [comment]
this only happens in the chat list, inside the chat the font size keeps the same, also with the new self-avatar icon etc. the smaller font doesn't seems to safe any space

**Comment by gerryfrancis** [comment]
Works like a charm in the latest nightly build, thank you for fixing! :)
