### ISSUE TITLE
Allow deleting whole chats from the email server

### ISSUE THREAD

**Issue by miguel3014** [deltachat/deltachat-android#183]
I noticed, that when I delete a conversation the messages remain on the mail server, it would be nice if they could be removed from the server as well

**Comment by r10s** [comment]
Thank you for your report. We are conservative when deleting messages as also normal mails may be shown in a chat - that may not be expected to be deleted when a chat gets deleted.

See also https://github.com/deltachat/deltachat-android/issues/169

So, I think it is a good idea only to delete messages _manually_ selected by the user. But maybe a simple "Select all messages" will help on this issue and keeps things clear.

**Comment by r10s** [comment]
also related to https://github.com/deltachat/deltachat-android/issues/80

**Comment by zoff99** [comment]
again, why not make an option for that?

**Comment by r10s** [comment]
Because IMHO it is not clear to the user what gets deleted if we ask

Delete Chat? 
[ ] This will also delete all messages from the server

"All messages" may be interpreted as only chat messages send/received by Delta Chat or as all messages displayed in a chat - these two option may be different.

So, we should use a precise formulation or just an option to select all messages - an option to delete all selected messages is already available. I personally would prefer this approach as the user really _sees_ what will be deleted and has selected the messages to delete manually before.

**Comment by zoff99** [comment]
make it an "expert option" in the settings then. normal users wont ever look there

**Comment by r10s** [comment]
Yes, maybe this is the best solution.

**Comment by decripter37** [comment]
Bump on this, maybe a POP option as well? If I use Deltachat I don't want to keep my msg on the server especially with a low space mail server.

**Comment by r10s** [comment]
@decripter37 thank you for your post.

regarding POP: if you think this is worth being a feature, please open a separate issue for this. i fear it gots lost here otherwise...

**Comment by r10s** [comment]
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.
