### ISSUE TITLE
Disable location service when it is not used anymore

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1908]
Google Play review: "Great idea and glance app, but please solve follow problem: location service staying on even after make off streaming location"

**Comment by Gh0stz0x** [comment]
🤔 I have to try to test it.

**Comment by r10s** [comment]
there is a similar issue on ios https://github.com/deltachat/deltachat-ios/issues/1137

**Comment by adbenitez** [comment]
one issue is that `stopLocationEngine()` is not unbinding the service hence the GPS is kept in use (called when user manually cancel location sharing) and another issue is that when the timer expires, no action is done at all, that event is not watched to stop the GPS service when all location streaming timers expire.

**Comment by adbenitez** [comment]
> another issue is that when the timer expires, no action is done at all, that event is not watched to stop the GPS service when all location streaming timers expire.

it turns out there are no such "location streaming ended" event? anyway it turned out that the service was stopped using a check when the we get the next location, it is checked if location streaming is enabled and at that time then it is canceled if it is no longer enabled, so the service is not immediately stopped but some seconds after that and it is not that bad for now.

**Comment by r10s** [comment]
> it turns out there are no such "location streaming ended" event?

no, there is no such event. the idea was that you continuously feed locations to the core using [`dc_set_location()`](https://c.delta.chat/classdc__context__t.html#a8b8e410c7bfad022443ecb4feba85089) - and that function returns false when no more chats want any location. at that point, the UI can stop requesting GPS coordinates from the UI.
