### ISSUE TITLE
No first letter displayed for own sent messages in search view

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1916]
- Android version:
Android 10.

- Device:
Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-04-30).

- Delta Chat version:
1.19.2 (latest nightly build).

- Expected behavior:
First letter of own name is displayed for own sent messages in search view.

- Actual behavior:
First letter of own name is not displayed for own sent messages in search view.

- Steps to reproduce the problem:
-- Search for messages sent from yourself.

- Screenshots:
![Screenshot_20210504-164516_Delta_Chat_2](https://user-images.githubusercontent.com/51095533/117024973-c7dec900-acfa-11eb-8116-5c345b1412a3.png)

- Logs:
N/A.

**Comment by Hocuri** [comment]
On my device, the own avatar is displayed, but if there is none, an "M" is displayed instead of the first letter of the name.

**Comment by gerryfrancis** [comment]
@Hocuri Why not "G" for "Gerry"? ;)

**Comment by adbenitez** [comment]
@gerryfrancis the issue description is wrong, for self avatar it works, in your case you don't have an avatar set, and you are expecting to see your nick's first letter but the issue is that you appear as "Me" not as "Gerry" to yourself, so to show a "G" as avatar the display name should be "Gerry" instead of "Me", but "Me" is better to realize the messages are from yourself, 

so since the real issue here would be that avatar is not displayed, which is not the case, that works, then what is left is a feature request about showing your name instead of "Me" and that should go to the forum: support.delta.chat :)

**Comment by gerryfrancis** [comment]
@adbenitez Thanks for your detailed statement. Although your assessment is correct, it seems highly illogical to me that this should be a feature request. Nobody looks for an "M" (or an "I" for "Ich" in German) as the own avatar letter. Maybe another dev could chime in and explain another (different) view on this issue, thanks in advance!

**Comment by gerryfrancis** [comment]
I am reopening this issue after reviewing and adjusting title and description.

**Comment by adbenitez** [comment]
@gerryfrancis it is a feature proposal because it is not a bug, it is also relative the "feature" part because it sounds logical for you but controversial for me, and probably the dev that did it in first place and decided to use "me" instead of your current name, it is more weird that it says "me" but displays a "G" as avatar, 

so since this is a thing of "personal taste" and not a bug, and this issue tracker is meant for bugs, I recommend to close here and move to the forum where you can get feedback of other users, here will just hang around and be in the way of devs trying to solve real issues

**Comment by adbenitez** [comment]
also this is not an android specific issue, it would need to be changed in all UIs so if any, the right place for this would be in the interface repo https://github.com/deltachat/interface, maybe?

**Comment by gerryfrancis** [comment]
> devs trying to solve real issues

@adbenitez This is a real issue to me, indeed. An avatar letter should be treated as an identification symbol, too. Showing "M" (for "Me") is not unique, and for now I do not like to use an image instead. But of course you are right, it _might_ be my "personal taste", and the rest of Delta Chat users might be fine with the current implementation. As you are one of the lead developers here and not satisfied to deal with my issue, I will close that one...

**Comment by adbenitez** [comment]
@gerryfrancis I am not "lead developer" :) but I understand that to you this might sounds important, there are **a lot** of stuff that might be vital and very important to a variety of users, some might not use the app because the lack of an easy way to call, lack of stickers, lack of "online status", etc. that doesn't mean all that stuff is not important or valued for a fraction of the user base, but **they are not bugs**

so please, open a feature request in forum and if it turns it is the killer feature and a lot of users like the idea, maybe some developer feels more motivated to add it ;)
