### ISSUE TITLE
add connectedness preferences 

### ISSUE THREAD

**Issue by travisfw** [deltachat/deltachat-android#200]
I'd like to avoid the persistent notification. If DC would give me the alternative to have it check, perhaps, every 20 minutes instead of staying connected constantly, that would be great. Of course, while DC is active I'd want that constant connection, just not in the background.

**Comment by csb0730** [comment]
Would like that too :-)

Additionally this is in relation to #104 !

**Comment by zoff99** [comment]
i been asking for this for 1 year now. developer does not like to do it :-(

**Comment by csb0730** [comment]
4 months ;-)

But joking aside: I think there are most of basic concepts existing to have a connectionless operation of DC. This would not mean to change to POP3, more to disable the foreground service and give the user a button to launch a "fetch_from_all_folders" like it is done now anyway.

But I think r10s's focus is more to fix basic bugs in the moment than doing that here. In spite of the fact that this issue here would really be a very low hanging fruit ?!

I fully understand r10s because I've some childreen too an I know how hard it is sometimes to get some time free to assist here!

**Comment by Ampli-fier** [comment]
Currently, first priority is to resolve all issues from the [Android Milestone list](https://github.com/deltachat/deltachat-android/milestone/1) and from the [Core Milestone list](https://github.com/deltachat/deltachat-core/milestone/1).

**Comment by r10s** [comment]
this idea is continued in the consolidated issue #269 ; this one is closed therefore.

regarding the large timespans: we appreciate and welcome all pr :)
