### ISSUE TITLE
verified groups, protected groups, recent thoughts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2099]
[since one year or so](https://github.com/orgs/deltachat/projects/28), we are thinking about transforming the currently existing _verified groups_ into so called _protected chats_.

while core is prepared since then, we hesitated for various reasons to do the shift in the UIs.

one of the reasons is that there was no consent that it is _really_ a good idea to give up the _thing_ of a verified group in favor to an _option_ which may have races, needs more explanations etc., see all the discussions at https://github.com/deltachat/deltachat-core-rust/pull/1968 esp. the thoughts of @flub and @link2xt. many discussions were also offline, however.

one year later, at the recent octobb33-meeting with @Hocuri, @hpk42, @okdistribute, @cyBerta, @Simon-Laux, @Jikstra, @dignifiedquire, Eileen and others re-thought things several times - at the end, **the consent was that the currently _verified groups_ are not the worse and could just be kept**, esp. that it is good to have a dedicated chat type that cannot be modified, which is also better to explain ux-wise - a switch is easily more something needed to fix things.

also, since then, the verified groups as is are _in use_ for a year or so ;)

but we figured out existing annoyances and how that could be improved:

1. we do not want to have a "Create Group" vs. "Create Verified Group" just in the first place. new users do know the differences and/or do not care.  
solutions may be to use only a "Create Group" - and if all added members are verified, ask the user if they want to create a "Verified Group". thinking that over today, the dialog needs to be appear also when "QR Invite Code" is tapped - as also then, users may not really know, maybe a simple checkbox is an alternative.

2. we do not have verified one-to-one chats, introducing them would create another chat type which most agreed on that this is not-so-nice, for $reasons. however, since forever, you could create a verified group with only two members.  
the idea is to make it easier to create a (verified) group with another members and add a dedicated option to the contact's profile - and it turned out that this is also very useful for the email-subject-discussion.  
(there was also the idea to show the user's profile instead of the chat on a qr-code-scan, from there, the user can decide what do do. meanwhile, the idea may not be _that_ great as the as the handshake runs in background and the profile would have very limited options at the first place, esp. "Create verified group" would not work. that in mind, showing just the chat as it is now seems to be better - and it is also in-sync with what we are doing on [group-join now](https://github.com/deltachat/deltachat-core-rust/pull/2508))

there were several other ideas and discussions, i am sure i forgot several things :) feel free to add and to chime in :)

**Comment by adbenitez** [comment]
I was not present in this discussions ;P so here is MHO:

- I like more the naming "protected chats" instead of "verified chats" because that is confusing with 1:1 chats with verified contacts
- I agree with the issues mentioned about weakening verified chats and sync issues, but that can be solved if we make them opt-in-only so if you protect a normal chat it can't be reversed it will be converted to what we call today "verified chat", we don't need to disable it again, to disable it we just create a new group with all members, that can be made easily with @link2xt's requested "clone group" option, so you will have both protection and a way to "switch off" creating a new group if something goes wrong (someone lost their key etc)
- absolutely agree with deleting the separated entry "Create Verified Group"

about protected 1:1 chats:
- the chat should be protected automatically when the contact is verified
- if peer changes key, the chat should be manually downgraded to unprotected by the user and it is a local change can't be unprotected for your peer. The UI could show an snack bar at the bottom of the chat saying that user is not verified anymore and you can't send messages until it is verified again or you press a button to remove chat protection.

**Comment by r10s** [comment]
this is superseded by the upcoming "verified 1:1 chats", no actionable item left in this issue, closing
