### ISSUE TITLE
use `get_last_error()` and remove capture hack with potential races

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2108]
- requires master with https://github.com/deltachat/deltachat-core-rust/pull/2788

- hacks as https://github.com/deltachat/deltachat-android/pull/2106 can be removed then

**Comment by Hocuri** [comment]
My thoughts, without being deep into this matter:

Be aware that (IIRC) capturing did two things: It also prevented errors from being shown as a toast. OTOH I think that at some point someone disabled `error!` errors being shown as a toast because this was too noisy, although it would be nice to at some point agree on what `error!` means and whether the UI should show them. And possibly introduce `toast_error!` or something, but all of this doesn't have to be now.

Anyway, one other (possibly nicer) solution would be to let account scanning return the error similarly to configure.

**Comment by r10s** [comment]
> It also prevented errors from being shown as a toast.

i do not want to remove enabing/disabling toasts directly, the issue is only about replacing getCapturedError() by dc_get_last_error() to prevent races. sorry when being unclear.

for removing toasts: yip, we can think over that, that also removes the bit weird situation that we log many core errors using `warn!` as they should not pop up as a toast and shown differently to the user.
