### ISSUE TITLE
Scrolling in ConversationActivity feels laggy

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-android#2177]
- Android version: 11
- Device: Mi 10T Lite
- Delta Chat version: 1.26.2
- Expected behavior: Chat view should have high refresh rate
- Actual behavior: Chat view is laggy, feels like being capped 60Hz
- Steps to reproduce the problem: 
	- Turn up the refresh rate to 90 or 120Hz in your phone settings
	- Open Delta Chat, click on any contact to open the chat view
	- Scroll down and up, you'll notice it's not smooth
- Screenshots: Not applicable 
- Logs: Not applicable

Delta Chat had proper high refresh rate on basically **everywhere**, EXCEPT chat view. Settings, contact list and even gallery/docs view in contact view, they all have high refresh rate.

**Comment by Hocuri** [comment]
Yup, scrolling in our chat view (the technical term is ConversationActivity) is pretty slow. This has nothing to do with the refresh rate, it's just a

**Comment by r10s** [comment]
we improved some things since this issue was filed, eg. https://github.com/deltachat/deltachat-core-rust/pull/3174, https://github.com/deltachat/deltachat-core-rust/pull/3175 (included in https://github.com/deltachat/deltachat-core-rust/pull/3194), https://github.com/deltachat/deltachat-android/pull/1987, and tried out other as https://github.com/deltachat/deltachat-android/pull/2254

also devices has changed a lot, so i am closing this stale issue which as no concrete actionable item.
