### ISSUE TITLE
Need to get the messages in plain text archive

### ISSUE THREAD

**Issue by LordVladneutral** [deltachat/deltachat-android#221]
I would like to get my conversations neatly copied and pasted in a file that I can do whatever with. But to do that I need to manually copy paste it all, and it doesn't have a time stamp.

Thank you to consider adding this.

**Comment by r10s** [comment]
do you imagine this working in the same way as for saving images to the gallery?

however, instead of implementing this in Delta Chat - have you considered doing this with another MUA? Could be possible even with a shell script or sth. like that. One of the advantages of Delta Chat is its interoperability :)

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
