### ISSUE TITLE
Selecting message shortly reveals total time of currently playing voice message

### ISSUE THREAD

**Issue by dotlambda** [deltachat/deltachat-android#2261]
- Android version: 12 (GrapheneOS)
- Device: Pixel 4a
- Delta Chat version: 1.28.3
- Expected behavior: Elapsed time is shown when a voice message is being played.
- Actual behavior: If another message is selected through a long touch while a voice message is playing, the total time of the audio is revealed for a short moment.
- [Screenshot](https://user-images.githubusercontent.com/6806011/161654292-8a9aa502-d425-4c86-998d-1fb4b45078f0.mp4)

**Comment by adbenitez** [comment]
for incoming messages it is for a short time since the audio is playing it changes to the current playing time, but for outgoing voice messages, it stays forever in the total time, it seems this issue is related in a way to https://github.com/deltachat/deltachat-android/issues/1288

lets close here and collect the information there
