### ISSUE TITLE
wrong audio channel used

### ISSUE THREAD

**Issue by kugelfee** [deltachat/deltachat-android#2320]
notifications uses media/main audio channel instead of notification channel.

problem: notification sound is always hearable in global vibration and mute mode.

**Comment by gerryfrancis** [comment]
I cannot confirm the issue on my device (Fairphone FP2 running LineageOS 18.1). However, please fill in the template (current OS version, current Delta Chat version, and the steps to reproduce the issue).

FYI, there are ways to exclude certain apps from Do-Not-Disturb mode so that they are able to play notification sounds. Please check your Android settings if this could be true for your case, thank you.

**Comment by gerryfrancis** [comment]
Closing here due to lack of feedback. Feel free to request a reopening if necessary.
