### ISSUE TITLE
status/navigation bar color

### ISSUE THREAD

**Issue by andsofine** [deltachat/deltachat-android#2326]
change the color of the status bar to the color of the toolbar in the light/dark theme

change the color of the navigation bar to white in a light theme

**Comment by r10s** [comment]
not sure what you mean here. maybe you can add some screenshot with details?

i have the feeling, the dark/light mode is fine so far - of course things can be done differently, however, i do not see bugs here (the issue tracker is about bugs).

closing this issue therefore, we can reopen if it turns out there is actually a bug.

**Comment by r10s** [comment]
thanks a lot for the screenshots and thanks for coming back, things are much clearer now :)

to me the right one looks not so good - and in some android versions i would consider this even a bug.

status bar is usually a bit different from title bar - are some android guidelines changed on that recently?

however, feel free to create a feature request or a discussion on that in the forum at https://support.delta.chat.
