### ISSUE TITLE
Remove compile time dependency on GMS

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2361]
Follow-up to #2349, runtime dependency and non-free components are removed, but GMS is still downloaded during the build.

See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11527#note_1053804549

A quick solution to get DeltaChat to F-Droid is to use a patched version of mapbox-events-android, like here:
https://github.com/johan12345/EVMap/commit/ed80d7b968826701d59b6590dfba7cf5a9611d74
Patched version is at https://github.com/johan12345/mapbox-events-android

Proper solution is to upstream fixes to MapLibre and introduce a free build flavour, suggested at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11527#note_1053885392

**Comment by licaon-kter** [comment]
maplibre 10 is out for a while now, plans to update?

**Comment by adbenitez** [comment]
since MapLibre 10 breaks support for Android 4 and it seems they can't bring it back lower than API level 18 anyway because their needs, so this issue can be closed also because meanwhile the issue is solved by fdroid somehow,  any advancements in this area will be with the complete removal of MapLibre, not upgrading it, the path to follow will probably be similar to what DC iOS is planning: [https://github.com/deltachat/deltachat-ios/pull/1912](https://github.com/deltachat/deltachat-android/issues/2361#)
