### ISSUE TITLE
Can't log into Yahoo

### ISSUE THREAD

**Issue by anaskaejdar** [deltachat/deltachat-android#2399]
- Android version: 12
- Device: Samsung Galaxy S20
- Delta Chat version: 1.34.1
- Expected behavior: Log into account, either via OAuth2 or with an app password.
- Actual behavior: When entering a yahoo email address, delta says that I must generate an app password, but yahoo's app password generation has been broken for several months, so unfortunately, it's not feasible. Yahoo, however, has an OAuth2 web-based login like Gmail does. It seems DeltaChat cannot invoke that right now, however.
- Steps to reproduce the problem:
  - Try to generate an app password on Yahoo.
  - Since that doesn't work, try logging with normal password
  - Since that doesn't work, try to somehow invoke the OAuth2 web login
  - If it worked, please tell me how you did it.
- Screenshots: none
- Logs: none

There is another interesting case that I want to lump into this one. I have a gmail account that belongs to a different domain, so it _doesn't_ end in `@gmail.com`. DeltaChat doesn't recognize this as a gmail account, so I can't invoke the OAuth2 web login. I _can_, however, put in a fakeaddress@gmail.com to bring up the web login and then log into this account, but then it fails when focus comes back from the web to DeltaChat, because DeltaChat tries to construct the imap/smtp addresses from the custom domain (for example, imap.customdomain.edu) instead of using imap.gmail.com ... Ultimately, I made it work by generating an app password, but there _should_ be a way to make OAuth2 work.

**Comment by Gh0stz0x** [comment]
@maemunman I tried yahoo too.
Unfortunately it is yahoo that does not generate the password. 
As for gmail with different domains (for example .edu ones) I didn't have any problems.
I try to run the setup again and then I'll explain how to do it.

**Comment by Gh0stz0x** [comment]
I tried with a domain.edu and it immediately recognized me that it was google 🤔
Try in the login parameters screen to click advanced -> Authorization Method -> OAuth2

**Comment by maemunman** [comment]
@Gh0stz0x I don't know what to say. My experience is entirely different. I put my @xxx.edu address in the top, open the advanced settings and set it to OAuth2 explicitly, and then I get this:
![Screenshot_۲۰۲۲۱۰۲۱-۰۰۳۴۰۴_Delta Chat](https://user-images.githubusercontent.com/32847759/197139721-f21794b5-b171-486d-a9da-16834bb48da4.jpg)
![Screenshot_۲۰۲۲۱۰۲۱-۰۰۳۴۱۸_Delta Chat](https://user-images.githubusercontent.com/32847759/197139726-6a1d797d-d194-40fc-b172-dbb23cde8284.jpg)

The error is in persian, so I translate:
>Please enter a valid email and password

Sounds like it's expecting a password, because despite explicitly setting it, it isn't actually trying to use OAuth2. Somehow I think the setting is being ignored.

**Comment by maemunman** [comment]
I have good news on the Yahoo front. It looks like the function to generate an app password works once again. I don't know whether this will last, but I was able to log in to this account at long last.

**Comment by adbenitez** [comment]
great! closing this issue then
