### ISSUE TITLE
Allow minimize permanent notification 

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#2421]
K9 mail also use a permanent notification for "reilable background connection". But they allow to minimize it and it will not visible.

https://forum.k9mail.app/t/how-to-configure-push/1102

I have no idea how they do that. But maybe you can do a look into the source code of k9?

![Screenshot_20221112-130037~2.png](https://user-images.githubusercontent.com/6864851/201473107-f6a8bc0a-7161-4edc-b4ad-8cd71053c1a3.png)

**Comment by r10s** [comment]
did you try that the same approach does not work with Delta Chat already today?

afaik, this is a system-thingie - so of that works on some OS with K-9, it should also work on the same OS with Delta Chat.

**Comment by webratte** [comment]
Yes, I tried it. And it it doesn't work with DC.

See also the screenshot of the k9 notification setting. This opens if I tap of the permanent notification.

For Delta Chat I didn't find this setting. If I tap the permanent notification I will redirect to the chat list. So it seems the k9 devs do something that I will redirect to this setting.

![Screenshot_20221112-134442~2.png](https://user-images.githubusercontent.com/6864851/201474660-19a0fdbe-67db-493d-b4a7-2b7173708aa4.png)

**Comment by webratte** [comment]
I have searched and played around with different notification settings (OS sided).
I can't find anything which hide the permanent notification for Delta Chat.

**Comment by r10s** [comment]
> I have searched and played around with different notification settings (OS sided).
> I can't find anything which hide the permanent notification for Delta Chat.

to be sure: but you could hide the permanent notification for K-9 on the same OS and same Device?

**Comment by webratte** [comment]
Yes absolutely. The same device and in this case also the same OS 😉
Also tested with the current nightly of DC.

**Comment by r10s** [comment]
thanks for clarification and double checking, +1

**Comment by adbenitez** [comment]
why is needed the "minimize" option? In my system I just tried and I see the "minimize" option for Delta Chat permanent notification but the description says "in the pull-down shade, collapse notifications to one line" that is not what you want I guess, since this is a single notification, so there will never be a bunch of notification to minimize/collapse, I guess you want to hide it, in that case you should go to your system settings for Delta Chat notifications, there will be a category "Generic Background Service" just disable the switch to hide it

otherwise please provide screenshot of the system page for Delta Chat notifications to see what is available and be able to help you, but this is a system stuff

**Comment by adbenitez** [comment]
closing this until more information is provided and we have more concrete idea what we can do
