### ISSUE TITLE
Remove Block/Accept for already known user

### ISSUE THREAD

**Issue by foxtrotchat** [deltachat/deltachat-android#2449]
it just does not make any sense when the both user already talked each other.

1. A-->B talk
2. after talk, A/B delete the conversation (right top menu)
3. after some days, B-->A talk

----

Current result

A will see B's message with "block accept" bar below

----

Expected

A will see B message and normal chat bar

**Comment by gerryfrancis** [comment]
@foxtrotchat Welcome, and thank you for your report! From my point of view it _does_ make sense to reask a user whether a previously deleted contact shall be accepted again or not, because it might be a cruel person I never want to chat with again.

But you can share your thoughts on this and many other topics in the Delta Chat Community Forum, of course! https://support.delta.chat

Thanks for contributing, I am closing here!
