### ISSUE TITLE
Move "backup" from "Chats and media" to "advanced"

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2478]
Most users click "Advanced" first when they search for backup (in ux tests in workshops too, not just me).

**Comment by r10s** [comment]
interesting. i intuitively always search "at the end" or "in the last real item beside help or version or so" - and that is often "advanced" then.

**Comment by r10s** [comment]
in fact, it already was at "advanced" in the past, cmp https://github.com/deltachat/deltachat-android/issues/957 - although i filed the issue that time, the change was also not driven by me but by some findings and reports - so, tbh, one say so and one say so :)

unless we have very concrete findings this time and really know that it is *much* better, i am sceptical if moving things around is worth the effort, esp as they are already consistent to other delta chat apps as well as to external apps

**Comment by adbenitez** [comment]
with the new "add second device" screen, I think this is a place where backups should also go, since is the place you look when you want to move to another device

there is the argument that backup is not only to move to a new device, but notice that backups are currently not even encrypted and we shouldn't be recommending backups to store in some place but as a way to only temporarily use it to transfer account, and only if the QR transfer is not a solution

which is why I think it should go in this screen as an alternative, because the QR transfer is experimental to start with, and assuming it will just work nicely for everyone is being too naive, people might not even have a wifi to connect to or the devices might not find each other etc. also when transfering from mobile to PC, the PC might not have camera to scan the QR, etc. and it is good to have the old good known offline transfer

**Comment by r10s** [comment]
> notice that backups are currently not even encrypted and we shouldn't be recommending backups to store in some place but as a way to only temporarily use it to transfer account, and only if the QR transfer is not a solution

why not? most of my documents, images and whatnot are not encrypted - and i still do a backup of them from time to time to a harddisk that i leave at some place. i do not think, this is insecure, maybe an advanced usage - but then, "Advaned" seems to be a good place.  i would not search for that at "Add Second Account".

i agree, however, that it may be good to have an "alternative, manual way" also for "add second device" - but then, let's first see how "experiment" things are really in practise and what is needed. maybe we can make the qr-thingie really work in most cases? also iroh is planned to improve and limitations will probably vanish.

already today, it is planned to explain the  "alternative, manual way" in the "troubleshooting" section (that is [needed to be written](https://github.com/deltachat/deltachat-pages/issues/628), however) - let's see, maybe this is good enough already.

when trying to transfer a backup from android to eg. ios, the place of the button is the smallest issue you'll have :)

**Comment by AndreaLattmann** [comment]
@Raiden1982 Good idea!

**Comment by adbenitez** [comment]
closing stale discussion, meanwhile we have the device transfer option which is more recommendable than backups, and moving backups from one side to another is more like nitpicking, more interesting would be a way to backup all accounts at the same time since it is quite the pain to select and export one by one
