### ISSUE TITLE
webxdc: pressing "back" button closes the app instead of navigating within it

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-android#2530]
- Android version:
- Device:
- Delta Chat version: 1.34.13
- Expected behavior: I navigate back inside the app
- Actual behavior: The app gets closed
- Steps to reproduce the problem:
  1. Open a webxdc app that has navigation (like [this one](https://github.com/WofWca/vikunja-frontend/releases/download/webxdc-0.2.1/vikunja.xdc)).
  2. Navigate somewhere inside the app (follow a relative, in-app link) (in the case of the linked app, go to settings).
  3. Press your phone's "back" button
- Screenshots:
- Logs:

I think this may have to do with the fact that the app is opened inside the iframe.

It's probably the same for iOS, but I didn't test.

Related: https://support.delta.chat/t/webxdc-desktop-navigation-buttons-back-forward/2506?u=wofwca

**Comment by r10s** [comment]
> It's probably the same for iOS, but I didn't test.

no. 

neither ios nor desktop have "back buttons" comparable to android.

this issue was discussed before, and it was decided, that navigation inside the apps should work without relying on back button for now. so, eg. using dialogs, close upper right, buttons tabs, etc. at best, nothing that can be mixed with "back".

this is not always possible and sometimes hard, however, for small apps, this is usually doable.

pwa have similar issues, with similar approaches, at least partly, eg. https://dockyard.com/blog/2017/11/09/designing-for-pwas-without-the-back-button

we may think over that, at some point, sure. however, vikunja as a multi-feature-app is also not the best example, as we tend to avoid  multi-feature-app for webxdc for now.

closing this issue here now as there is no clear actionable item for android. just adding "back" on android would raise new issues. this has to be discussed on a broader level first. timing wise, when the other pending webxdc questions are solved.

in between, we could add a hint to the docs.
