### ISSUE TITLE
register as handler for `.xdc` file type

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#2532]
register for .xdc file extension then ask to which chat to attach as draft. Like that the file manager asks to open the file with deltachat and deltachat then asks the user where to send it to.

I recently showed someone deltachat and webxdc on android and I though this was already implemented, but seems like it is not.

desktop: https://github.com/deltachat/deltachat-desktop/issues/2886
iOS: https://github.com/deltachat/deltachat-ios/issues/1733

**Comment by r10s** [comment]
what works already today is to use "Share" the file in the file manager "to Delta Chat".

sure, a simple tap is a nice enhancement. might be easy to add as the functionality seems already there, cmp. https://stackoverflow.com/questions/4799576/register-a-new-file-type-in-android/55976817#55976817

**Comment by monperrus** [comment]
I confirm that one can open xdc files with 'share with' - 'saved messages'. register an handler would be great though!

**Comment by adbenitez** [comment]
opening files by extension doesn't work that fine in Android, I tried this already in DeltaLab, in the end a lot of apps get recommended anyway because they also just register to handle everything, and sometimes the filename/extension is not available in the URI for reasons, so I ended up registering for opening everything in DeltaLab so the sharing works for .xdc files but also for any other file that gets "opened with deltalab" which is a bit wierd

I don't think it makes much sense on mobile to have this feature, in desktop I see the point, but it is not like users will be playing around organizing in folders a collection of webxdc apps, that is not how most users work on android, and we have the in-app store for that apps management and sharing already, so I recommend closing this issue, we can reopen if it is considered otherwise at a later point

**Comment by Simon-Laux** [comment]
The point is you dl sth. in browser then you can just click on it to share it in deltachat. not to keep an collection as files.

**Comment by adbenitez** [comment]
> The point is you dl sth. in browser then you can just click on it to share it in deltachat. not to keep an collection as files.

that is **exactly** the sort of thing that will not work if you simply register for opening files with extension .xdc, that was what I used to try while implementing it in deltalab, I go to webxdc.org, click on the download of some of the games, then it is downloaded, I click the open button in the notification and you get an intent that does not have the file extension anywhere:

![image](https://github.com/deltachat/deltachat-android/assets/24558636/239cda7e-66af-4954-b326-c60944f5247b)

**Comment by adbenitez** [comment]
> have you tried this code?:

yes

**Comment by adbenitez** [comment]
> have you tried this code?:
> 
> ```
>  <intent-filter>
>     <action android:name="android.intent.action.VIEW" />
>     <category android:name="android.intent.category.DEFAULT" />
>     <data android:scheme="file" />
>     <data android:host="*" />
>     <data android:pathPattern=".*\\.xdc" />
>   </intent-filter>
> ```

as you can see in the screenshot, the scheme is not even file, it is content

**Comment by adbenitez** [comment]
@Simon-Laux why did you reopened? see my comment above

**Comment by Simon-Laux** [comment]
Ok now I get it's the notification intent that does not work, does it work in the file browser at least?

**Comment by adbenitez** [comment]
> Ok now I get it's the notification intent that does not work, does it work in the file browser at least?

it varies from file manager to file manager... if you are not going to work in this issue, please close

**Comment by Simon-Laux** [comment]
Thanks for the elaboration, seems android really has no decent support for registering for custom file types.
Especially after the move to not pass around real paths anymore.

So unfortunately not really possible on android. Closing this issue again
