### ISSUE TITLE
message search result items don't show when it is a contact request

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#2552]
confirmed by @adbenitez

**Comment by adbenitez** [comment]
also if the chat is archived is not shown, this badges also take quite some space and more in the phones

**Comment by adbenitez** [comment]
thinking about it better, due to reduced screen space, it doesn't make much sense to show a contact request badge per message result, they are shown only for chats not for individual messages which makes sense because the chat is the contact request and displaying it for every message would look a bit weird IMHO, lets close this here, we can open a forum thread if we want to keep discussing this feature request
