### ISSUE TITLE
Chosen avatar image outlined in soft black, causes different image content than selected in Desktop app (w/o outline)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2577]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 from 2023-05-20).

- Delta Chat version:
1.36.5.

- Expected behavior:
After chosen (selected), the avatar image content is not outlined by a soft black circle.

- Actual behavior:
After chosen (selected), the avatar image content is outlined by a soft black circle.

- Steps to reproduce the problem:
-- Prepare a Desktop client to become a second Delta Chat device.
-- Select a softly coloured image for your avatar in the settings of the Android app. (For comparison, select the same image file for your avatar in the settings of your Desktop client.)
-- Enable "Copy-to-self" in the settings.
-- Send a message in any chat and receive it in the Desktop app.
-- Recheck your avatar image in the Desktop app settings. (Result: The image suddenly carries a dark border.)

- Screenshots:

Result on Android (with outline):
![grafik](https://github.com/deltachat/deltachat-android/assets/51095533/972f68ae-a527-4fc8-83ad-d6995bf07551)

Result on Desktop (w/o, correct, IMHO):
![grafik](https://github.com/deltachat/deltachat-android/assets/51095533/6e231e09-0d26-407b-9252-7acb4dad3fda)

- Logs:
N/A.

- Remark:
-- Note: This is not just a local app display issue. The respective image file content seems to be imported and applied differently in the two apps, and I believe that it is not done correctly in the Android release.

**Comment by r10s** [comment]
> This is not just a local app display issue

good that you underline that detail. if the border is added on import somehow and shared to others, this is a bug, indeed

**Comment by adbenitez** [comment]
> The avatar passed to AvatarHelper.setSelfAvatar should not be cropped to the circle IMO,

just checked this, the avatar passed to setSelfAvatar is not cropped, indeed in the receiving side if I go to the peer profile and click on the avatar I can see the full square image, I think the issue here is that the avatar gerry tried is a circle icon already with transparency and then the alpha channel is removed and replaced with dark when converting the image to jpg and/or recoding / reducing quality/size

if in desktop it works it is maybe because desktop is not removing the alpha channel and passing the raw avatar with transparency, I don't think supporting avatar with transparency is a must, in fact it can cause confusions and ugly layouts like the circle avatars looking smaller or not a circle shape at all, so it is fine if we remove the alpha channel, 

closing this issue then

**Comment by gerryfrancis** [comment]
Unfortunately I cannot review the original file of this avatar image anymore to confirm/deny, but many thanks @adbenitez and @link2xt for "outlining" the alpha channel issue. :)
