### ISSUE TITLE
Add advanced setting for `fetch_existing_msgs`

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2580]
Now that `fetch_existing_msgs` is disabled in the core with https://github.com/deltachat/deltachat-core-rust/pull/4423, this function is not used.

One way to still be able to test it and improve it would be to add an advanced setting "Download last 100 messages" on the configuration screen, disabled by default.

**Comment by r10s** [comment]
to me, it seems to be a bit unclear, what we actually want here. there is some forth and back with this feature :)

being possible to download only 100 messages and deciding before even log in sounds very special to me.

there are ideas around to have a button as "download existing messages" somewhere in the settings that allows downloading existing messages at any time; that seems to cover more use cases.

closing this issue here, however, we can move it to the forum at any time
