### ISSUE TITLE
combine "Create Verified Group" and "Create Group"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2775]
_before this issue is targeted, #2773 and #2774 needs to be closed._

letting the user decide whether to create a normal groups or a verified group already from the "create chat" dialog is hard. users usually won't know the differences and the advantages and disadvantages at this moment, if at all later.

to still make verified groups a  1st class element, strike the "Create Verified Group" option and let the user just create a normal group.

if it turns out on real creation that only verified members are added, ask the user whether they want to create a verified group (later on, we may skip the question):

```
All added contacts have a green verification checkmark.
Do you want to create a group that guarantees end-to-end-encryption?

[Learn more]      [Cancel] [OK]
```

(note, that we do not speak about "verified group" or "protected chats" or so - neither here nor in the rest of the app)

**Comment by Hocuri** [comment]
I am concerned that the flow of "I want to create a verified group" is interrupted, see the story below. From my view, all in all, this would neither improve nor decrease usability, so I'm just like -0.1 on this.

1. Alice wants to create a verified group with Bob and Carol, because a security trainer told her that it's safer this way. She doesn't have Carol verified, and doesn't know that this is a problem.
2. "Hm, let's try the 'New Group' button"
3. She adds Bob and Carol.
3.1. "Hm, but how do I make it verified?"
4. Alice is confused.

---

One alternative is adding a checkbox. Other messengers like Telegram and WhatsApp also have some settings at this point which most people ignore. Details:

- Add a checkbox (or another kind of setting) "Guarantee End-to-End Encryption".
- If it's enabled, show an explaining AlertDialog with a wording similar to what @r10s proposed.
- If it's enabled, only allow adding verified contacts, as in https://github.com/deltachat/deltachat-android/issues/2773.
- If unverified contacts were added, grey it out.

Of course, the disadvantage of a checkbox is that it will be more effort to implement.

**Comment by r10s** [comment]
yip, we (@hpk42 and me at least :) were thinking also about an checkbox below the member list in the "create group screen", this would be more effort, but this is not the point.

the point is more to nudge ppl more into verified groups in general.  this is interesting in the broader context of chatmail and esp. _leaving_ chatmail-servers with AEAP. as we nudge ppl into verified groups, of course, we have to mitigate issues (as eg #2773 - but also fixing bugs)

a follow up of asking ppl may even be to let just the app decide whether a verified group can be created.

for the scenario of security trainers: they could just tell: make sure, all members you add to the group have the green verification checkmark - then, the groups also gets that checkmark and is guaranteed end-to-end-encrypted. in either way, they need to know how to verify ppl, which is the harder part anyways.

**Comment by adbenitez** [comment]
> [Learn more]      [Cancel] [OK]

the cancel/ok doesn't fit well here IMHO, because user clicks the "create group" button and then they get asked if they want to make it verified, it is a yes/no question, and the result is always the creation of the group verified or not, saying "cancel" feels weird as one would expect canceling the group creation action you just did
