### ISSUE TITLE
use "QR Code Icon"

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2820]
Users expect "invite link" or QR code to be somewhere in the group profile, but not in the member list. Because of this, they open the group profile, overlook "QR Invite Code" in the member list and go search for it in 3-dot menu or click the title bar (which opens the avatar in full-screen) in an attempt to find the screen that looks more like a profile with an info section.

While it is logical for "QR Invite Code" to be considered somewhat similar to "Add Members" action, it is not where users look for it.

Maybe transforming two items ("Add Members" and "QR Invite Code") into two overlay buttons with different icons ("+" and "QR code") could help.

As a minimal change, add "QR Invite Code" into three-dot menu as well as keeping it inside the member list.

@kermoshina :
> actually may be good to add group QR in group profile - when clicking on the group name

(this is not a actually a group profile but this huge avatar screen with "edit" button looks more like a group profile than member list)

**Comment by r10s** [comment]
thanks for filing the issue!

we have the **+ QR Invite Code** meanwhile in bold, not sure if it was the case already during the test. even if overlooked by some/one testers, i do not think it is _easy_ to overlook if you're already searching for that term and are in the profile:

<img width="403" alt="Screenshot 2023-11-04 at 23 34 18" src="https://github.com/deltachat/deltachat-android/assets/9800740/4aeba0d9-00b0-4ff1-a467-a363c30c17cb">

i do not think floating buttos or whatever can make this much clearer.

another thing is adding an additional option to the kebab menu.

we are considering streamlining the chat-menu and the profile-menu anyways since some time, it is especially confusion that it is not clear which items are where. 

this is the current idea we figured out together with @adbenitez for the same menu in chat and profile:


```
Search / Copy to Clipboard * **
Disappearing Messages
Mute Notifcations
QR Invite Code
Archive Chat
Leave Group
Delete Chat
More >
     Sound
     Vibrate
     Encryption
     Block Contact 
     Clear Chat
     Clone Chat
```

`*` this is the only item that will be different in chat-/profile-menu
`**` "Edit" wil becomes a pencil

**Comment by r10s** [comment]
> A QR-code icon would make it easier to find, not the floating button itself. If it is possible to replace this (+) with a QR-code icon, this would also help.

yeah, i misread your point initially and meanwhile also edited my comment. replacing "+" by a qr-code-icon makes sense.

**Comment by r10s** [comment]
> we are considering streamlining the chat-menu and the profile-menu anyways since some time,
this is the current idea we figured out together with @adbenitez for the same menu in chat and profile [...]

sleeping it over, i am not sure if making both menus completely equal is a good idea.

- we never got complains afaik
- it may worse ux as it may become unclear what "clear chat" or "delete chat" in the member list means. "i thought it is only the members"
-same for "clone group": offering that in chat view may raise expectation that messages are cloned 
- really rare items do not need to be duplicated

i suggest to solve the issue more on point therefore, without reinventing everything. this is also easier code wise

**Comment by r10s** [comment]
after some forth and back, to close this issue, showing the  QR code icon is sufficient (the same icon as in the main screen, on a round circle as the "+" then)

this should point users much better to the right direction as a "+" and is far less easy overseen

updating the menus because of this issue is probably not really helpful and will clutter things otherwise
