### ISSUE TITLE
add "close" button in the upper left corner of the welcome title bar

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2870]
some people click "add new account" then don't know how to go back, or close the app and forget then opening again opens in welcome screen, and they think their accounts are lost

**Comment by r10s** [comment]
not sure about that; using the "recent app" list or the "quick app switch" or similar things should work as expected, so that may be more complicated than it appears at a first glance; also, it may be unexpected even when tapping the app icon (as this is not how android usually works)

that said, the issue that ppl may bet lost in the welcome screen is valid; i suggest to just add a title bar with a regular "back" or "close" button in the upper left corner, this is needed anyways. if then ppl still get lost we can think over adapting the flow
