### ISSUE TITLE
Editable subject line

### ISSUE THREAD

**Issue by westsibe** [deltachat/deltachat-android#290]
![screenshot](https://user-images.githubusercontent.com/29564089/38455803-94715b0e-3a6c-11e8-8268-857e47b5146a.png)

Please see an image...

"Chat: Encrypted message" in subject it is poor variant for sending on traditional e-mail addresses.

Also, poor that impossible add text for attachment in one message!

**Comment by r10s** [comment]
hi @westsibe 

thank you for your post.

regarding the subject: 
- For _unencrypted_ messages, the subject is set to the beginning of the message body. 
- to not leak data in _encrypted_ messages, this subject-excerpt is currently replaced by the "Chat: Encrypted message" placeholder. 
- Upcoming releases will also add the subject-excerpt to the encrypted payload which should shown by compatible clients as K-9 or Enigmail,  however, there are still some issues with that, see https://github.com/deltachat/deltachat-core/issues/139
- There are also some ideas keeping the `Re:` part, see https://github.com/deltachat/deltachat-core/issues/136
Yes, there is room for improvements. Regarding a separate input field for the subject - i do not like this. I think Delta Chat is a messenger in the first place and should not try to copy traditional e-mail-clients while, of course, staying compatible to them wherever possible, see above.

regarding text+message in the same mail: i do not see this as a top prioritiy, i am not even sure if this is compatible with the current, simple workflow., at least internally, this would require some new structures, i am not sure if we have the resources for this. but i know some other messengers do have this option (i have never used it, however :)

**Comment by westsibe** [comment]
1. In the screenshot, I meant that it was possible to call up a field for the Subject of message. Initially, let this field be hidden.

2. And it may be better if the default folder in Delta Chat is the Spam folder. This will make it possible to use ONE e-mail address in Delta Chat and in another Push mail. Currently this is a bad option, since notifications come from Delta Chat and from Push mail at same time. (From AquaMail for example).

**Comment by csb0730** [comment]
I think all this is related to the ability of DC (core) to handle multipart messages. I recommend to read the issues 91 and 90 of deltachat-core.
Both are describing current problems around this. This means explicitly that DC is designed (in the moment) to handle only single part messages. There are the two cases sent (1) and incoming (2)  messages:
1. If you intend to send a message, you can send everything, but exclusively text, picture or what ever (this issue here).
2. Incoming messages are split into single parts which are worked and shown seperately (and this is not perfect, see 90 and  91 dc-core).

I think it's worth to think about this issue(s) to be compatible with other MUA (and to make dc more userfriendly).

1. can be solved in combining text and picture to one email (multipart or text with embedded uuencoded part)
2. workflow is ok so far, but splitting needs to work properly (but here open issues 90, 91 of dc-core)

I hope this helps a little to clear this discussion.

At the end: If these issues are solved many following discussions around email compatibility and usability may be prevented :-)

**Comment by fphammerle** [comment]
Added bounty for option to manually change the subject of a new chat
https://www.bountysource.com/issues/56768801-editable-subject-line

**Comment by testbird** [comment]
A possible alternative, instead of special UI functions may be to allow for a manual definition of the the subject by using the same separator "-" as when displaying received subjects.

Example:

     New Feature  - Deltachat might make the subjects user defineable by using a separator.

**Comment by rgedda** [comment]
+1 from me!

I found out about Delta Chat the other day and I love it. Just blogged about it:

https://www.gedda.info/?p=1199

Having an editable subject line or a character separator would be awesome.

"Meeting next week? - Hi John, are you available...."

And "Meeting next week?" is the subject.

Another option would be in the settings. Tick a box to "Set the first sentence (before full stop.) to be the subject", or something similar.

I'm happy to pay for the bounty to do this if that is all good with the contributors.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
