### ISSUE TITLE
allow creating invite-code in-app

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2939]
currently, invite-links for https://i.delta.chat need a copy+paste process.

the idea is to simplify that, maybe by offering a "share to" directly, but at least by offering copying the correct URL to the clipboard.

#2938 already mentions this option

once this is settled, we should create corresponding issues for desktop/ios

**Comment by adbenitez** [comment]
when user selects the "share" option the link could be shared as text in addition to the image I guess

I think you are recommending to add explicitly a "copy link to clipboard" option?

I am afraid this will get a bit confusing with the existing "copy to clipboard" option and user might paste link from clipboard instead of raw QR-data etc.

btw the old copy-to-clipboard is kind of unnecessary with the links :thinking: maybe the copy-link should replace the existing copy-to-clipboard option? (paste from clipboard is then not necessary

**Comment by r10s** [comment]
> when user selects the "share" option the link could be shared as text in addition to the image I guess

is image sharing really still a big thing if we can share a link instead? and does it make sense to share both the same time? maybe yes if it does not hurt :) however, note, that i.delta.chat could also generate the QR code automatically

and yes, copy could also write the i.delta.chat-links instead of OPENPFP4FRP-links, assuming, they are handled by paste correctly
