### ISSUE TITLE
contact name lost after app update

### ISSUE THREAD

**Issue by monperrus** [deltachat/deltachat-android#2961]
Steps to reproduce:
- Change the contact name in the app (click on profile >> profile >> Edit name)
- Wait until next app update from Play Store

Expected behavior:
- The changed contact name is still there

Actual behavior:
- The change is undone, lost. The contact name goes back to the email from header.

**Comment by gerryfrancis** [comment]
@monperrus Thank you for your report. From which to which version did you update?

**Comment by monperrus** [comment]
The latest App Store version pushed on Dec 6, 2023, from the previous one.

**Comment by gerryfrancis** [comment]
Sounds like a duplicate of https://github.com/deltachat/deltachat-android/issues/2871 to me, but it was fixed on Nov 17, 2023, hmm...

**Comment by monperrus** [comment]
thanks! it seems so related that I suspect my version 1.42.6 does not have the fix in it. or?

**Comment by monperrus** [comment]
no, not at all related to a backup restore.

**Comment by adbenitez** [comment]
hi @monperrus did this happened again after updating to the latest version? otherwise could be considered an old/solved issue then, maybe the reason was even not related to the app upgrade but multi-device ex. deleting your name in desktop and got synchronized with android or something like that :thinking:

**Comment by monperrus** [comment]
hi @adbenitez yes, closing it. if this happens again, I'll post here. thanks!
