### ISSUE TITLE
re-label delete/accept request buttons to ignore/accept

### ISSUE THREAD

**Issue by bar-g** [deltachat/deltachat-android#2965]
When delta chat clients are configured to show all e-mail, incoming e-mails show up as new, locked chats labeled "request".

The problem is that the buttons to proceed are labeled "delete" and "accept".

Deleting the e-mail is surely not desired in many cases, so maybe just re-labeling the buttons to "ignore" and "accept" could possibly better indicate what they do.

**Comment by Hocuri** [comment]
The reasoning in calling the button "Delete" is that the chat is deleted. It's the same as if the user had clicked "Delete Chat".

On the other hand, nothing in the current request UI tells the user that "Delete" means deleting the chat rather than message(s). So, I tend to slightly agree with @bar-g that "Ignore" would be better even though it is inconsistent with the "Delete Chat" button's wording.

**Comment by adbenitez** [comment]
"ignore" implies the chat will be blocked and ignored in the future, I find delete/accept a contact request more friendly
