### ISSUE TITLE
tune down in-app emoji selector

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2980]
the in-app emoji selector is worse than what most modern keyboards offer wrt emoji, eg ...

- modern emoji
- stickers

... are available by many keyboards - but not by our in-app emoji selector.

the last update was several years ago, it seems, we cannot really maintain that effort, even if we based on existing upstream (which does not supported older android ...). also, it seems unnecessary as things are already offered by keyboards - and our limited resources are better spent elsewhere.

to move forward on this issue, get some feedback and to not annoy existing users too much, we could do the following:

1. let `pref_system_emoji` default to `true` for new installations (existing installation stay as is for now)
2. move option "Appearance / Use System Emoji" to "Advanced / Use In-App Emoji" with the subtitle "In-app emoji often has less features" (just beside "Use In-App Camera")

then, let's see what happens :)

as a successor, we could check out [EmojiCompat](https://developer.android.com/reference/androidx/emoji/text/EmojiCompat) and see if that can replace emojify() & co. but that can come later as needed and would require are larger cleanup.

@adbenitez @all or do newer androids with really worser-than-our emoji-picker exist? all i have seen recently on androids was way better, even the default stock-androids in the emulators

**Comment by adbenitez** [comment]
instead of removing the emoji picker button, we could replace it with the same picker we use for reactions, this will only work on android 5+ so we would only need to remove the button for android 4 which is a good compromise, then we have an emoji picker that is even auto-updated

closing this issue since the complete removal of the emoji picker button is an anti-feature for several users that find it hard to pick emoji without it (I already experimented this in DeltaLab and completely removed the button and people often complain about they miss the button)

**Comment by Gh0stz0x** [comment]
Besides being unsightly, there are often keyboards that require you to hold down the emoji key for a long time, then select the desired emoji.
People are lazy 😉
