### ISSUE TITLE
encrypt settings database

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#302]
I was just messing around with a database reader and found all my account info in delta chat was unencrypted.  What else can be read in plain text in data crypt database?

**Comment by r10s** [comment]
how would you encrypt the account info? where to save the password needed for decryption?

currently, unless you root your phone or enable the debug mode, afaik, the data are protected by the system so that other apps cannot read them and also they're not readable via usw.

however, any ideas to improve this are very welcome :)

**Comment by r10s** [comment]
some more background: In the Android-slang, we use "internal Storage" which is described at  https://developer.android.com/training/articles/security-tips as:
- By default, files that you create on internal storage are **accessible only to your app.** Android implements this **protection**, and it's sufficient for most applications.

https://developer.android.com/guide/topics/data/data-storage#filesInternal gives some additional details:
- By default, files saved to the internal storage are **private to your app**, and other apps cannot access them (**nor can the user**, unless they have root access).
- When the user uninstalls your app, the files saved on the internal storage are **removed**.

That's about Android. I do not really know Google details - does Google backing up Apps - including internal data - to their cloud? On OS upgrades? I do not know if this happens. Does anyone has more information about this?

**Comment by johanw666** [comment]
Well, you could use SQLCipher and store the encryption key for it in the Android keystore like Signal does it. There are ways to get to that information if you are root and know the device's unlock code/pattern, but that's much less straightforward.

**Comment by johanw666** [comment]
@r10s Google can sometimes backup data to the cloud but you can forbid that in the manifest. The following is an example from the manifest from Signal:
```xml
    <application android:name=".ApplicationContext"
                 android:icon="@drawable/icon"
                 android:roundIcon="@drawable/icon_circle"
                 android:label="@string/app_name"
                 android:supportsRtl="true"
                 tools:replace="android:allowBackup"
                 android:allowBackup="false"
                 android:theme="@style/TextSecure.LightTheme"
                 android:largeHeap="true">
```

**Comment by r10s** [comment]
@johanw666 thank you for the hint, didn't know this - or forgot i've known this some time :)
in fact, [Delta Chat also sets android:allowBack="false"](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/AndroidManifest.xml#L48)

Do you know what the tools:replace="android:allowBackup" is for? A fast DuckDuckGo search didn't gave me sufficient answers.

**Comment by johanw666** [comment]
From https://developer.android.com/studio/build/manifest-merge I get the impression that has something to do with merging multiple manifest files. Since Signal doesn't have that I would guess that it may have something to do with settings they set in gradle.build such as the version number, but I could be completely wrong.

The flag prevents backup to Google cloud and with adb. Of course a root tool like Titanium Backup just ignores it but TiB doesn't work with Signal anymore because they use the keystore to store the encryption key for their database.  Because the absence of a backup irritated me, I forked Signal and wrote my own backup routines; for that I had to figure out all that keystore stuff.

**Comment by johanw666** [comment]
@testbird I just copy all files under `/data/data/org.thoughtcrime.securesms`, and I store the key to encrypt the database in a separate file. On restore, I copy all files back and re-create a valid keystore entry with the database key. If any messages are exchanged after the backup was made one might have to reset the session in Signal after restore, something that does not apply to Delta Chat because DC does not implement forward secrecy.

**Comment by r10s** [comment]
related: https://github.com/deltachat/deltachat-core/issues/194
