### ISSUE TITLE
quote reply goes to wrong chat 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#3032]
With 1.44 android a quote reply can land in the wrong chat like this:
- in a 1:1 chat do a quote reply of a former message, maybe type some chars 
- tap top bar to go to "shared chats" and select any shared chat with that one contact 
- the quote-reply from the 1:1 chat will now appear in the selected group chat still referencing the message from the 1:1 chat

**Comment by r10s** [comment]
i can confirm the bug :)

things to add:

- at least typed text is not taken over to the other chat, only the reply - bad enough, though, as it should not appear in the group at all

- one really needs to go over "shared chats" - so the issue is probably that the reply is not cleared on reusing the intent

- the bug is not new, maybe existent since forever (just checked with 1.42)

- iOS and desktop do not have this bug
