### ISSUE TITLE
don't auto import .vcf file attachments when pressing

### ISSUE THREAD

**Issue by AndySchroder** [deltachat/deltachat-android#3042]
- Android version: 14

- Delta Chat version: 1.44.0

- Expected behavior: prompt what to do with .vcf file attachments so we can save the file to shared storage or forward it to someone else.

- Actual behavior: .vcf file is auto imported into the contacts storage and merged with all other contacts

- Steps to reproduce the problem:

1. export all contacts from another phone to a single file in .vcf format
2. send the file to yourself
3. press on the attachment on second phone
4. tons of contacts are automatically imported without asking

**Comment by AndySchroder** [comment]
Also, say you did want to import the .vcf file with all contacts and not save it to shared storage or forward it to someone else, you can do that, but as it is now if you do import all contacts into a fresh new phone but later are scrolling through messages and accidentally press on the .vcf file again, it will re-import the contacts and you'll have a bunch of duplicates.

**Comment by r10s** [comment]
thank you for your report! 

handling of `.vcf` will be added soon, so this issue will probably disappear anyways.

apart from that: afaik, Delta Chat is not saying "please import", so we cannot really ask for it. Delta Chat is just firing an intent for files it cannot handle, letting the system or the user decide what to do with it - that could be displaying, import, whatever. we do not know - so and additional question can also be annoying.

the responsibility about a confirmation seems to be more on the  the receiver side, that knows what to ask the user. i just tried on a quote standard phone - i was asked several time how to proceed - last time by the contact app:

<img  width=230 src=https://github.com/deltachat/deltachat-android/assets/9800740/7a0172ba-6fd1-4d31-b638-fc7910253d94> <img  width=230 src=https://github.com/deltachat/deltachat-android/assets/9800740/6a4bf4d6-9b39-479a-9b75-9325559c9a17> <img width=230 src=https://github.com/deltachat/deltachat-android/assets/9800740/35db9293-c284-4529-980e-66cacb69ec4e>


but as said, Delta Chat will soon know about these types and handle them explicitly

**Comment by AndySchroder** [comment]
I am using the default contact app in GrapheneOS, which I think is the default contact app from the AOSP. I only have a single contact app and no third party contact list storage providers so that is why I think I am not getting the first 2 screenshots that you show. The third one I am also not getting, is that coming from the AOSP contacts app?

**Comment by AndySchroder** [comment]
I understand the you are saying you are only firing an OS intent on the file. If the third screenshot prompt came up, that would make sense to me to be enough of a warning, but I don't seem to get that. Would be curious what other people get. I guess I have mixed feelings about DeltaChat firing OS intents on a press of a file. Wondering what other situations might exist where we might want a warning before doing that?

**Comment by r10s** [comment]
for passing intents to other apps in general, thanks for bringing that up, i took the chance to have a closer look at that.

i just checked some other messengers and other apps - most do exactly the same when a file is tapped. i think it is expected like that and it also makes sense to me. i would just stay with that is common user expectation here.

sure, there are situations thinkable where the target app does something unexpected - but we did not really got complains here in the past justifying an extra step - in fact, this issue is the first i can remember in all the years :) 

and if the target app is buggy - well, in this case one does not know before and an additional warning does really help. and if one does not trust the target app, one is anyways in trouble, also without opening the file :)

but feel free to open a feature request at https://support.delta.chat 

as said, this issue will be targeted by the new `.vcf` support, so i think, we can close here.

**Comment by adbenitez** [comment]
I also tested and get asked to import contacts before proceeding, I am using CalyxOS, with default contact app
 
> I am using the default contact app in GrapheneOS

I think you should report this issue to the OS vendor, or the contacts app creator, it makes lite to no sense for a contact app to directly import any random .vcf upon opening without letting you select which contacts to import or at least to confirm to import and completely polluting your contact list in a way that might be pretty hard to recover and remove the unwanted contacts, it just makes no sense

 I don't think that is something that should be fixed in every app out there, but in the app that is working wrong, your contacts app, for example, also in signal, when clicking the vcard, it opens directly the contacts app, and I bet that will happen for most other apps out there, then what is the solution? to go asking to every app to patch this issue or should that contacts app the one to fix that odd behavior??

I am closing this issue as I don't think the real issue will get fixed just by us creating a hacky patch, and the extra dialog will annoy the majority of our users that have a normal contact app that will ask before importing

thanks for creating this issue, and I am sorry we can not solve it for you, maybe you can try another contact app for example: 
https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/
