### ISSUE TITLE
Invalid resource ID 0x00000000

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#3054]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 14.

- Delta Chat Version:
1.45.0 (beta).

- Expected behavior:
Not to read `Invalid resource ID 0x00000000` in a log.

- Actual behavior:
The log includes several lines that contain `Invalid resource ID 0x00000000`.

- Steps to reproduce the problem:
-- View the log under `Settings` -> `Advanced` -> `View Log`, and search for `Invalid resource ID 0x00000000`.

- Screenshots:
N/A.

- Logs:
[deltachat-log-20240515-134732_2.txt](https://github.com/deltachat/deltachat-core-rust/files/15321267/deltachat-log-20240515-134732_2.txt)

**Comment by adbenitez** [comment]
we tried in several devices and emulators and couldn't reproduce, it seems to be related to the Preferences classes (settings screen) and Android 14 (SDK 34) but there is no clear source of the logs, it seems not directly from our code, maybe they come from [Glide](https://github.com/bumptech/glide/issues/413) dependency, and since it seems there is no visible error or problem caused by that log entry, I think we can close here until this turns a real problem affecting the user and we have a more clear idea how to reproduce it
