### ISSUE TITLE
Dont alter names of attached pictures!

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-android#3093]
I realized today that when i sent pics from ds (Android) to another ds (PC) and store it to local storage there, the filename changed to worse (the ds sending datetime). This is a **nogo** if you depend on the original filenames for legal reasons!

So why is this? Why must it be this way? Can it be changed to: use the original filename for sending?!

- Android version:
- Device:
- Delta Chat version: 1.44.0
- Expected behavior: keep the orig filename
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots: 
![grafik](https://github.com/deltachat/deltachat-android/assets/37833326/75f0e375-27f0-4a65-8258-e89a3f4596f4)

it clearly can be seen that the picture cant be taken at 12:45 , its from 21:30 from another day.

![Bildschirmfoto vom 2024-05-24 14-59-48](https://github.com/deltachat/deltachat-android/assets/37833326/606ed628-a7c6-432f-984f-fe3892502ad9)

**Comment by r10s** [comment]
name and metadata are removed on purpose by default for privacy reasons - to protect unaware users from revealing their position, the time of the photo etc. unexpectedly.

moreover, the image is recoded by default to save traffic and storage.

however, you can bypass these defaults by attaching images as "File" (for technical reasons, this sometimes adds a suffix to the filename, however, this will be improved with one of the next releases, so that really the original name is used)
