### ISSUE TITLE
Make it possible to opt out of obtaining FCM token before creating a profile

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3142]
Currently application checks if push notification preference is enabled at the application start:
https://github.com/deltachat/deltachat-android/blob/7e7257bf4180060495c86cb10cd09121f9e69d77/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L230-L239

If preference is enabled, FCM token is requested and once it is obtained it is uploaded to the server.

User has no chance to change the setting before creating a profile and even then FCM token is already obtained.

**Comment by adbenitez** [comment]
to be honest an user visible option to enable/disable push notifications is already unheard of, most apps don't expose this, if it is really important using fdroid version without any push notifications should be the way to go, otherwise there shouldn't even be any option to disable push notifications if you install from google play

**Comment by r10s** [comment]
ftr, the option was added initially _not_ for gplay to disable FCM but to have it [disabled by default for fdroid](https://github.com/deltachat/deltachat-android/pull/3090), which turned out to be [not sufficient for fdroid](https://github.com/deltachat/deltachat-android/issues/3030#issuecomment-2133566742). and when we then added [a different build flavour for fdroid](https://github.com/deltachat/deltachat-android/pull/3122), the option was left as is somehow :)
