### ISSUE TITLE
Android v1.46.5 forces a profile name

### ISSUE THREAD

**Issue by Norbert80** [deltachat/deltachat-android#3160]
I cannot clear the name field of a profile and confirm. DeltaChat v1.46.5 on Android insists on a non-blank name field.

(Workaround was to remove the no longer wanted profile name on v1.46.1 Desktop (Linux) that has the same account. The profile name on Android was immediately synchronized and blanked.)

![Screenshot_20240713_142758_Delta Chat](https://github.com/user-attachments/assets/99ab1c48-ea6b-4e2a-858a-71d00227e146)

**Comment by r10s** [comment]
the profile name is the most important information others see when you contact them, it is not nice if that is blank for lots of users. 

this is not only a personal decision: it would make groups much harder to read and to follow for all participants.

this is even more true when considering chatmail and randomised email addresses.

note that you can enter whatever you like here, there is no need to enter you real name. just something. at best somethings that help ppl to realise who you are, of course.

for these reasons, we enforce setting a name during onboarding. most ppl do not change the name later, so that has a large enough effect already.

> Workaround was to remove the no longer wanted profile name on v1.46.1 Desktop (Linux) that has the same account. The profile name on Android was immediately synchronized and blanked.

yes, indeed, changing the name should be consistent across platforms as well.

i'd argue, android is doing fine here, and desktop/ios should not allow the empty string here. however, as said, compared to onboarding, this is a minor

**Comment by adbenitez** [comment]
@Norbert80 as an alternative, if you really want to set your display name to be just your email address, which is not recommended, you can set the name to your email address that way the field will not be empty

**Comment by Norbert80** [comment]
Anyway... It should behave the same on ALL plattforms. Are there any plans to harmonize the behaviour?

**Comment by r10s** [comment]
> Are there any plans to harmonize the behaviour?

thanks for the reminder, i also think it makes sense to have that consistent and created issues at https://github.com/deltachat/deltachat-ios/issues/2243 and https://github.com/deltachat/deltachat-desktop/issues/4042

**Comment by Christianpaciel** [comment]
BBIAB
