### ISSUE TITLE
remove gmail's oauth2

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3233]
oauth2 for gmail stopped working, at least partially.

we decided that we do not want to spend additional development resources and extra money for that (we would need a yearly  "CASA Tier 2/3 sth. security assessment" only for that - [despite we have much better security reviews already passed](https://delta.chat/en/help#security-audits), that alone would require quite some bureaucracy effort, which would result in other things not being done).

gmails oauth2 was annoying all the time, it seems a waste of resources for a provider that is not even playing well together. also, there are comparable few users using gmail oauth2 with Delta Chat. finally, with 2FA and app passwords, user can still use gmail.

- for existing gmail oauth2 users, add a device message how they can "exit"

- do not offer oauth2 for new gmail users, instead, use the normal hint, "With 2FA and an app password set for Delta Chat, logging in works fine." (gmail dc user)

this may require adapting provider database

**Comment by gerryfrancis** [comment]
We should aim to support OAuth 2.0 in the long term. Thunderbird has already done so for two years: https://support.mozilla.org/en-US/kb/automatic-conversion-google-mail-accounts-oauth20

And if I interpret this correctly, currently less secure applications that use a simple login that consists of a username and a password will no longer be supported by the end of Sep 2024:
> Starting on September 30, 2024, less secure apps, third-party apps, or devices that have you sign in with only your username and password will no longer be supported for Google Workspace accounts.

(Source: https://support.google.com/accounts/answer/6010255 )

I can be wrong, of course, but if not, Delta Chat users with Gmail accounts might face a real issue in the future, not mentioning the Microsoft 365 account users who are already having it. ;)

**Comment by gerryfrancis** [comment]
@r10s I understand, but what about the deadline (Sep 30th) that I have mentioned before? Do you think Google will decline access to all apps that do not use the featured Google API?

**Comment by r10s** [comment]
> Do you think Google will decline access to all apps that do not use the featured Google API?

i do not know in detail, so  research on that is welcome :)

however, _in my understanding,_ i expect "App Password" generated with google's 2FA enabled will continue to work, at least in the past, this was not what Google called "Less Secure Apps".

**Comment by r10s** [comment]
for K-9, having similar issues,  a user posted in the K-9 forum expects App-Password to continue working as well: App-https://forum.k9mail.app/t/using-gmail-with-k9-mail-5-600-in-2024-using-app-passwords-not-oauth/8536

**Comment by iequidoo** [comment]
App passwords work well for me with all my Gmail accounts, with Delta Chat and Thunderbird. But yesterday my friend reported to me that Delta Chat can't log in anymore after they changed the Gmail account password (but not the app password for Delta Chat), and changing the app password after that didn't help. It's not the first time i see people struggling with Delta Chat + Gmail, but for most of them it works :)

**Comment by gerryfrancis** [comment]
> i do not know in detail, so research on that is welcome :)

@r10s In the document linked above, they also state:
> To continue to use a specific app with your Google Account, you’ll need to use a more secure type of access that doesn’t share password data. [Learn how to use Sign in with Google](https://support.google.com/accounts/answer/12849458).

I would interpret this statement as a sign that logging in with an app password is not going to work anymore by Sep 30th.

**Comment by iequidoo** [comment]
> I would interpret this statement as a sign that logging in with an app password is not going to work anymore by Sep 30th.

<h1>Sign in with app passwords</h1><div class="article-content-container"><div class="cc"><div class="important"><strong>Important: </strong>App passwords aren’t recommended and are unnecessary in most cases. To help keep your account secure, use "Sign in with Google" to connect apps to your Google Account.</div>

<p>An app password is a 16-digit passcode that gives a less secure app or device permission to access your Google Account. App passwords can only be used with accounts that have <a href="[https://support.google.com/accounts/answer/185839](view-source:https://support.google.com/accounts/answer/185839)" rel="noopener">2-Step Verification</a> turned on.</p>

<h2>When to use app passwords</h2>

<p><strong>Tip:</strong> iPhones and iPads with iOS 11 or up don’t require app passwords. Instead use “Sign in with Google.”</p>

<p>If the app doesn’t offer “Sign in with Google,” you can either:</p>

<ul>
  <li>Use app passwords</li>
  <li>Switch to a more secure app or device</li>
</ul>

<h2><a id="app-passwords" name="app-passwords"></a>Create &amp; use app passwords</h2>

<p><strong>Important: </strong>To create an app password, you need 2-Step Verification on your Google Account.</p>

<p>If you use 2-Step-Verification and get a "password incorrect" error when you sign in, you can try to use an app password.</p>

<p><a href="[https://myaccount.google.com/apppasswords](view-source:https://myaccount.google.com/apppasswords)" rel="noopener" target="_blank">Create and manage your app passwords</a>. You may need to sign in to your Google Account.</p>

<p>If you’ve set up 2-Step Verification but can’t find the option to add an app password, it might be because:</p>

<ul>
  <li>Your Google Account has 2-Step Verification <a href="[https://support.google.com/accounts/answer/6103523](view-source:https://support.google.com/accounts/answer/6103523)" rel="noopener">set up only for security keys</a>.</li>
  <li>You’re logged into a work, school, or another organization account.</li>
  <li>Your Google Account has <a href="[https://support.google.com/accounts/answer/7539956](view-source:https://support.google.com/accounts/answer/7539956)" rel="noopener">Advanced Protection</a>.</li>
</ul>

<p><strong>Tip:</strong> Usually, you’ll need to enter an app password once per app or device.</p>
