### ISSUE TITLE
Do not delete messages at server if deleted in Contact Requests

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#327]
New messages where no chat exists are coming up in Contact Requests.
Very often they are not intended to open a chat but needed later to handle them with another MUA.
You want to delete them from local device's Contact Requests but You need it available further on at server!

This is not possible now. They are delete it at server too.

This should be changed in general or there should be a user option to prevent deleting messages at server which are deleted from Contact Requests!

**Comment by testbird** [comment]
Considering, DC is an IMAP server client (with local offline storage). And the "contact requests" are actually "Unnapproved Emails" in your INBOX https://github.com/deltachat/deltachat-core/issues/48. Why would you expect message to remain there for other MUAs when you delete them?

I actually wouldn't want to have to delete messages twice, in DC and then again on the server.

It may depend if one considers the INBOX to be for sorting out the messages or for keeping a longer history. For the latter case I could understand wanting a hide or ignore message function in DC.

**Comment by testbird** [comment]
How would you imagine an unintuitive and understanable UI that deletes messages locally and hides all these messages on the server (until they are removed by another email client)?

**Comment by csb0730** [comment]
Hi testbird,
yes, read work and delete or move by another Client. use case: you make an order for example at Amazon. there are mails coming in for that order which you need to notice and which are most of times in html format. you don't want to start a chat because all these are Single cases or you can't really read it. you need simly delete them locally because they now anyway are at mobile but let it on server.
they don't come up any more because only new messages are downloaded. this is a Standard use case which dc had in the past and which k9 offers as a user option.

Maybe you understand now?

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by testbird** [comment]
I understand what messages you are referring to, now. "Archive for reference" emails that one may just wants out of the way in the chat app.

I use a (server) filters to move those into separate folders, and normally do not have to deal with them (if I don't want to check for particular messages or reset the unread count).

But since this is heavily user dependent, and it may also be needed to only delete a message on the server, and keep it locally.
Maybe the delete modal (notice) could provide the choice (server/local/both).

**Comment by csb0730** [comment]
Hi yes, I think the modal dialog can solve this issue if user has the choice what DC does.

Some more thoughts about this issue:

- in the past this issue doesn't appear because mails at server anyway were leaved untouched.
- now it get's important because DC deletes even mails which are intended to work on with other MUA (!).

@r10s: this is an important issue now. Maybe You can consider a solution for next release? Options in question dialog what to do as proposed by @testbird ?

**Comment by csb0730** [comment]
@testbird: by the way: how can you define server filters for that kind of mails? It's neither clear where they come from nor what is the matter in these mails?!

**Comment by testbird** [comment]
Filtering I use for repetitve things, I see them often coming from something like noreply@shop, or have "confirmation" or something recognizable in the subject.

For ocasional, or not yet filtered stuff, I'd just ignore it in DC (gets seen flag) until I move it away  with MUA ( or maybe https://github.com/deltachat/deltachat-android/issues/324) and only create a filter if  it's woth it.

**Comment by csb0730** [comment]
Ok as I suspected. You don't really know what mails are affected and You do Your filters manually if You have many mails which are not intended for DC.
But this doesn't solve this general issue. You're running behind that mails situation.

DC simply should leave mails at server untouched if they are deleted manually in Contact Requests.

That's the solution.

It is another situation for messages which are intended for DC !

**Comment by testbird** [comment]
Could you please elaborate more on the solution you have in mind?

I don't really understand, why one would want to use DC to manually delete ~~contact requests~~unapproved emails (only in DC) at all, only to have to open the email client afterwards, to delete or move the same messages again on the server. That is a method in which I think the user is running behind every email message, twice.

**Comment by testbird** [comment]
BTW: Also have a look at the plan for a "Local Chat Archive" setting.
(The item just before (above) https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy#re-inits-at-startup-if-network-is-available--on-connection-state-changes)

**Comment by csb0730** [comment]
By the way:
The wording "_unapproved emails_" is IMHO not appropriate for the intention of "_Contact Requests_". I think "_Other Emails_" or similar is a better wording to understand the purpose.

**Comment by testbird** [comment]
(The disadvantage I see with "other emails" is that it doesn't stand in a nice explaining context with the "chat approval mode" (use-cases) and "email-approved contacts".)

The proposed _optiononal_ local chat archive option I mentioned, because the disabled default would allow you to delete or move messages on the server to have them disappear in DC as well.

I'd still like to know if, when or where you see deleting emails only locally has an advantage somewhere.

**Comment by csb0730** [comment]
I'll try to explain a litle more technical again.

My assumption is that You have ONE mail account for use with (both) Your standard MUA (for example Thunderbird) and additionally You use DC with same account. I think this is a standard use case for many people which are using DC.
 
Now suppose:
1. You are using your standard MUA if You have time to do it (NOT ALWAYS online!).
2. DC is in use in parallel but ALWAYS online by mobile.
3. DC cannot handle some mails because of their nature (pure HTML mails)
4. DC must not handle some mails with which You don't want to start a chat or which are really not intended for DC because of their content. But all these are at mail server's INBOX and appear in (so called) _Contact Requests_.

3 and 4 are leading to the problem because DC sees these mails first (PUSH).

So from that point of view _Contact Request_ shows mails which are really not intended for it, but You need them for possibly starting a chat. All other ones are there but must not be touched (at server) because they are intended for handling somewhere else (other MUA with all possibilities).

To simply clean Your _Contact Requests_ You would decide to delete them (locally) and then they never will appear in DC and disturb You.
If these mails are deleted by DC at server's INBOX too, You DELETE MAILS WHICH ARE NOT INTENDED FOR DC ! ==> That's NOT OK.

Maybe it's now more clear? For me It's a must not to touch mails at server which are not intended for DC.

This issue here is not in relation with any local archive function or some similar. IMHO it's just a bad behaviour in the moment by DC which has been introduced since DC deletes these mails (3. and 4.) at server.

Now I simply cannot clean my Contact Requests from locally unwanted mails because then I delete them permanently in INBOX and further handling is IMPOSSIBLE.

More comments about this issue are really welcome.

But my proposal for @r10s is really clear: PLEASE (!) introduce a user setting "don't delete mails at server". Whether for _Contract Requests_ only or _globally_ or _both_ doesn't matter for me. Most important is that it comes!

**Comment by testbird** [comment]
Thank you for explaining, helps a lot. Let me try to sort this out. 

What I had envisioned in https://github.com/deltachat/deltachat-core/wiki/Use-Cases for the "wanting to clean-up" type of appoach was the option to open "tentative chats"(formerly option 3, now first general feature) *for all messages* (option 2.0). To allow the user to browse all new email messages right in the chat list, deciding what to do with them: chatting, deleting (client & server by default), or keeping as email (moving it the message to the unnapproved classic email that would be a perfectly tidy reference list this way).

What's your opinion here?

I see the drawback of opening a tentative chats for all messages is that the sorting becomes a foreground task. (Tidying up the unnapproved classic emails with local email deletions could be done when desired, no matter that it has to be repeated in the MUA again.)

To support your way of usage, there will have to be **two separate default delete preferences** to override a confirmation/selection dialog, one for chat messages and one for the classic emails. A single default setting can't cut it right.

For the "factory default" I'd still say to have "delete message" in the unnapproved (classic) emails really mean delete on the server (and locally of course) is the right choice. The reason is that local email deletions bring redundant sorting work, and introduce explicit inconsistencies between server and local storage. The user needs to have an understanding how "wanting to delete", still "needed for possibly starting a chat", and "needed for MUA use" go together. Also misunderstandings are to expect "I explicitly *deleted* that message and now it is still there in the MUA, it was only hidden."

**Comment by csb0730** [comment]
Hi testbird,
I'm coming more from the old fashioned pop3 usage for email handling and I have only one MUA and one phone in service at my account. Maybe this leads me to this approach of email handling ;-)
 
But, You need simply need to recognize that some emails in inbox You can't handle with DC and they are simply not intended for it. This is not a problem of sorting them twice or a double handling. You need to handle them a second time with classic MUA in each case.

The simplest approach is then really "don't touch them on server" (keep them available) and clean them locally (only one time ;) ).

Only a simple approach is a good approach :-)

A word to unexperienced users: They are not calculate with the fact, that DC deletes their (possibly) important mails from inbox if they clean Contact Requests.

A last thought: There should be a hazard-free possiblity to clean Contact Requests without the impact to disturb standard MUA's mail handling.

**Comment by testbird** [comment]
I recongnized your use-case a couple of messages ago, and concluded yesterday it will need two options, because "delete *chats* only locally" would break chat syncing. (Deleting *emails* only locally also breaks syncing, but that's the respected preference with "POP client thinking".)

In oder to improve the designs, I was also interested in your opinion about an alternative message-flow configuration that maintains a clean inbox.

For me a true solution would not require to mess with emails in deltachat at all, one only needs to handle them once in the MUA, and the unapproved emails in DC will get cleaned up automatically. (With IMAP clients in the moment of the clean-up, and with POP whenever the client is configured to delete the messages from the server.) https://github.com/deltachat/deltachat-core/issues/195

---
@ all
The wording "Contact Requests" also contributes to the notion that the listed emails belong to deltachat, and may have to be deleted if not intended for deltachat to clean up, which should rather not be the case. The list shows the users received emails on the server, that did not approve for chat and have not been moved into the DeltaChat folder, and should get cleaned up together with the server. (Which may be done through MUAs or for simple deletions right in DC.)

**Comment by csb0730** [comment]
If You can handle all shown emails in Contact Requests you need to do it then You can delete it after handling at server. As long as this is not possible DC must not do that (!)

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
