### ISSUE TITLE
New onboarding is confusing and creating friction

### ISSUE THREAD

**Issue by therainingmonkey** [deltachat/deltachat-android#3344]
First, thanks for all the work you do on Delta Chat, it's truly the best messaging application!

Since the new instant onboarding, I've introduced several friends to Delta Chat who have bounced off it and gone back to proprietary messaging apps.

They say, "I can message some people but not others, and I can't post in the groupchat!"

This is because they've created a chatmail account, and so cannot interact with others using classic email. Of course, they're not interested in the explanation and before I can suggest that they try "Add profile" -> "Create new profile" -> "Use other server" -> "Classic email login" they've gone back to Facebook messenger.

Proposals:
* The signup with chatmail should include some explanation that it won't work with unencrypted plain email accounts (and groupchats that contain them).
* That "Classic email login" be moved, so that that after choosing "Add profile" the user is presented with three options: "Create new account", "Classic email login" and "I already have a profile".
* That this screen should have a short explanatory sentence, something like:
  > Chatmail is a secure form of email which will reject unencrypted messages. Use classic email to communicate with people who aren't using encryption

**Comment by gerryfrancis** [comment]
@therainingmonkey Thank you for your detailed report, it is very helpful to understand how Chatmail catches on with some people.

> Use classic email to communicate with people who aren't using encryption

Some potential users might misunderstand this phrase as a call to use apps other than Delta Chat.

However, unfortunately this is not the right place to discuss changes to an already introduced model architecture. Please start/continue this discussion in the [Delta Chat forum](https://support.delta.chat/). Thank you very much.

I am closing here now.

**Comment by r10s** [comment]
i'd like to amend that the discussion, advantages and drawbacks of chatmail/dedicated-address-for-chatting vs. using classic-email-address/existing-address are of course widely known in the team. however, the classic approach fails larger adaption for years, due to big onboarding issues wrt. therefore, we did the change.

https://delta.chat/en/2024-05-31-instant-onboarding will give more depth and answer some questions.

note, that one still can use Delta Chat as before, nothing was removed. if the "classic log in" is too hard, compared to effort and knowledge needed outside Delta Chat, that is a question to discuss better in the forum.
