### ISSUE TITLE
`Group Name` field isn't focused / keyboard isn't shown when creating a New Group

### ISSUE THREAD

**Issue by iequidoo** [deltachat/deltachat-android#3355]
So to type the group name, the user has to do one tap more which is especially inconvenient because group name is mandatory. On Desktop it's auto-focused, so would be good to unify things here. Telegram also auto-focuses the group name field and brings the keyboard on screen.

**Comment by iequidoo** [comment]
+ an unrelated question, but also regarding to quick onboarding contacts to groups -- why not show the QR Invite Code button in the group chat window in the same place where it's shown on the main screen, i.e. next to the vertical ellipsis? That would unify layouts of these screens. Now the Location/Map button is shown there (if it's enabled in advanced settings).

**Comment by r10s** [comment]
to the unrelated question: reason is that "group invite to add members" is a far less often used option than "get in contact  with someone". therefore, we voted for not to cluttering the UI of the chat with a QR Code icon (in fact, we're more thinking about what it would take to removing the QR code from the main screen, as it is at least partly duplicating the functionality from the "+" button :)

**Comment by adbenitez** [comment]
> Telegram also auto-focuses the group name field and brings the keyboard on screen.

in Telegram it is fine because you first select the members of the group and *then* pass to another screen where the only thing left to do is basically to set the group name, that is not the case in Delta Chat, however, probably auto-focusing the input field make sense since there is a lot of empty space in that screen, if it would cover the member list / add-member button it would be bad, but it is unlikely unless it is a super small screen device
