### ISSUE TITLE
Do not remember "New Contact" tab state

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3357]
Currently "New Contact" screen remembers the last open tab: either "QR INVITE CODE" or "SCAN QR CODE".
This makes it difficult to give instructions or write guides because the screen that actually opens when you click the qr code button in the top panel or "new contact" (item with the QR code in the contact list) you may get one of the two screens depending on the last action that you did.

Instead of remembering the state, QR code button at the top panel should always open the scanner (so you can use Delta Chat as a QR code scanner, this should be easy to access the scanner with one click) and "New contact" option should always open the QR invite code. "New contact" is not a frequent action anyway as this is only used by new users and most users get their contact from groups afterwards. Worst case users have to switch to another tab from there.

Reworking the "QR INVITE CODE" screen itself is outside of the scope of this issue.

**Comment by adbenitez** [comment]
> Instead of remembering the state, QR code button at the top panel should always open the scanner

I am not so sure this is a good idea, most of the time what people want is not to scan any QR but to get access to the invite link,

one of the problems that was pointed out in some discussions was that users don't realize they can change this tabs, the scan QR screen is even less user friendly since it will first ask for camera permission and then just a camera screen without any potential to hint that user can change to the other tab :thinking:
