### ISSUE TITLE
Blocked at «please wait: 95%»

### ISSUE THREAD

**Issue by stemy2** [deltachat/deltachat-android#337]
**Delta Chat version**

0.18

**Expected behavior**

Validating my mail settings

**Actual behavior**

The «pdease wait» dialog is blocked at 95%.

**Steps to reproduce the problem**

1. Enter your mail and password while first configure.
2. Click on the validation button.
3. Wait some time.

**Comment by vit1-irk** [comment]
Can confirm on Android 6

**Comment by r10s** [comment]
okay - 95% (950 permille) is here: https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_configure.c#L674

the configuration is done successfully there and it's just cleaning up which seems to hang.

if anyone has an idea what is going wrong in this code snippet,  please let us know :)

**Comment by r10s** [comment]
@stemy2 @vit1-irk is this reproducible?

if so, i can add an apk here with some extra information that you could try then.

on the next app start (use "force stop"), the app should work as expected, as the configuration as such is done.

**Comment by r10s** [comment]
tried to reproduce this, no success.

@stemy2 @vit1-irk which provider do you use?

**Comment by r10s** [comment]
for testing: here is a new apk (0.18.1dev1) that shows some more detailed progress information: 
https://share.riseup.net/#ChwqQm76ihwkBXp9VqtsUA

would be very useful to know at which percentage this apk halts for you @stemy2 @vit1-irk

**Comment by vit1-irk** [comment]
@r10s tried test apk from riseup both with GMail and Yandex. Now it's freezing on 92%

**Comment by vit1-irk** [comment]
After 2-3 minutes 98% is displayed, watching...

// force-stop makes the app usable, but I didn't try to do that before

**Comment by vit1-irk** [comment]
see [logcat.txt](https://github.com/deltachat/deltachat-android/files/2129553/logcat.txt)
_login credentials replaced with "my email"_

98% is displayed after keypair creation is done and then the app is just watching receiver timer

**Comment by vit1-irk** [comment]
[logcat.txt](https://github.com/deltachat/deltachat-android/files/2129558/logcat.txt)

98% is shown after keypair creation is done and from then the app is just checking receiver timer

**Comment by r10s** [comment]
@vit1-irk thank you very much, i have an idea what is going wrong 

(my rough idea: the smtp-thread has to be suspended during configuration, we do this by holding the smtp-thread in idle until configuration is done. However, the condition for the wakeup seems to be wrong, [if the timeout is reached the first time](https://github.com/deltachat/deltachat-core/blob/master/src/mrjob.c#L816), we're waiting for 0 ms and the mutex will stay locked most of the time. dc_configure() has very few chances to set the unsuspend condition. i will try to reproduce this now)

**Comment by r10s** [comment]
@vit1-irk can you please retry with this apk
https://share.riseup.net/#77_bNtx3p6j8Tlg_n_MxjQ (0.18.1dev1)

the version contains a [single change](https://github.com/deltachat/deltachat-core/commit/8396fc786ebb1cc439299a6d466230dbaa3e0753) to avoid heavy load in the suspended smtp-thread. not sure if this fixes your problem, but it might be a _part_ of the problem :)

**Comment by testbird** [comment]
I saw smtp-idle looping entries in the log every minute, is the changeset to stop these loopings if no jobs are pending?

Another small thing I saw, was imap-idle being immeadiately interupted, and starting again.
It was first interrupted by "new data" from server, and likely then again from within the fetch(), and this was so fast, that it reached the new idle (logs all in same second). So no breakage, but CPU cycling.

Overall, usage I can say so far that the foreground messaging seems to work well.
We'll watch the next days for background and screen-off mode.

**Comment by vit1-irk** [comment]
Build №2 works!

Thanks for fixing this so quickly
Here is the second log if you're interested: 
[logcat2.txt](https://github.com/deltachat/deltachat-android/files/2129873/logcat2.txt)

**Comment by comradekingu** [comment]
@r10s
0.18.1dev2 works, but stuck for a little bit at 92%.
0.18.0 was stuck at the same 92% and then stuck at 95% presumably forever.

Installing on 17.2 and upgrading to 18.0 posed no problem.

**Comment by r10s** [comment]
thanks for all the help :)

@comradekingu the 92% are shown when the key generation is started, the time needed for this seems to be very different. on most devices i saw for testing this is only very few seconds - but on my "Moto G4 Play" it's about a minute. The time is spent in [RSA_generate_key_ex](https://github.com/deltachat/deltachat-core/blob/master/libs/netpgp/src/openssl_crypto.c#L757), not really sure what happens here and why there are so large differences.

@vit1-irk thanks for the seconds log - if logcat.txt and logcat2.txt belongs to the same devices, key generation time was reduced from 3 minutes to 1 minute (due to avoiding heavy load is smtp-idle-suspend). This 1 minute seems to be reasonable.

@testbird the smtp-idle loop every minute is by design currently. if there are no jobs to do, this should take no time (there is no network involved) and results in a simple guarantee that failed jobs are restarted at most after a minute (if a job fails and there _is_ network available, the restarting time is only 1 second)
interrupted imap-idle without new messages arriving was also noticed here from time to time, this may be done by the server to guarantee no message is missed since the last fetch, not sure about this.

**Comment by r10s** [comment]
there is a 0.18.1 out now on github and probably in a few days on f-droid
