### ISSUE TITLE
remove account address from notifications

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3378]
i just realised there is quite some noise in the notifiation that show the email address of the account, see screenshots at https://github.com/deltachat/deltachat-android/pull/3377

i suggest to:
- if there is only one account, show nothing thelike
- if there are multiple accounts, show the "private tag", if set. otherwise show the account's displayname

**Comment by adbenitez** [comment]
> * if there is only one account, show nothing thelike

if user added a tag maybe show it even if single account, this would help when user is using gplay and f-droid or nightly  at the same time, but yeah kind of a niche situation it is also ok not to do it, but it would not hurt since the tag is an user action and the user would have non to blame but themselves if they are annoyed by the tag while having a single account
