### ISSUE TITLE
Impossible to access the draft after leaving the group

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3428]
Currently if you enter some text into the composer and then leave the group, the draft stays displayed in the chatlist:
![draft](https://github.com/user-attachments/assets/6b22d5f8-6eb7-4f40-8ace-9d14abb66c37)

It is however impossible to remove the draft without entering the group back. Also if the draft has a long text, it is not even possible to access it as it is only displayed truncated in the summary.

We considered removing the draft when you leave the group, but you can also be removed from the group or get removed and re-added, an in this case losing a draft is not nice because you may have been in the middle of writing a large message:
https://github.com/deltachat/deltachat-core-rust/issues/6175

So a solution would be to not hide the composer if dc_chat_can_send() is false, but there is an existing draft. When user clicks send, fail to send with a toast and make sure to keep the draft so user can do something with it like copying the text and sending to another chat.

**Comment by iequidoo** [comment]
I think a simple solution is to never hide the composer, but warn the user that they can't send messages in the chat, e.g. add an appropriate system message. Then the user can see messages and compose a new one based on them, and then e.g. clone the chat and copy-paste the composed message there.

I think in general it's not good to prohibit users to do smth too early. E.g. prohibiting chatmail users to create contacts manually also has downsides, contacts still may be useful, even not to send messages, but to just have them in the address book, give them names, share with others etc.

**Comment by adbenitez** [comment]
I think it is not that important that you lose the draft after being removed, the chances that this happens is low anyways, and the chance you get added back even more low (in theory, in practice it happens constantly by accident, but not because one want this person to be in the group)

**Comment by adbenitez** [comment]
so I recommend to keep with the core issue and just remove draft after user is removed from group, in the corner case it was an accident and user gets added back, well, that is how it is, and you have to start typing again, most of the time is short messages etc. and it is not worthy the effort in all UIs to handle this corner case to be nice when you get removed and added back WHILE drafting

**Comment by r10s** [comment]
tbh, i am also not super happy with having another state in the UI, esp. one that is rare and will not really be a tested path often used, this is a call for more bugs in cornercases in the future.

eg. on iOS, we have tons of issues with the early responder thing and the message box, we are having a really hard time to fix them and to get a grip onto that, having now another state to take care and think of is does not make it easier. 

also, the fix on desktop and android - tbh, they are not super simple,  they may be tricky in detail and need maintainance, eg. desktop checks some draft fields that may not be exhaustive in the future. 

so, i would also find a core-internal solution much smarter.

did we got many complains from ppl about losing drafts? the original issue at hand was not about that, but to clear the draft ... where i am not even sure if that is needed, or expected - esp, as it may make re-adding harder. i only agree fully that entering the chat should not sort it up again, that really seems to be an issue.

but maybe it is sufficient to fix only that? so, do not change draft time (or whatever we're using for sorting) when a chat is read-only?

**Comment by r10s** [comment]
additionally, i also find the UX weird, having a text field with a send button, but you cannot send.  
you left a group, but it still allows you to type something.  

i also just tested signal and whatsapp: 

both do not delete the draft on leaving and it is shown in the chatlist - so, it is not that clear, what the _expectation_ is here. 

i assume it is also about the option of being re-added and _then_ not lose the draft 
(which, btw, can also be much more than only a bit of typed text, but eg. an image you cannot export, or a webxdc you cannot send ...)

**Comment by r10s** [comment]
> > did we got many complains from ppl about losing drafts?
>
> We never remove the drafts, this is why users don't lose them. 

well, from the view of the user, a draft is lost when it can no longer be accessed [^1]

and i was wondering, if this is a real-world issue with many complains, esp. in the light that a fix has costs, weakens UX signs, and at least WhatsApp-iOS/Signal-iOS, are doing it similar [^2] [^3]

> Worst case this state becomes broken again, like it is now when you have a draft that you cannot access.

i think, everyone of us is experienced enough to see big issues arising from minor "there will not be an issue" changes  😅 - and we are here in an area already known to be hard and are about to add another state/complexity to handle a very minor thing differently ...

... not to mention follow-ups, as buttons need to be disabled, photos just taken need to be exported (as send does not work) etc. you get the idea, one can easily get crazy about finding more cornercases. i do not think, that is worth the effort, but will surely raise discussions and costs again.

it is also not necessarily to be seen as an issue: if a chat cannot be written to, the chat got _frozen_, that's it. no questions, strong UX elements that work as expected

so, tbh, i would fix only https://github.com/deltachat/deltachat-core-rust/issues/6211 and close this one, at least for now

> In Matrix if you leave the room the whole room disappears, together with the draft and message history, does not sound like a good idea.

agree, deleting the whole chat including all messages is also what Telegram-iOS is doing even on leaving a group, quite unexpected

[^1]: having non-accessible drafts is the case since we introduced canSend() years ago, which, btw, was added as a "editing a message where one cannot send" is bad UX
[^2]: github mailing lists with a flacky canSend() were mentioned, however, that is not-so-great also otherwise and i do not see that justifies the costs
[^3]: WhatsApp drafts exist since a long time. the recent change was that they are shown in the chatlist

**Comment by adbenitez** [comment]
> Well, actually, there is one very strong complaint, users don't like lost drafts :D

that is in an understandable situation, but if you are removed from group you can't send the message anyways so it doesn't matter much to lose a draft you can't send anyways

**Comment by adbenitez** [comment]
to summarize my suggested possible solutions:

*a.* on leaving group / member removed, discard draft (seems to be the simpler solution and super expected for the "I left the group" case, being removed while drafting is a niche corner case and losing draft doesn't matter much in that situation)
*b.*  on leaving group / member removed,  keep the draft but don't re-sort / update timestamp (more complex, useful for the niche case when the removal was accidental not worth the effort IMHO, but an improvement wrt current situation, the more annoying part is not losing the draft but the re-sorting of the chat)
