### ISSUE TITLE
Make the 'Add Second Device' QR code bigger

### ISSUE THREAD

**Issue by exelotl** [deltachat/deltachat-android#3466]
I attempted to add my laptop as a second device, but was unable to scan the QR code generated by Delta Chat on my phone, because the image picked up by my laptop's webcam was too blurry.

I then took a screenshot on my phone, and zoomed in so that the QR code took up the entire width of the screen instead of only half the width (before doing so there was ~25% dead space either side). After doing that, the code was read easily. 

- Android version: 10
- Device: LG Nexus 5
- Delta Chat version: 1.48.3

**Comment by r10s** [comment]
indeed, the "add second device" qr code may contain more infomation and may be more dense than the add-contact one - but both use the same rendering and size. the used device, however, is also old and probably has a comparable low-resolution :)

however, we aim to [get rid of the old rendering anyways](https://github.com/deltachat/deltachat-android/issues/3381), for "add second device", this could mean to render the QR code at the same place, but without the gray border.

the text "Scan to set up second device for ..." can go where currently the "experimental" warning is. 

i think, that would look better in general, and might solve the issue as the code could be a bit bigger

**Comment by adbenitez** [comment]
hi @exelotl thanks for the feedback! I think we can close this as a duplicated of #3381 since it is about dropping/changing the current QR layout

in a bigger picture, often desktop computers have much worse cameras (if any!) than phones and we should invert the scanning QR workflow to always scan from phone so there is no need to look like a mad person moving the phone in front of your webcam  :sweat_smile:
