### ISSUE TITLE
delta chat slow

### ISSUE THREAD

**Issue by jmsecurity05** [deltachat/deltachat-android#358]
Hello, someone knows why this slow delta chat tnks

**Comment by csb0730** [comment]
No idea what You mean. Without more details noone is able to understand this issue.

**Comment by jmsecurity05** [comment]
the app was working very well. two days ago it is not stable the messages do not arrive so that it arrives and that go to accounts and touch the pigeon ok so that it brings the messages thanks

**Comment by jmsecurity05** [comment]
my problem is chat folder tnks

**Comment by beenotung** [comment]
It is slow on my account as well, the message cannot be sent even after 4 hours, sometime a new messages can be sent but quite often to keep in the pending state. Not sure if it's the app or the mail server's problem. I'm using mail.com at the moment (receivers is yahoo and gmail, in 1-to-1 chat)

**Comment by webratte** [comment]
@beenotung

Have you tried to send a mail with a normsl mail client?

This way you could check out if it's a mail server problem.

**Comment by adbenitez** [comment]
some people here in Cuba has the same issue and it is due to the slow network in our case, sometimes the message is pending forever, and it actually was sent, sometimes it just take several minutes, seems like the threads get stuck, stopping the app and opening again make it send faster, can you try that @beenotung ???
