### ISSUE TITLE
Translation of Domainnames with  ä ü ö etc. 

### ISSUE THREAD

**Issue by rickcrash** [deltachat/deltachat-android#37]
Domainnames with non-ASCII-letters, eg. german letters like ö ü ä etc, are translated. The answer of an recipient won't appear in Delta Chat, because the translated E-Mail-Adress differs from the recipients one.

**Comment by t-oster** [comment]
can you provide an example? I am not sure I understand where the problem occurs.

**Comment by testbird** [comment]
According to the last link messages including headers can be UTF8, but domain names can not, they need to be in punny-code. (special characters are translated into something like xn--code)

The last paragraph says to use UTF8 everywhere internally,  and to only translate before sending.

BUT (IIUC) the spoofing problem comes in when translating incoming punny domains (what r10s seems to refer to above), because there are multiple punnycode domains that look the same for the user.

Thus, also keeping the domain part as non-ambiguous punny-code for reference internally and use it to assign incoming messages to the right chat (possibly also displaying in the contact details), also seems safer (prevents others to spoof).  (And, do not translate of local parts to always stay unambiguous and prevent mis-addressing and spoofing.)

**Comment by r10s** [comment]
moved to https://github.com/deltachat/deltachat-core/issues/264
