### ISSUE TITLE
DC don't send message until restart

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#408]
Often when I send a message the message don't get delivered until I close and open the app again, seems like the sender thread get frozen or something like that, maybe this is related to the fact my email service is provided through a 2g mobile connection, and probably it is a bit unstable. This isn't something that is happening to me only, but to all the friends and people I have convinced to use the app, and that use the same mail server since it is a service provided to the whole country.
 
- Delta Chat Version: 0.20
- Expected behavior: I can send all messages without restarting the app
- Actual behavior: I must close and reopen the app to get some messages delivered
- Steps to reproduce the problem: probably not reproducible because it is intermittent, but probably will show up on 2g connections.
- Screenshots:
- Logs:

**Comment by r10s** [comment]
@adbenitez thanks for filing this issue.

in fact, we've put much effort to this (and many more) topic in the last month while developing [android-dev](https://github.com/deltachat/deltachat-android-ii/issues/25) - which will replace the current f-droid release as soon as it is "ready".

**Comment by csb0730** [comment]
@adbenitez - do You see a red "!" at not sent messages? Maybe this is the issue I targeted too with an own fix.
If You like I can provide a self compiled apk which is based at v0.20.0 but with a fix for that resending issue.
See here for details https://github.com/csb0730/deltachat-core/blob/master/src/dc_job.c
(line 625 and following)

This approach is different from @r10s's fix, but it works fine :-)

Let me know if You want to do a trial ...

**Comment by csb0730** [comment]
Ah, I just saw, that I uploaded the apk here:

https://github.com/csb0730/deltachat-core/releases/download/v0.20.0uu9cs/dc-20181015-v0.20.0uu9cs.apk

But, because this is a self compiled apk You have to export a  backup from Your v0.20.0 version first, then deinstall this version, then install v0.20.0uu9cs and import the backup again. This is a must!

**Comment by adbenitez** [comment]
csb0730 thanks, but I was talking about the clock icon, I realized that if I wait up to 3min the message get delivered without needing a restart, probably it is simply that my network is a bit unstable, I have a friend that told me he was getting this red "!" and had to forward the message as a work around to resend it, it is supposed that DC must retry to send the messages in such a situation or it is the normal behaviour??

**Comment by csb0730** [comment]
Yes, this is normal behaviour and it has annoyed me relatively often. So I decided to make a fix. r10s gave me the starting point into the code.

In standard v0.20.0 DC tries to resend a message three times in general. As a retry only a try is counting for which the phone is indicating that it is online! So in general this seems to be reasonable logic.
But in reality this online state not seems to be accurate, so that under unstable network conditions the retry counter quickly reaches it's end: You see the red "!" and retries are stopped.

My approach does the assumption that only two consecutive tries under "online" condition are counting!
Additionally I decrement the counter again, if unstable state is detected by "not consecutive" online indicators!

This seems to work fine. I never detected the red "!" again and all messages are reliably sent (as quick as possible)  :-)

**Comment by csb0730** [comment]
@adbenitez 
Meanwhile I detected a scenarion where messages are really not sent. But this is related to wrong or bad network connection.
If WLAN is active and phone decides to use WLAN for data connection and this WLAN is weak and not really working DC tries to send messages, but DC can't be successful because of too bad conditions.
In this case it helps to switch WLAN off and immediately messages are sent by "mobile data connection" afterwards!

I'm using an old Samsung S3 and maybe this is related to that device, but this situation is really existing too. Maybe these hints are helping You?

**Comment by adbenitez** [comment]
csb0730 thanks for your work, but I think that if a message can't be sent due to unstable network, instead of this dead-end red [!] an easy way to retry/resend when the user consider it necessary should be provided, perhaps this comment should be a feature request.

**Comment by csb0730** [comment]
Under my conditions the dead-end has been reached very quick and often. And, I don't know if You know that: Former versions of DC did another approach and tried resending IMHO endless. So this resulted sometimes in other problems but prevented not sent messages unseen by user.
 The team recognized this situation and did a new resending approach too, while I finished my approach :-)

Now it's up to You: Try if You want or wait for next android-dev version which will IMHO have a solution for resending issue.
I don't see this discussion here as a feature request. If team's solution is working fine in future this is sufficient :-)

By the way: After the new imap/smtp approach which has been introduced (I think with version 0.18.x) I did not see the situation where I need to restart DC to force retrying of sending messages. Before that I can confirm Your experience!
