### ISSUE TITLE
Connection icon hiding

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-android#413]
I believe currently the connection icon is hidden by deltachat as soon as there is interactive use of the phone in an attempt to not show the icon all the time.  However when the screen is off this icon is still showing.  In theory this hides the icon from users, but in practice it can be confusing for two reasons:

1. Sometimes the icon can still be seen disappearing if the phone is a bit slow.  Then users might wonder why a deltachat notification just silently vanished.

2. On newer phones there is a feature where the phone shows a dim version of the lock screen when you pick it up, but before you still activate the screen.  In this state the deltachat icon is shown, however this then disappears as soon as the screen is actually activated.  Again resulting in the user wondering what happened to the notification.

This is fine to me since I had this described to me once how it works (even though I forgot the details).  But I think it could not be a great experience for users and wonder if there's a better way to handle things.

**Comment by r10s** [comment]
i think this can be closed.

since v0.101.0, 2019-02-12, after installation, after sending the first message or so, the user is asked to allow the app to disable "battery optimisations". if he allows this, the "connection icon" is no longer shown at all and all disadvantages as short-coming-in, similarity-to-normal-notifications and so on disappear.
