### ISSUE TITLE
In-Chat photo behaves differently based on orientation of phone

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#424]
Its unclear if this is already in the intended state.
- When I open the in-chat camera in profile view, the lower half of the chat window becomes the camera.
- When I do the same in landscape, the camera opens full screen.
- When I rotate from profile -> landscape the camera becomes full screen.
- When I rotate from landscape -> profile the camera stays full screen.

We should decide if this (inconsistent) behavior is what we want and if not, change it.

I personally don't use the half-camera so would miss nothing if we removed it and go full-screen every time.

**Comment by r10s** [comment]
well, i think this is just because the portait-expanded-or-not-state is just not tracked.

from a user point-of-view the described behaviour is "if we're in full screen, we stay in full screen" whereas landscape-mode only supports full screen.

so, i'd say it is not bad as it is currently and i would not change this. also as there was not much complaints about this point.

so i'd like to close this issue for now.
