### ISSUE TITLE
collect selected contacts at the top on group creation

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-android#426]
when creating a group, in a long list of contacts, it's difficult to keep the overview about who is selected... how about collecting the checked contacts at the top? or at least show a counter about how many contacts are selected...?
telegram UI also listed them at the top and said "5 members and me" in the title

**Comment by r10s** [comment]
this issue is stale, moreover, feature requests should better go to https://support.delta.chat - feel free to continue the discussion there.

**Comment by csb0730** [comment]
@violoncelloCH @r10s 

In spite of having an old issue discussion here one recommendation:

When the issue state "open" or "closed" is used as indicator if someone is working on a certain issue then "closed" issues should be tagged with their status.
a) If matter of issue is solved, then it should be tagged with "solved", otherwise b) for example simply no tag.

Then everyone sees clearly what is intended with an issue.

IMHO my first assumption was too, that a closed issue is always "solved", but I learned here that issue handling is a little bit different.

**Comment by violoncelloCH** [comment]
Well yes... Almost all projects I have seen only close issues which are either solved or have a state of "wontfix" (so also contributions on this are most likely to be not accepted)...
So if open/closed state is used differently, I'd support the idea of @csb0730 to use labels or something else to indicate if an idea suggested in an issue is generally accepted by maintainers or not :)

**Comment by r10s** [comment]
> use labels or something else to indicate if an idea suggested in an issue is generally accepted by maintainers or not

well, it is the other way round: issues that are closed because they do not match the requirements of an issue, are label. these are the the yellow-ish labels "feature request", "discussion", "question" etc. so it is already pretty easy to recognize.

apart from that, issues here are not used that much differently, usually, we also keep bugs and things someone is working on open until they're solved. this is also a psychological things, having a 1000 open things to do is not really nice.

all this was the outcome of discussions with  several devs, main reason was to avoid a situation with several hundreds or thousands of open issues - as seen in several other projects.

ah, and there is [Project Resurrection](https://github.com/orgs/deltachat/projects/19) for pull requests that are closed by seems to be worth finishing later, same for issues. however, as this also affects pull requests, this would not match the open/close paradigm at all.

but i agree, that this could communicated better - maybe @violoncelloCH, @csb0730 you can do a pr for the README that clarifies things? also, maybe the issue-template can be updated.
