### ISSUE TITLE
Set minSdkVersion to 19

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android#437]
As currently only 3.8% are below that mark and a lot of APIs are only usable on 19 or above I would highly suggest to update the minSdkVersion. Would that be fine for you @r10s?

**Comment by angelo-fuchs** [comment]
Just for completeness: I use a 4 year old phone (that is not that old for my perspective) and it has API Level 17 (Android 4.2.2).

**Comment by r10s** [comment]
okay, we cannot definitely not lock out the phones of the maintainers :)

**Comment by angelo-fuchs** [comment]
@r10s I disagree. If I'm the last (or so) user with such a phone, I'll get a new one.

**Comment by Hiboycubano** [comment]
I does not see this before but let me tell that in my area (Cuba) we are not a few using android 4.1 and getting a new phone is not easy(money).
And right now Delta Chat is spreading well. 

So, raising the target SDK without a real need may affect a lot of users

Thanks

**Comment by adbenitez** [comment]
Yes, recently I realized that exists some people using old Android versions like Android 4.1, and the fact that Delta Chat is compatible with 4.0 turned out to be a really nice feature.

**Comment by r10s** [comment]
okay, i have the same feeling.

also, there is currently no need to refactor code or so, so we can just leave the minSdkVersion for now.

however, imo it is totally fine if these old versions do not get support for some new features as map-view or video-recording if it turns out that the used libs have some higher sdk-requirements.
