### ISSUE TITLE
Can't share with pattern set

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#464]
I have set the Screen lock option to unlock Delta Chat with a pattern, but with this option set, sharing a file with Delta Chat doesn't work

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.98.2
- Steps to reproduce the problem: Go to Settings/Privacy and enable "Screen Lock" switch, close the app go to your file manager and try to share a file, select Delta Chat, you will prompted to enter your pattern, nothing happens, you get back to your file manager.

**Comment by Boehrsi** [comment]
Will look into that one.

**Comment by Loader009** [comment]
Nearly the same problem for PIN and on newer version.
(Mostly copied from adbenitez and changed the different things.)

Platform (android/blackberry/anbox): Android 8.1 (omniROM)
Device: suzu (Sony Xperia X)
Delta Chat Version: 0.100.0
Steps to reproduce the problem: Go to Settings/Privacy and enable "Screen Lock" switch, close the app go to your file manager and try to share a file, select Delta Chat, you will prompted to enter your pattern, enter the PIN prompt to enter the PIN will reappear, the same always happens if I enter the PIN.

**Comment by Boehrsi** [comment]
Yep, this issue shouldn't be related to the given Android version. The sharing stuff needs to be aware of the screen lock feature, which is currently missing and I hope it will be fixed next week.

**Comment by Boehrsi** [comment]
Fixed by:

- Allowing the ShareActivity to exist in the stack history
- Moved the deletion of unneeded content from onPause to onDestroy, to allow the ShareActivity to exist in the background (required as soon as the ScreenLockActivity takes over the screen)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/703
