### ISSUE TITLE
Lock pattern security issues

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#649]
When user press cancel/back on the pattern screen sometimes the Delta Chat screen (with the sensitive content) is briefly shown. 
Also when the app is put in background/minimized and user go to the app again, the chats list is shown (all chats and their last message are visible) when the user tries to open a chat, then the pattern screen is shown.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.98.2

**Comment by Boehrsi** [comment]
Will have a look. I assume this happens due to the older / special Android version used. I try to circumvent that problem.

**Comment by Boehrsi** [comment]
https://github.com/deltachat/deltachat-android/pull/706 should hopefully fix the mentioned problems.

**Comment by r10s** [comment]
> #706 should hopefully fix the mentioned problems.

on my nexus4 with lineage-oreo, the screen is still shown shortly when the app is exited and started again without switching the device off in between.

**Comment by r10s** [comment]
ahh, but with "screen security" also enabled, it works as expected for me  :)
makes some sense, maybe we should point the user in this direction.

**Comment by Boehrsi** [comment]
@r10s yep we should. Totally forgot to mention this. Only with screen security enabled (so disallowing screenshots) it is possible to hide to content completely. The reason is that a lot of device use the "screenshot" created for the app switcher as base when reopening the app. So the last state is shown while transitioning to the real app, before any onXYZ events of the Android lifecycle are kicking in. The only way to avoid this is to disallow the mentioned screenshots.
