### ISSUE TITLE
Use non-Google maps

### ISSUE THREAD

**Issue by licaon-kter** [deltachat/deltachat-android#654]
Eg. via `org.osmdroid:osmdroid-android`

**Comment by r10s** [comment]
afaik, currently, there are no maps at all, so, also no Google maps.

**Comment by licaon-kter** [comment]
@r10s You mean https://github.com/deltachat/deltachat-android/issues/414 ? Yeah...

**Comment by r10s** [comment]
well, #414 but also several other commits as https://github.com/deltachat/deltachat-android/commit/c5bf2cd00dfb073c23ebec1f6297636d27482ae1 or https://github.com/deltachat/deltachat-android/commit/04fd5cbf4db9bf944f09f8c2733ab70152764d9c plus lots of older ones have removed the google dependencies - not only to maps but also to playstore, cloud messaging and whatever. 

so, you see, we'll do a lot of stuff to make the app workable without google dependencies :)

due to no directly actionable item i would suggest to close this issue, however.
