### ISSUE TITLE
Layout new Group, Button shifted if text too long

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#657]
In German the Buttons in the 'New Group' screen are misaligned in Portrait View (presumably because the texts are too long)

**Comment by angelo-fuchs** [comment]
![screenshot_2019-01-24-14-06-11](https://user-images.githubusercontent.com/10619521/51680174-52df9d80-1fe1-11e9-93bb-7db67f68c164.png)

**Comment by r10s** [comment]
ahh, interesting. this is because of the word-wrap and the screen on the test device is rather small and the german translations are rather long.

i would suggest to disable word-wrap for the buttons.

btw. the correct german translation would be "QR-Einladungscode" (with hyphen, is already changed on transifex) - might be that already this fixes the problem :)

**Comment by adbenitez** [comment]
This was also happening for Spanish, didn't opened an issue before because I was not sure you were interested in this details :)

**Comment by r10s** [comment]
@adbenitez thanks for the info, one more reason to fix this :)
and also thanks for prefiltering :)
