### ISSUE TITLE
check, if images of older versions (<0.10 or so) may get deleted by housekeeping

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-android#676]
- Platform (android ): CYANOMODGEN - Android 6.1 
- Device: Samsung GT-N8013
- Delta Chat Version: 0.20.0 -> 0.100.0
- Expected behavior: old chats and pictures should be there as before
- Actual behavior:all pictures and videos except the one from yesterday are deleted from device (saw it in log)
- Steps to reproduce the problem: doing it one time is enough ...
- Screenshots:
- Logs: sorry, had no login credentials at that time and tried to restore an older backup (which failed too :-( )

**Comment by r10s** [comment]
that's bad :( thanks for reporting.

what does "from device" mean - from delta chat messages (so, from the blobdir as shown in settings/advanced/log) or from the devices gallery?
also, the files should still be together with the messages on the imap server.

just had a closer look to the code, in fact, 0.100.0 adds a "housekeeping" function that scans the blob directory and deletes files that are not referenced, see https://github.com/deltachat/deltachat-core/blob/master/src/dc_sqlite3.c#L894 - cannot really imaging how files from elsewhere get deleted.

in tests, thing works fine (of course, otherwise we would have fixed it :)

one think i can imaging is that the paths belonging to the messages are stored using absolute paths - this was done by delta 0.10.0 or so; at some point we changed to relative paths (storing just the name in the blob directory) and converted the existing absolute paths. might be that this conversions failed for some other reasons.

**Comment by haeckser** [comment]
I recognized it the first moment when I looked into the log (while discovering the new UI) and saw that a bunch of pictures were deleted ..
deleted from the device, not from mail server.
The device was migrated from version to version since 0.76 version one or two years ago. So the theory of absolute path might be correct.

Meanwhile I have rebooted the device and now I can reload an older backup (yes - stupidity - why not a current backup ....) but it seems that starting from old backup date, the mails from server will be loaded and added to chats  - great feature :-)
So my first bad feelings of 0.100 are getting calm and I would like to discover all the new features I didn't saw in the first shot :-)
Thanks a lot!!! to all active developer and supporters - Hope I can add something sometimes

**Comment by r10s** [comment]
cool, i'd like to keep this open for a while anyway :)

**Comment by r10s** [comment]
yip, thinking it over again, the absolute-conversion-path-thingie that failed on an older version is reasonable.
the conversion as such, however, is still present and will be executed as needed (just re-checked that).

anyway, there is nothing that could be done on this just now, agree to @haeckser and re-closing.
