### ISSUE TITLE
re-enable "invite activity"

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#796]
The invite feature is certainly needed by users, to get in touch with the messenger-only people (especially some groups) without having to manually scribble down the own email address in a clickable format, and composing all the necessary help/instruction about what deltachat is and how it is set up.

For a discussion about this, and a better invite message template see:
https://support.delta.chat/t/lets-switch-to-a-new-messenger/334

Please revert
https://github.com/deltachat/deltachat-android/pull/790
before the next release.

**Comment by hpk42** [comment]
a mobile-number based messenger can invite via other mobile-number based messengers and the UX can be made rather seemless.  DC's invite friends breaks this, as suddenly the receiving end needs to enter the unfamiliar terrain of providing their e-mail/password combo, see also https://delta.chat/en/2019-03-30-uxreport page 6 where it says: " Almost all users were confused that they had to enter their real email logindetails   from their  pre-existing  email   account(s),  and  not   to create  a new   app-specificpassword for Delta Chat. They expressed concern about Delta Chat having access to their email". 

If someone wants to tell friends to use DC, they can simply do it using whatever channels. We should not pretend that by providing an "invite friends" click, it becomes easy for the other side using it.   FWIW the FAQ now starts promininently with saying the other side does not need to install Delta, with a little graphic.  There is a plan to add more graphics and to majorly rework/refine the FAQ/help page.  This probably does a lot more than having a not-really-working "invite-friends" process. 

Once we have better on-boarding and graphics, better entry pages, we can reconsider looking at the invite/onboarding process.  The issue is not gone as long as you keep an interest in it and bring it up as appropriate :) If it turns out after the next release that lots of people say "where is that damn invite-friends link, i was relying on it!" we could go for re-enabling it.
