### ISSUE TITLE
'Login to your server' view not in dark mode

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#806]
with theme dark set the registration view still is in light mode

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: set theme to dark, go to your profile settings, tap in "password and account settings"(which is a bit hidden because the keyboard is shown by default in this view)

**Comment by r10s** [comment]
well, the "real" login view is never in dark mode because the user just does not have an option to switch to dark mode before logging in.

however, when changing the account data later, dark mode should be regarded.

> which is a bit hidden because the keyboard is shown by default in this view

the keyboard is no longer shown by default and _this_ dialog is tweaked a bit:

<img src=https://user-images.githubusercontent.com/9800740/55349540-40d71b00-54ba-11e9-8220-ac2bac77d139.png width=200>

**Comment by r10s** [comment]
i think when targeting this issue, on can also have a look at https://github.com/deltachat/deltachat-android/issues/439

**Comment by r10s** [comment]
@adbenitez sure - thank you for the report :)

**Comment by r10s** [comment]
fixed by #811
