### ISSUE TITLE
Delta chat consumes a lot of resources

### ISSUE THREAD

**Issue by Wiesensohle** [deltachat/deltachat-android#834]
- Platform (android/blackberry/anbox): Android 8
- Device: Samsung S7
- Delta Chat Version: from March 14, 2019
- Expected behavior: Resource-saving
- Actual behavior: On my Samsung S7 it uses a lot of battery and mobile data without me using it. My friends don't have the problem.
- Steps to reproduce the problem: Constantly
- Screenshots: https://www.h-felder.de/nextcloud/index.php/s/xd2mfz7EFZNz54r
- Logs: I have already deleted Delta-Chat, so I can't deliver logs.

Sorry, my english is very bad

**Comment by csb0730** [comment]
Since a few days I'm using v0.200.0 (Signal ui) and are able to compare to v0.20.0 (Telegram ui)
My experience is:

- v0.20.0  uses around 2% of battery in average
- v0.200.0 uses around 8% of battery in average
  (IMAP jobs only for inbox and message move to deltachat folder activated)

Relating data transmission I'm not shure to see any difference.

**Comment by r10s** [comment]
wrt battery, there are some ongoing discussions about this in the forum, eg. https://support.delta.chat/t/delta-chat-drains-battery/71/24
wrt mobile data, there are several issues files at https://github.com/deltachat/deltachat-core/labels/save-traffic

closing this issue therefore.
