### ISSUE TITLE
Implement a Backup functionality

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#89]
**Export/Backup**
- just a function to write all data to an sqlite database into a _well-defined folder_ - including all media files and settings
- the name of the written file may include the date as `deltachat-YYYYMMDD-HHMMSS.bak` which allows multiplie backups that do not overwrite each other

**Import**
- a function that imports the newest backup to Delta Chat from the _well-defined folder_
- on new installations, if there is a backup present, ask if to use this instead of a configuration - this will also make a MultiDevice installation easier if the backup contains the private key material
- this would also simplify if you switch between different app signatures, eg. from Google Play to F-Droid
- moreover, this would simplify switches from Android to iOS, Desktop ... (if we have these apps, of course ;-)

I think, this all can delayed after 1.0, ~~however, we should check if some settings can be saved in to the sqlite database instead of the [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences.html) (however, the most important settings as name, email, server settings are already in  the sqlite database)~~ I've had a look into the code and I think the current state is more or less okay: server settings are in the backup, gui settings are not. There may be good reasons to use different sounds, fontsizes etc. on different devices. Maybe the one or the other setting may be moved to sqlite, but in general, it seems fine to me.

**Comment by kollokollo** [comment]
This would probably be a nice to have function, but maybe its unnecessary. I could have used this feature, lost all data (als so also the encryption key) and had to reinstall Delta Chat. With a new installation I cannor read the old messages anymore. So If I would have backuped the key (which is possible) I could be OK now. Having backuped the chats as well would have been fine, too, but this is not the problem, because the chats are still on the server and could be backuped there. The important thing is a backup of the key (and store it on a different device). So if used correctly it is fine the way it is now. The question is if DC should automatically writeout the key to some file which is not lost, when DC is (accidentally) uninstalled.

**Comment by r10s** [comment]
implemented since [v0.9.5](https://delta.chat/en/2017-10-08-delta-chat-0.9.5)
