### ISSUE TITLE
Text input field size

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#91]
On my device when I write a message it shows only 4 lines of my message. After that the text input field does not expand any more and I have to scroll to read my full text before sending. I would appreciate this text input field size to be a little bigger, for example two more lines, to read and correct the written message before sending more comfortably.
Vielen Dank!

**Comment by r10s** [comment]
Well, I'm not sure if _just more_ lines fit on smaller displays.

**Comment by bokf** [comment]
OK, I thought it could be a short thing. I tested with Kontalk and Conversations and both seem to have no limit.
![screenshot_2017-05-19-08-17-23_cr](https://cloud.githubusercontent.com/assets/25562831/26236081/d64985e4-3c6e-11e7-84b3-94c2a87abd8d.png)
![screenshot_2017-05-19-08-18-27_cr](https://cloud.githubusercontent.com/assets/25562831/26236086/da4da4d6-3c6e-11e7-90c0-0ac88dc77f40.png)

**Comment by r10s** [comment]
Yeah, I would also vote for it :-) Any PR are welcome :-)

**Comment by kskarthik** [comment]
AFAIK even WA & Telegram has same problem...

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat

**Comment by csb0730** [comment]
@bokf 

Tried to tweak max input lines to 10 and it works well on my small S3 mini.

The only change which is needed is in
`deltachat-android/res/values/styles.xml`
where the line `<item name="android:maxLines">4</item>` needs to be changed to `<item name="android:maxLines">10</item>`

That's all.

@r10s - maybe You could do this directly without a PR because I need some time to get my repo updated again with local sources.

**Comment by csb0730** [comment]
@r10s - as long as the change is not done this issue should be reopened.

**Comment by csb0730** [comment]
Easier than thought. See PR.
