### ISSUE TITLE
close search-keyboard on click on "ok"

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#910]
v0.200.0

When search result is presented keyboard is still there and covers result list.

![Screenshot_2019-05-14-22-23-27](https://user-images.githubusercontent.com/30560716/57730338-8c274080-7698-11e9-8add-4c340c1fc00a.png)

Keyboard should be closed when first results are coming up.

**Comment by csb0730** [comment]
Maybe this is not an issue at standard devices, but at mini devices it is.

**Comment by r10s** [comment]
> Keyboard should be closed when first results are coming up.

well, i do not think so. there is no "search" button, so we cannot really say when the user is finished with typing. the user may want to refine the search or remove characters to become broader.

> Maybe this is not an issue at standard devices, but at mini devices it is.

but for these small devices you can hide the keyboard by the back button. this is one extra tap, however, to really know when the search is done (see above), we'd need a search button which would also require an extra tap.

so, one extra tap on small devices, no extra tap on normal devices (most devices are larger than the screenshot nowadays)

the discussion can be continued in the forum, however, i'd suggest to close the issue here.

**Comment by r10s** [comment]
just had a closer look: there is a "search" button on the keyboard that is currently unused.

- as the search is done incremental and automatically (normally fast ...), the "search" button should be converted to an "ok" button (as in the "new chat" activity where contacts can be search with an incremental search)

- a click on this "ok" should just hide the keyboard then. this is also the behavior in the "new chat" activity and also in many stock-android apps

i think this is a good compromise.

**Comment by csb0730** [comment]
Good proposal :+1: 
In addition to that, search could be started when this button is pressed and not before? This would make debouncer unnecessary and speed up search process again :+1:

**Comment by r10s** [comment]
> In addition to that, search could be started when this button is pressed and not before? This would make debouncer unnecessary and speed up search process again +1

well, i'd prefer making the additive search usable and/or check if #868 it is really a general issue :)

**Comment by Boehrsi** [comment]
I will add the suggested behavior today :).

**Comment by r10s** [comment]
cool :)

**Comment by r10s** [comment]
fixed by #918
