### ISSUE TITLE
move "export" to settings/chats

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#957]
currently, the "export" functions are at "settings / advanced", however, they should better go to "settings / chats" as the last option.

this change would require a little refactoring as "settings / advanced / manage keys" use the same function that is local to the advanced-fragment. however, this should not  be too hard.

@cyBerta maybe you can target this.

**Comment by csb0730** [comment]
Is "settings/chats" the right position for exporting all app data? There is a discussion at support.delta.chat.

IMHO it would be more clear for a user to have a seperate section "settings/import-export" for all these functions as they are not really related to chats only.

**Comment by csb0730** [comment]
... or another proposal: "settings/data management".
Here user should find all functions around export, import and compress function for database. Even key import/export would match to such a section, isn't it?

**Comment by r10s** [comment]
> Is "settings/chats" the right position for exporting all app data? There is a discussion at support.delta.chat

which discussion are you refering to? iirc there is only a discussion about whether an import should be possible without wiping data - but this is not the point in this issue.
the point of this issue is not to rewrite or change features in import/export. it's just to pull it out of "advanced".

> all these functions as they are not really related to chats only.

well, the title of the section is called "chats and media", so it should fit.
also, this is the place where users from other messengers will probably expect it mostly.

**Comment by csb0730** [comment]
discussion is this https://support.delta.chat/t/import-backup-only-at-new-install-no-import-menu-item-in-settings/445

> iirc thre is only a discussion about whether an import should be possible without wiping data - but this is not the point in this issue.
> the point of this issue is not to rewrite or change features in import/export. it's just to pull it out of "advanced".

It's clear not to change import process and it's also clear that import wipes ALL existing data.
But IMHO would vote for a dedicated item in settings because I would not search in chat's settings for import or export (don't know other messengers). The import replaces ALL settings and database, not only the messages and media. You know?
Import / Export is a global app function. Isn't it?

**Comment by r10s** [comment]
> Import / Export is a global app function. Isn't it?

well, "notifications" or "appearance" settings does not go to the backup, so it is not that clear.
I think if this pops up as an issue on user testing or so, we can think it over. for now, it is fine.

**Comment by adbenitez** [comment]
I think a good place where people would look for import/export an account is in their profile settings, as this import/export is not only the chats but more like the whole account, server settings, passwords, private key, etc. 
@r10s personally I was expecting all settings to be exported the first time I tried this functionality, since they aren't, I understand your point if you choose the chats and media entry.

**Comment by csb0730** [comment]
@adbenitez @r10s 
We know the internals around backup and know that full database including blobs is exported and imported. That's the reason for why I argued in that way before.

But meanwhile I checked WhatsApp and found that there the backup is done in chat's settings!

Don't know what WA is doing when backup but in DC's situation I find this the wrong position as the backup incluldes here all data and all settings.

**Comment by r10s** [comment]
> as the backup incluldes here all data and all settings.

as said, this is not really true. the backup contains chats, contacts and server settings. it dies not contain settings related to notifications, appearance etc (mainly because these settings are not really portable)

**Comment by adbenitez** [comment]
well, this is a better place than the old one so no blockers on my side :) +1

**Comment by csb0730** [comment]
@r10s 
but where are the other settings saved when not in database? Strange?!

**Comment by r10s** [comment]
> but where are the other settings saved when not in database? Strange?!

with the android settings/preferences classes, https://developer.android.com/guide/topics/ui/settings.html
