### ISSUE TITLE
ask before sending voice message

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#969]
DC v0.304.0
Android 4.1.2

When recording a voice message this is sent immediately after release of the button.

There is no chance to stop it. It would be recommend to ask user to send before doing it.

**Comment by r10s** [comment]
yip, I also thought about that. however, user are aware of this behavior through other messengers. and as far as I know, in the user testings, there were not much complains about this function.

closing this here, as a feature request, this should be better discussed in the support forum - also as there is also iOS.

**Comment by csb0730** [comment]
@r10s for me it's really an issue, not a feature request.

In old telegram UI there was a dialog before sending and that was a good approach.

In my own practice I sent some messages I really didn't want to sent but could not stop it !!!

In the moment voice messages behave like an input field which is sent in any case without a send
button to confirm sending! -> Not ok.

Please reopen this issue.

**Comment by strypey** [comment]
I agree with @csb0730 on this, because of 2 things:
1) Unlike matrix apps like Riot (now Element), Delta is unable to recall a message once it's been sent, 
2) On a mobile screen it's easy for the user's finger to slip off the record button without finishing their voice message.

When you put these together, it creates a high chance of users being inconvenienced by accidentally sending incomplete voice messages.
