### ISSUE TITLE
Self-destructing messages

### ISSUE THREAD

**Issue by rickcrash** [deltachat/deltachat-android#99]
Selfdestructing messages - like known by Signal messenger - would be nice.

Thank you for the great work!

**Comment by Hocceruser** [comment]
Technically, Delta Chat is an e-mail client. You can't do anything which isn't​ possible with e-mail either.
If you just sent the time when the message is supposed​ to be deleted within the message, this does only work if the other user uses Delta Chat as well, which is against the idea of Delta Chat.

**Comment by Hocceruser** [comment]
Technically, Delta Chat is an e-mail client. You can't do anything which isn't​ possible with e-mail either.
If you just sent the time when the message is supposed​ to be deleted together with the message, this would only work if the other user uses Delta Chat as well. Otherwise the message would never disappear because it is just a usual email.

**Comment by r10s** [comment]
I do not see much sense in  so called "selfdestructing messages". As a rule thumb selfdestructing messages on other systems: _You should assume they don’t work._

So even, if we would find a technical solution for this, you should always assume your messages is stored forever eg. as a screenshot... we should not encourage our users to rely on something like this for privacy for security.

In short: Normal messages may be stored forever by the recipients. Selfdestructing messages may be stored forever by the recipients, too.

**Comment by rickcrash** [comment]
Ok, you convinced me.

May be an option to adjust how many messages are kept would be helpful. 

For me the benfit of selfdestructing messages is more the clean, short chat than the disappearing after a given time.

**Comment by r10s** [comment]
:-)

**Comment by Hocceruser** [comment]
I also vote for the option to adjust how many (or for how long) messages are kept. You should maybe open a new issue for this.
On the other hand this is not that urgent because it is also possible to adjust this from the web front-end of your mail provider.

**Comment by labdsf** [comment]
This feature is useful indeed if you can trust your contacts not to store the messages outside the application. Signal has a great [blog post](https://signal.org/blog/disappearing-messages/) describing their threat model.

But all messengers that have self-destructing messages also implement forward secrecy. Signal and Wire have forward secrecy for all chats, and Telegram implements self-destructing messages only in so-called "secret chats". Keybase specifically implemented forward secrecy for their ["exploding messages"](https://keybase.io/blog/keybase-exploding-messages) only.

Otherwise you should assume that the server stores your messages forever, so if you eventually lose your private key, they can be restored even if you have them removed from all devices.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
